{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"smartsheet - Region\",\"smartsheet - Florida\",\"Order\",\"Perc\",\"Dol\",\"Tot\",\"Exec Sum\",\"Golf\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.1066.0 (23.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Order",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\E082336\\OneDrive - RSM\\Clubs Project\\Clubs Order.xlsx\"), null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Sheet1_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}}),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Classification\", type text}, {\"Order\", type text}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "c1abf8fd-c5d5-4403-a785-a78b3c8cf717"
      }
    ],
    "relationships": [
      {
        "name": "5ed5f536-d377-4305-91d2-5cb62002baa2",
        "fromColumn": "Year end",
        "fromTable": "smartsheet - Region",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_610958bb-1789-43bf-a11c-8faba4da955e"
      },
      {
        "name": "4a00b6aa-83a1-49e9-a4fb-56551f552f03",
        "fromColumn": "Year end",
        "fromTable": "smartsheet - Florida",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a8244fc7-8c0f-4d11-9005-3d05c57ca1d1"
      },
      {
        "name": "da62d0b4-468c-4c4a-90f6-55405cf1da86",
        "fromColumn": "Classification",
        "fromTable": "smartsheet - Region",
        "toColumn": "Classification",
        "toTable": "Exec Sum"
      },
      {
        "name": "de909d4d-80d9-4e9a-bf96-a27e97e58a5b",
        "fromColumn": "Classification",
        "fromTable": "Perc",
        "toColumn": "Classification",
        "toTable": "Exec Sum"
      },
      {
        "name": "ac3f3cb8-721e-4608-8dd9-e242e20ff000",
        "fromColumn": "Classification",
        "fromTable": "Dol",
        "toColumn": "Classification",
        "toTable": "Exec Sum"
      },
      {
        "name": "40671749-c41b-4dac-82b1-bf841cd4f66c",
        "fromColumn": "Classification",
        "fromTable": "Tot",
        "toColumn": "Classification",
        "toTable": "Exec Sum"
      },
      {
        "name": "5e7ce12c-a7dd-4026-ae7d-48b605a21660",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Classification",
        "fromTable": "Golf",
        "toColumn": "Classification",
        "toTable": "Exec Sum"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_c89bc7c5-dcda-4cbd-996f-c859000290d3",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f1d6b3b4-c838-4238-9150-05b19e56ae5e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "705068f9-1634-4a2a-b6f5-97675d921526",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d826dab2-ca55-4296-a8e9-19d1c146b224",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1b037957-f8f2-4954-b09d-74c1eb536c2a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dc7314e1-b954-4937-a695-ed478f6e78ab",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "55f3c58a-89ca-4896-a986-d25a4a4d7bf2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8aa5decf-339f-465e-8e19-ca9a82137cb5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f4993f25-094b-440d-b705-4f55e7840bff",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b2dc85f2-5dfc-4d31-a2b2-02c2718e6f04",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "fab4ced7-2ff0-4496-9c70-3678c885a860",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "afe1a811-b913-48de-b251-5fba7657cd29",
                "ordinal": 3
              }
            ],
            "lineageTag": "309a13cf-ea75-4044-8b0d-d9cdd92dfa88"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "cf010148-209a-4e14-83d2-e438fabf117f",
        "partitions": [
          {
            "name": "DateTableTemplate_c89bc7c5-dcda-4cbd-996f-c859000290d3-80da482d-32f9-4a9e-93a8-ec01bcaf2b0f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "smartsheet - Region",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15904ba2-7d65-46a4-83a6-e39114887d65",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Club name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd086c40-28ef-4298-9fe8-db4417474d74",
            "sourceColumn": "Club name",
            "summarizeBy": "none"
          },
          {
            "name": "Year end",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9afc307f-f56a-454c-86f3-44e158f4088c",
            "sourceColumn": "Year end",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_610958bb-1789-43bf-a11c-8faba4da955e"
                },
                "isDefault": true,
                "relationship": "5ed5f536-d377-4305-91d2-5cb62002baa2"
              }
            ]
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd63ca4f-2528-4f5c-94d3-434f4d11bd2b",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Mandatory Membership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b17873f1-aad4-4df6-9ea0-96464a87651e",
            "sourceColumn": "Mandatory Membership",
            "summarizeBy": "none"
          },
          {
            "name": "Full Member Equivalents (FME)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "a70bf369-f954-4747-89c6-e5247a68cfcb",
            "sourceColumn": "Full Member Equivalents (FME)",
            "summarizeBy": "sum"
          },
          {
            "name": "Refundable Equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cbf4fc6d-7d4a-467c-9513-aedccdf2e3c6",
            "sourceColumn": "Refundable Equity",
            "summarizeBy": "sum"
          },
          {
            "name": "Total equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "58c4f805-09bd-4c94-bea0-220da2698ac2",
            "sourceColumn": "Total equity",
            "summarizeBy": "sum"
          },
          {
            "name": "General Capital Assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0dac49ab-8dfa-4c22-89b0-b6dfab694cb0",
            "sourceColumn": "General Capital Assessment",
            "summarizeBy": "none"
          },
          {
            "name": "Capital Assessment Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "79ae841e-d10d-4de9-a9a1-ee6b4367ffe3",
            "sourceColumn": "Capital Assessment Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3fafdf38-9561-4a2a-86ea-ae9c17e4df61",
            "sourceColumn": "Operating Assessment",
            "summarizeBy": "none"
          },
          {
            "name": "Operating Assessment Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "379bc52f-634f-4f33-b1d8-06d2200c3a24",
            "sourceColumn": "Operating Assessment Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Other Capital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c03a4fc-dc81-44d9-a50a-8862663370f0",
            "sourceColumn": "Other Capital",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of general capital assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "520878fc-c98d-4a76-9a88-8f6c1c7a4b31",
            "sourceColumn": "Amount of general capital assessment",
            "summarizeBy": "sum"
          },
          {
            "name": "Major renovation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea8e0413-1fca-485c-9b5c-4d6dcf780c0e",
            "sourceColumn": "Major renovation",
            "summarizeBy": "none"
          },
          {
            "name": "Budgeted Major Capital Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "200fe955-ad39-49c8-9407-a2752ef1a024",
            "sourceColumn": "Budgeted Major Capital Project",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of Budgeted Major Capital Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "0e490e6c-58de-49e0-88cb-473beb38d466",
            "sourceColumn": "Amount of Budgeted Major Capital Project",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount of Budgeted Other Capital Projects",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "99797c6a-3a7b-4ef4-9b50-d71bc9b69265",
            "sourceColumn": "Amount of Budgeted Other Capital Projects",
            "summarizeBy": "sum"
          },
          {
            "name": "Ending PPE, net",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "434a1cc2-fae6-4c7e-8527-3ae73534d98c",
            "sourceColumn": "Ending PPE, net",
            "summarizeBy": "sum"
          },
          {
            "name": "Capital Expenditures (PP&E)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "58e9fc45-fcda-4a63-9a7a-51ba1b8528c9",
            "sourceColumn": "Capital Expenditures (PP&E)",
            "summarizeBy": "sum"
          },
          {
            "name": "Depreciation Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6217701a-f89c-4379-9bd2-1515c798ed49",
            "sourceColumn": "Depreciation Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Third Party Debt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6dae3c5d-37cd-4325-aa23-6fc38deb77d8",
            "sourceColumn": "Third Party Debt",
            "summarizeBy": "none"
          },
          {
            "name": "Total Third Party Debt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aa873a42-13f5-4158-ae13-b2e17ec712c7",
            "sourceColumn": "Total Third Party Debt",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Assets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b1c5153d-e0ca-409e-a88f-92ebaadd8d01",
            "sourceColumn": "Current Assets",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Liabilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bdc293a7-16e6-4d5f-a735-8dac8de48926",
            "sourceColumn": "Current Liabilities",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Liabilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d71d58e6-e8c6-4370-9d2b-2075217cb007",
            "sourceColumn": "Total Liabilities",
            "summarizeBy": "sum"
          },
          {
            "name": "Ending Net Assets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e7522bae-a37d-411a-8b51-ec1bc27e0ad2",
            "sourceColumn": "Ending Net Assets",
            "summarizeBy": "sum"
          },
          {
            "name": "Golf Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c6b69029-3450-4dc4-ac0a-eb260ecde1f5",
            "sourceColumn": "Golf Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Tennis Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "091b7623-9a18-4d73-bf5c-f882b109760c",
            "sourceColumn": "Tennis Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Pro Shop Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1d44f4c1-14fc-4ddc-98e0-9b99385db6c6",
            "sourceColumn": "Pro Shop Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Other Sports Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "652a9db6-58ec-4c2f-81e3-49ffba71b952",
            "sourceColumn": "Other Sports Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5c9fdd4f-50d6-4d42-be41-c25ea46f106c",
            "sourceColumn": "Dues Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Assessments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d099e15d-abf6-47db-8288-117b35980867",
            "sourceColumn": "Operating Assessments",
            "summarizeBy": "sum"
          },
          {
            "name": "Food Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7bf81ae5-9705-4131-8157-de2977457b2a",
            "sourceColumn": "Food Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Beverage Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4bb82e65-afd7-45af-8ec9-9d170d763270",
            "sourceColumn": "Beverage Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "All Other F&B Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9b569f35-fc7e-4179-b9a0-729150305eae",
            "sourceColumn": "All Other F&B Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Payroll and PTEB Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "43eb3576-67fa-4a06-a539-4dadfb43e669",
            "sourceColumn": "Payroll and PTEB Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Expenses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1a40115a-6fb0-4da1-9ece-d963d612c91a",
            "sourceColumn": "Operating Expenses",
            "summarizeBy": "sum"
          },
          {
            "name": "Property Taxes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "79844b85-ef1d-4e7e-b89f-75c481cef18c",
            "sourceColumn": "Property Taxes",
            "summarizeBy": "sum"
          },
          {
            "name": "Insurance Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "26a420b4-f87d-4953-a0fa-a87cc1c86df0",
            "sourceColumn": "Insurance Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Total employees in season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "2986dae9-e299-45f9-9358-2158a8597b6d",
            "sourceColumn": "Total employees in season",
            "summarizeBy": "sum"
          },
          {
            "name": "Use of Organized Foreign Labor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b243029-4ad0-4aeb-a409-5a1630fb6570",
            "sourceColumn": "Use of Organized Foreign Labor",
            "summarizeBy": "none"
          },
          {
            "name": "# Foreign Staff hired in yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "cc4a62fc-2169-44e1-8741-482c6ea6b4f1",
            "sourceColumn": "# Foreign Staff hired in yr",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Foreign Labor Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "8970f950-a714-471f-a969-6e6afc84a5f8",
            "sourceColumn": "Total Foreign Labor Costs",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Health Insurance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9890774f-03bb-4827-955f-f4eb1d472e03",
            "sourceColumn": "Increase in Health Insurance",
            "summarizeBy": "none"
          },
          {
            "name": "% inc. in Health Insurance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "14b0f56d-58b0-4639-9c07-c79cfb383278",
            "sourceColumn": "% inc. in Health Insurance",
            "summarizeBy": "sum"
          },
          {
            "name": "Food and Beverage Minimum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83af6663-46df-4f0a-91ac-1a1881a1f7e9",
            "sourceColumn": "Food and Beverage Minimum",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of F&B Minimum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "30daae2b-ea20-4ebd-8a5a-272888502539",
            "sourceColumn": "Amount of F&B Minimum",
            "summarizeBy": "sum"
          },
          {
            "name": "Automatic F&B Gratuity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "870f8108-dd00-4aef-8dad-15ffc35119ac",
            "sourceColumn": "Automatic F&B Gratuity",
            "summarizeBy": "none"
          },
          {
            "name": "% amt of F&B gratuity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7935ed28-8250-425a-97f3-6618ac371381",
            "sourceColumn": "% amt of F&B gratuity",
            "summarizeBy": "sum"
          },
          {
            "name": "Mandatory Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "981b0f3d-b849-48aa-9588-0b89f1c72aee",
            "sourceColumn": "Mandatory Service Charge",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of Monthly Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f3a5bb8f-d840-44d3-ab20-8727687ebe6c",
            "sourceColumn": "Amount of Monthly Service Charge",
            "summarizeBy": "sum"
          },
          {
            "name": "# full service kitchens",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "ffb427e4-d795-46dc-82b3-58c8638b3d7d",
            "sourceColumn": "# full service kitchens",
            "summarizeBy": "sum"
          },
          {
            "name": "# covers (include function / banquet)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "b57b6a50-58e4-4e17-b63a-6cc389f18aed",
            "sourceColumn": "# covers (include function / banquet)",
            "summarizeBy": "sum"
          },
          {
            "name": "#  function / banquet covers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "f2950501-5ba2-4c09-bc53-526c41400082",
            "sourceColumn": "#  function / banquet covers",
            "summarizeBy": "sum"
          },
          {
            "name": "Compensation Method for F&B Staff",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dffbaf43-9593-430e-943a-91c6c5d249ce",
            "sourceColumn": "Compensation Method for F&B Staff",
            "summarizeBy": "none"
          },
          {
            "name": "Food sales (exc Mins)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "54f184bb-09be-4fcd-9180-3b3b9058d87d",
            "sourceColumn": "Food sales (exc Mins)",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of food sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "77adb01b-5ea3-4a78-9015-58f5e4e71c1f",
            "sourceColumn": "Cost of food sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Beverage sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1bcc27cc-2e9e-42bb-bbcc-e952f5f2b1b9",
            "sourceColumn": "Beverage sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of beverage sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5c609d6d-dda6-4761-b3c7-4b748c6e1ade",
            "sourceColumn": "Cost of beverage sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Menu Prices",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0dcb47e-3651-4d16-afb4-ad95d77da66b",
            "sourceColumn": "Increase in Menu Prices",
            "summarizeBy": "none"
          },
          {
            "name": "Av % inc Menu Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "abed8e5b-2113-4139-8528-022f283ca56f",
            "sourceColumn": "Av % inc Menu Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Beverage Prices",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e94a5e07-34ec-426a-b15e-9fee81799364",
            "sourceColumn": "Increase in Beverage Prices",
            "summarizeBy": "none"
          },
          {
            "name": "Av % inc Bev Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "d5d877a6-26da-4b7e-9fd0-1de3b899c0d2",
            "sourceColumn": "Av % inc Bev Price",
            "summarizeBy": "sum"
          },
          {
            "name": "# of holes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "c7189330-60eb-4b8e-8275-d666e8ec8564",
            "sourceColumn": "# of holes",
            "summarizeBy": "sum"
          },
          {
            "name": "Maintained golf acreage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c219494c-31e0-460e-b6f1-9a5ae534488c",
            "sourceColumn": "Maintained golf acreage",
            "summarizeBy": "sum"
          },
          {
            "name": "Rounds per year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "700fd897-ca36-4083-822b-9176f00d9e2a",
            "sourceColumn": "Rounds per year",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  Salaries and wages",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "46bf3495-00c6-4d26-9e57-550867b2bdcb",
            "sourceColumn": "GCM  Salaries and wages",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  Payroll taxes and benefits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "94bbc0b2-b75b-4c99-9241-5d5a9548ca51",
            "sourceColumn": "GCM  Payroll taxes and benefits",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  Course supplies and contracts (includes gaso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d68b4192-18b1-46e7-95e2-47e99313bf9c",
            "sourceColumn": "GCM  Course supplies and contracts (includes gaso",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  Repairs & mtce (includes tree trimming, lake",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a973d75f-73ec-4f82-a3a6-48d7cf156e27",
            "sourceColumn": "GCM  Repairs & mtce (includes tree trimming, lake",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  Leased equipment expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "29aa9ec5-86cf-4108-810a-4c3c8f8f25a6",
            "sourceColumn": "GCM  Leased equipment expense",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  All other expenses (including utilities)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "431a3aea-c296-4f5d-b69d-f98d78a90564",
            "sourceColumn": "GCM  All other expenses (including utilities)",
            "summarizeBy": "sum"
          },
          {
            "name": "Type of Renovation  1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7aae0938-f552-400e-a19a-20fabc22590d",
            "sourceColumn": "Type of Renovation  1",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation  2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "286c0c6a-fdac-4d72-bdf9-28daed01943b",
            "sourceColumn": "Type of Renovation  2",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation  3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "840bd6d0-ceab-43c0-9116-60e67a389785",
            "sourceColumn": "Type of Renovation  3",
            "summarizeBy": "none"
          },
          {
            "name": "Zip Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79c38b81-6fa4-4b35-8693-e300a6cea28c",
            "sourceColumn": "Zip Code",
            "summarizeBy": "none"
          },
          {
            "name": "Clubs With Positive Working Capital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0%;-0%;0%",
            "lineageTag": "3bc87a7d-6380-472c-b34e-c3dfd1df995d",
            "sourceColumn": "Clubs With Positive Working Capital",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Revenue per FME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "DIVIDE('smartsheet - Region'[Dues Revenue], 'smartsheet - Region'[Full Member Equivalents (FME)],0)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isDataTypeInferred": true,
            "lineageTag": "4d52e75b-7972-45ec-8764-95b92cef9241",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Non-refundable equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "472c1086-55b7-4686-8468-35ab5cd376e4",
            "sourceColumn": "Non-refundable equity",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Rate - Current Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "0937d160-5fd9-4365-8932-af6efb970fcd",
            "sourceColumn": "Dues Rate - Current Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Rate - Audit Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "0145fb6e-c4e4-4221-9bcf-1165314d6575",
            "sourceColumn": "Dues Rate - Audit Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Type of Renovation - 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "515dbc9c-bc0a-4850-92ab-731cd3be02c1",
            "sourceColumn": "Type of Renovation - 1",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation - 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43a1a67f-37dc-43d5-b460-acae72e895d0",
            "sourceColumn": "Type of Renovation - 2",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation - 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d783b0d9-b728-4df3-9ef6-9b69e369e9a2",
            "sourceColumn": "Type of Renovation - 3",
            "summarizeBy": "none"
          },
          {
            "name": "Non-Owner Initiation fees",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2ea08985-7865-4f1b-9961-7037b001c7db",
            "sourceColumn": "Non-Owner Initiation fees",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of sales - F&B",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "4354c8be-e363-483b-b3f9-df41b5ae4601",
            "sourceColumn": "Cost of sales - F&B",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of Sales - Pro shop",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d2aa764a-2b9a-4f36-8b4b-2aeb3528de6e",
            "sourceColumn": "Cost of Sales - Pro shop",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Salaries and wages expense (EXC credit for M",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b400fced-78c9-4305-a218-5010c57f10cd",
            "sourceColumn": "F&B - Salaries and wages expense (EXC credit for M",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Less credit = 20% of F&B sales (only applies",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a52c9458-c05b-4235-a948-d696fff21901",
            "sourceColumn": "F&B - Less credit = 20% of F&B sales (only applies",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Payroll taxes and benefits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d08368d5-808e-4697-9e54-822dc111ae88",
            "sourceColumn": "F&B - Payroll taxes and benefits",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Employees' meals",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3554fc03-e16a-4920-ad38-496192a092be",
            "sourceColumn": "F&B - Employees' meals",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Laundry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d93ca25f-b4ee-4b1b-916d-4d0e3d9b38d5",
            "sourceColumn": "F&B - Laundry",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Linen, china, glass, silver",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ff5eeb08-1eaf-40b5-a4f8-fe75036f8b1b",
            "sourceColumn": "F&B - Linen, china, glass, silver",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Other expenses (excluding entertainment, val",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8f3f594a-b32d-41f8-bccb-06ad8b74fa59",
            "sourceColumn": "F&B - Other expenses (excluding entertainment, val",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH('smartsheet - Region'[Year end]) ",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "4f45dbb5-bde2-40db-8673-7a1c96afa7c6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('smartsheet - Region'[Year end])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "05b310cd-5344-4662-b045-3e50f1f649e8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Sports Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[Golf Revenue] + 'smartsheet - Region'[Tennis Revenue] + 'smartsheet - Region'[Other Sports Revenue] + 'smartsheet - Region'[Pro Shop Sales]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "7aeb9016-acd3-4f21-94a0-da447a70501f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "lineageTag": "0ff2ca74-12ab-4939-8fd7-dfbe91eaf373",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Tax and insurance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[Insurance Expense] + 'smartsheet - Region'[Property Taxes]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f87ff594-f5c1-4ca4-a867-0147f298c4f8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Rev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[Sports Revenue] + 'smartsheet - Region'[Dues Revenue] + 'smartsheet - Region'[Food Revenue] + 'smartsheet - Region'[Beverage Revenue] + 'smartsheet - Region'[All Other F&B Revenue]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isDataTypeInferred": true,
            "lineageTag": "54e38dd8-10ff-4ada-b6b9-91db62ef9adf",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Exp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[Payroll and PTEB Expense] + 'smartsheet - Region'[Cost of beverage sales] + 'smartsheet - Region'[Operating Expenses] + 'smartsheet - Region'[Cost of food sold] + 'smartsheet - Region'[Cost of Sales - Pro shop] + 'smartsheet - Region'[Insurance Expense] + 'smartsheet - Region'[Property Taxes]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isDataTypeInferred": true,
            "lineageTag": "04023ca5-d1a5-4c91-a877-5d0b13071ad2",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Restaurant sales per FME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "DIVIDE(('smartsheet - Region'[Food Revenue] + 'smartsheet - Region'[Beverage Revenue]), 'smartsheet - Region'[Full Member Equivalents (FME)],0)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isDataTypeInferred": true,
            "lineageTag": "3ee192dd-38e6-4e40-9221-219698b03dbc",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Annual Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[Amount of Monthly Service Charge] * 12",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isDataTypeInferred": true,
            "lineageTag": "1104e747-bb71-4016-91ad-6442dc0575f4",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Clubs with min and mandatory service charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "IF(",
              "    'smartsheet - Region'[Food and Beverage Minimum] = \"yes\" && 'smartsheet - Region'[Mandatory Service Charge] = \"yes\",",
              "    1,",
              "    0",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "isDataTypeInferred": true,
            "lineageTag": "23bf2fc5-86b5-435c-9af5-ce60c25762a6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Clubs with no min and mandatory service charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "IF(",
              "    'smartsheet - Region'[Automatic F&B Gratuity] = \"no\" && 'smartsheet - Region'[Mandatory Service Charge] =\"no\",",
              "    1,",
              "    0",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "isDataTypeInferred": true,
            "lineageTag": "5edbe502-caad-4773-8c5f-5ef9da19b2d8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Normalized Holes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "DIVIDE(18, 'smartsheet - Region'[# of holes],0)",
            "isDataTypeInferred": true,
            "lineageTag": "a7747bd8-4d78-4745-8b48-439022d26c19",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Full membership - total annual cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[Amount of F&B Minimum] + 'smartsheet - Region'[Amount of Monthly Service Charge] + 'smartsheet - Region'[Capital Assessment Amount] + 'smartsheet - Region'[Amount of general capital assessment] + 'smartsheet - Region'[Dues Rate - Audit Year] + 'smartsheet - Region'[Operating Assessment Amount]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isDataTypeInferred": true,
            "lineageTag": "00dd766f-1cf6-4279-89c1-0dc55709912c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Full membership - % that had a dues rate increase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF('smartsheet - Region'[Dues Rate - Current Year] > 'smartsheet - Region'[Dues Rate - Audit Year], 1, 0)",
            "formatString": "0%;-0%;0%",
            "isDataTypeInferred": true,
            "lineageTag": "72cadec0-f8a7-42d3-9691-2874a9fdd27e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "F&B departmental subsidy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "double",
            "expression": "('smartsheet - Region'[Food Revenue] + 'smartsheet - Region'[Beverage Revenue]) - ('smartsheet - Region'[Cost of food sold] + 'smartsheet - Region'[Cost of beverage sales] + 'smartsheet - Region'[F&B - Salaries and wages expense (EXC credit for M] + 'smartsheet - Region'[F&B - Less credit = 20% of F&B sales (only applies] + 'smartsheet - Region'[F&B - Payroll taxes and benefits] + 'smartsheet - Region'[F&B - Employees' meals] + 'smartsheet - Region'[F&B - Laundry] + 'smartsheet - Region'[F&B - Linen, china, glass, silver] + 'smartsheet - Region'[F&B - Other expenses (excluding entertainment, val])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isDataTypeInferred": true,
            "lineageTag": "72493e65-c153-4c3c-b9fa-d77b0a08312c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Fiscal_Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7779453e-d442-49bc-96be-1f2f978cc56a",
            "sourceColumn": "Fiscal_Year",
            "summarizeBy": "none"
          },
          {
            "name": "Full membership - joining fees",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[Refundable Equity] + 'smartsheet - Region'[Non-refundable equity]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isDataTypeInferred": true,
            "lineageTag": "326156f1-900b-4255-a8a7-54eac6194e53",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Food and beverage (F&B) revenues",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[Food Revenue] + 'smartsheet - Region'[Beverage Revenue]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isDataTypeInferred": true,
            "lineageTag": "7f6bc780-88c5-48d6-8814-432467f76786",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "GCM Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[GCM  All other expenses (including utilities)] + 'smartsheet - Region'[GCM  Course supplies and contracts (includes gaso] + 'smartsheet - Region'[GCM  Leased equipment expense] + 'smartsheet - Region'[GCM  Payroll taxes and benefits] + 'smartsheet - Region'[GCM  Repairs & mtce (includes tree trimming, lake] + 'smartsheet - Region'[GCM  Salaries and wages]",
            "isDataTypeInferred": true,
            "lineageTag": "0de2b3b5-b380-42c1-a474-1d6efa4d9978",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Tot Equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[Refundable Equity] + 'smartsheet - Region'[Non-refundable equity]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isDataTypeInferred": true,
            "lineageTag": "4eef6c76-db43-46fb-b23b-8e87618e594c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Cost of sales F&B",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[Cost of food sold] + 'smartsheet - Region'[Cost of beverage sales]",
            "isDataTypeInferred": true,
            "lineageTag": "d374002a-07cd-4c0d-a726-bd8cd4db0d82",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "% of clubs increasing fees",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF('smartsheet - Region'[Dues Rate - Current Year] > 'smartsheet - Region'[Dues Rate - Audit Year], 1, 0)",
            "formatString": "0%;-0%;0%",
            "isDataTypeInferred": true,
            "lineageTag": "c4ecf79f-bdeb-4173-866b-7a6015541ae4",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "In-house pro shop",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF('smartsheet - Region'[Pro Shop Sales]>0,1,0)",
            "formatString": "0%;-0%;0%",
            "isDataTypeInferred": true,
            "lineageTag": "38d1a41f-b9c9-4fe9-96da-f0cdffca8348",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Membership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d900ccb-b73e-4a09-b5ba-f28ce651f47c",
            "sourceColumn": "Total Membership",
            "summarizeBy": "sum"
          },
          {
            "name": "Unnamed: 6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6290e198-8b27-456d-bec9-e20e8fa169c4",
            "sourceColumn": "Unnamed: 6",
            "summarizeBy": "none"
          },
          {
            "name": "Order.Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82f722f0-b890-455d-8864-2d983215aa5b",
            "sourceColumn": "Order.Order",
            "summarizeBy": "none"
          },
          {
            "name": "Total covers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[#  function / banquet covers] + 'smartsheet - Region'[# covers (include function / banquet)]",
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "e7918293-b490-46a9-9e66-6e5d3809a372",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "F&B All other expenses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[F&B - Employees' meals] + 'smartsheet - Region'[F&B - Laundry] + 'smartsheet - Region'[F&B - Less credit = 20% of F&B sales (only applies] + 'smartsheet - Region'[F&B - Linen, china, glass, silver] + 'smartsheet - Region'[F&B - Other expenses (excluding entertainment, val]",
            "isDataTypeInferred": true,
            "lineageTag": "8e18bbd8-bf01-4f95-916f-3b067acca658",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "F&B Total Expenses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "'smartsheet - Region'[F&B - Payroll taxes and benefits] + 'smartsheet - Region'[F&B - Salaries and wages expense (EXC credit for M] + 'smartsheet - Region'[F&B All other expenses]",
            "isDataTypeInferred": true,
            "lineageTag": "4f0c898c-620d-4135-bd1c-5f368a6fb0b1",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Type of Renovation  4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4cc34669-2e89-44d2-a661-ac28535bd848",
            "sourceColumn": "Type of Renovation  4",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f2b1f587-9f55-431c-9263-1658d41c7db9",
        "measures": [
          {
            "name": "Full membership - refundable equity percentages",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Refundable Equity]), SUM('smartsheet - Region'[Tot Equity]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5c27d323-cd1e-47d9-a352-d5036e8e202c"
          },
          {
            "name": "Third-party debt per FME",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Total Third Party Debt]), SUM('smartsheet - Region'[Full Member Equivalents (FME)]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "0851762f-9eab-4b99-820f-dbdf6da5d31d"
          },
          {
            "name": "Capital Improvements to Depreciation Expense",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Amount of Budgeted Major Capital Project]), SUM('smartsheet - Region'[Depreciation Expense]))",
            "formatString": "0%;-0%;0%",
            "lineageTag": "aa555271-84a9-4452-a795-3b854b162e06"
          },
          {
            "name": "Working Capital Ratio2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "VALUE(DIVIDE(SUM('smartsheet - Region'[Current Assets]), SUM('smartsheet - Region'[Current Liabilities]), 0))",
            "lineageTag": "78f00160-01d1-413c-9367-d0f920ffb236"
          },
          {
            "name": "Dues Revenue FY22",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE('smartsheet - Region'[Dues Revenue per FME]),",
              "    YEAR('smartsheet - Region'[Year end]) = 2022,",
              "    VALUES('smartsheet - Region'[Classification])",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "fc3ba5ce-53be-4c09-ab22-b8ad4a9aa404"
          },
          {
            "name": "Dues Revenue Change",
            "expression": "[Dues Revenue FY23] - [Dues Revenue FY22]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8cf4534e-6979-4769-a544-90e8616d20c2"
          },
          {
            "name": "Dues Revenue % Change",
            "expression": "DIVIDE(([Dues Revenue FY23] - [Dues Revenue FY22]), [Dues Revenue FY22],0)",
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "0142a081-7574-4f76-a34d-ed7489183510"
          },
          {
            "name": "Initiation Fees / FME",
            "expression": "DIVIDE(SUM('smartsheet (2)'[NonOwner Initiation fees]), SUM('smartsheet (2)'[Full Member Equivalents (FME)]),0)",
            "lineageTag": "f48bdbd4-e223-4116-83eb-f06a8ad16782"
          },
          {
            "name": "Capital Improvements per FME",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Capital Expenditures (PP&E)]), SUM('smartsheet - Region'[Full Member Equivalents (FME)]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "37cb6475-78da-403d-8e80-6268132201bf"
          },
          {
            "name": "Budgeted Capital Improvements %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('smartsheet - Region'[Budgeted Major Capital Project]),",
              "        'smartsheet - Region'[Budgeted Major Capital Project] = \"Yes\"",
              "    ),",
              "    COUNT('smartsheet - Region'[Budgeted Major Capital Project])",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "1183ad57-605b-4c3c-b644-a394e1a64c6d"
          },
          {
            "name": "Third Party Debt %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('smartsheet - Region'[Third Party Debt]),",
              "        'smartsheet - Region'[Third Party Debt] = \"Yes\"",
              "    ),",
              "    COUNT('smartsheet - Region'[Third Party Debt])",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "a4dc5edd-11ad-45bb-bf59-9b0e198d1c25"
          },
          {
            "name": "Annual Capital Assessment %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('smartsheet - Region'[General Capital Assessment]),",
              "        'smartsheet - Region'[General Capital Assessment] = \"yes\"",
              "    ),",
              "    COUNT('smartsheet - Region'[General Capital Assessment])",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "ee0e2cb4-1eb3-4532-bb05-1fbb8a6686cd"
          },
          {
            "name": "Other Capital %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('smartsheet - Region'[Other Capital]),",
              "        'smartsheet - Region'[Other Capital] = \"Yes\"",
              "    ),",
              "    COUNT('smartsheet - Region'[Other Capital])",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "7ee3e950-25fe-4a34-80c9-a600bd4b51ce"
          },
          {
            "name": "GCM per Hole",
            "expression": "DIVIDE(SUM('smartsheet - Region'[GCM Total]), SUM('smartsheet - Region'[# of holes]),0) ",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "8e7f5f16-87ad-42cb-9ab7-b77127cb1f87"
          },
          {
            "name": "GCM salaries and wages per hole",
            "expression": "DIVIDE(SUM('smartsheet - Region'[GCM  Salaries and wages]), SUM('smartsheet - Region'[# of holes]),0) ",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c5c0d2ca-d58a-486e-ae74-fdf5d882e40b"
          },
          {
            "name": "GCM PTEB per hole",
            "expression": "DIVIDE(SUM('smartsheet - Region'[GCM  Payroll taxes and benefits]), SUM('smartsheet - Region'[# of holes]),0) ",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a26f0d0c-0163-4eae-882a-48817f00511f"
          },
          {
            "name": "GCM course supplies per hole",
            "expression": "DIVIDE(SUM('smartsheet - Region'[GCM  Course supplies and contracts (includes gaso]), SUM('smartsheet - Region'[# of holes]),0) ",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "795c0c8d-b92f-46cb-98dc-a3e24a3b1d68"
          },
          {
            "name": "GCM repairs and maintenance per hole",
            "expression": "DIVIDE(SUM('smartsheet - Region'[GCM  Repairs & mtce (includes tree trimming, lake]), SUM('smartsheet - Region'[# of holes]),0) ",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "0121f3d1-67ca-4ff8-afff-2e5b0b5f0c5f"
          },
          {
            "name": "GCM leased equipment per hole",
            "expression": "DIVIDE(SUM('smartsheet - Region'[GCM  Leased equipment expense]), SUM('smartsheet - Region'[# of holes]),0) ",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "37344580-c4f6-4127-8896-007c32cb96c5"
          },
          {
            "name": "GCM all other expenses per hole",
            "expression": "DIVIDE(SUM('smartsheet - Region'[GCM  All other expenses (including utilities)]), SUM('smartsheet - Region'[# of holes]),0) ",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "3a2bbee4-928a-4eed-8135-4d4b63e00e2d"
          },
          {
            "name": "Food & Beverage Cost of Sales %",
            "expression": "DIVIDE((SUM('smartsheet - Region'[Food Revenue]) + SUM('smartsheet - Region'[Beverage Revenue])), (SUM('smartsheet - Region'[Cost of food sold]) + SUM('smartsheet - Region'[Cost of beverage sales])),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "35ba986a-419d-4e51-a9c4-d008fc6ac9e1"
          },
          {
            "name": "Dues Rev%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('smartsheet - Region'[Dues Revenue]) / (SUM('smartsheet - Region'[Dues Revenue]) + SUM('smartsheet - Region'[Sports Revenue]) + SUM('smartsheet - Region'[Food Revenue]) + SUM('smartsheet - Region'[Beverage Revenue]) + SUM('smartsheet - Region'[All Other F&B Revenue]))",
            "lineageTag": "67773f00-950c-45ca-8ea6-89d19d049cce"
          },
          {
            "name": "Dues Revenue%",
            "expression": "SUM('smartsheet - Region'[Dues Revenue]) / (SUM('smartsheet - Region'[Dues Revenue]) + SUM('smartsheet - Region'[Sports Revenue]) + SUM('smartsheet - Region'[Food Revenue]) + SUM('smartsheet - Region'[Beverage Revenue]) + SUM('smartsheet - Region'[All Other F&B Revenue]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "242d3261-6827-4474-8412-ef1190304315"
          },
          {
            "name": "Sports Revenue%",
            "expression": "SUM('smartsheet - Region'[Sports Revenue]) / (SUM('smartsheet - Region'[Dues Revenue]) + SUM('smartsheet - Region'[Sports Revenue]) + SUM('smartsheet - Region'[Food Revenue]) + SUM('smartsheet - Region'[Beverage Revenue]) + SUM('smartsheet - Region'[All Other F&B Revenue]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ef848e05-3b6e-4722-bbc1-e5476fba7e66"
          },
          {
            "name": "Food Revenue%",
            "expression": "SUM('smartsheet - Region'[Food Revenue]) / (SUM('smartsheet - Region'[Dues Revenue]) + SUM('smartsheet - Region'[Sports Revenue]) + SUM('smartsheet - Region'[Food Revenue]) + SUM('smartsheet - Region'[Beverage Revenue]) + SUM('smartsheet - Region'[All Other F&B Revenue]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a6f45546-4f28-4092-be3d-117a900f2107"
          },
          {
            "name": "Beverage Revenue%",
            "expression": "SUM('smartsheet - Region'[Beverage Revenue]) / (SUM('smartsheet - Region'[Dues Revenue]) + SUM('smartsheet - Region'[Sports Revenue]) + SUM('smartsheet - Region'[Food Revenue]) + SUM('smartsheet - Region'[Beverage Revenue]) + SUM('smartsheet - Region'[All Other F&B Revenue]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "95b82362-a4ea-442f-b14f-029e3d6a6ed4"
          },
          {
            "name": "Other Revenue%",
            "expression": "SUM('smartsheet - Region'[All Other F&B Revenue]) / (SUM('smartsheet - Region'[Dues Revenue]) + SUM('smartsheet - Region'[Sports Revenue]) + SUM('smartsheet - Region'[Food Revenue]) + SUM('smartsheet - Region'[Beverage Revenue]) + SUM('smartsheet - Region'[All Other F&B Revenue]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "8ef08b39-e791-4620-8803-78dbd9844a95"
          },
          {
            "name": "Payroll and related expense %",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Payroll and PTEB Expense]), SUM('smartsheet - Region'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7ef76777-ae5f-4ded-bb28-a138061ad5e9"
          },
          {
            "name": "Cost of sales - F&B expense %",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Cost of sales F&B]), SUM('smartsheet - Region'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2cc90fa3-6579-4f8d-a00b-6327cba4050b"
          },
          {
            "name": "Operating expense %",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Operating Expenses]) + SUM('smartsheet - Region'[Cost of Sales - Pro shop]), SUM('smartsheet - Region'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0f69252a-c6b2-4bff-a8c2-9d7dc710f8b5"
          },
          {
            "name": "Tax and insurance expense %",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Tax and insurance]), SUM('smartsheet - Region'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c5d8b2ff-5e1d-422f-b4be-38dd39c7d3d9"
          },
          {
            "name": "Dues per FME",
            "expression": "SUM('smartsheet - Region'[Dues Revenue]) / SUM('smartsheet - Region'[Full Member Equivalents (FME)])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "120d7183-8986-4ab6-ac55-0757ec63fcf2"
          },
          {
            "name": "Sports per FME",
            "expression": "SUM('smartsheet - Region'[Sports Revenue]) / SUM('smartsheet - Region'[Full Member Equivalents (FME)])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d376ec97-cca1-4150-98fb-821cfda69903"
          },
          {
            "name": "Food per FME",
            "expression": "SUM('smartsheet - Region'[Food Revenue]) / SUM('smartsheet - Region'[Full Member Equivalents (FME)])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7f3e589c-524e-4e60-bc52-2a99a04d44b5"
          },
          {
            "name": "Beverage per FME",
            "expression": "SUM('smartsheet - Region'[Beverage Revenue]) / SUM('smartsheet - Region'[Full Member Equivalents (FME)])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "bca3f271-364f-4a00-83ce-476ae5d49276"
          },
          {
            "name": "Other per FME",
            "expression": "SUM('smartsheet - Region'[All Other F&B Revenue]) / SUM('smartsheet - Region'[Full Member Equivalents (FME)])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ac7b7493-274e-4d1a-9bbf-4acd76e1c4b8"
          },
          {
            "name": "Total Revenue per FME",
            "expression": "(SUM('smartsheet - Region'[Sports Revenue]) + SUM('smartsheet - Region'[Dues Revenue]) + SUM('smartsheet - Region'[Food Revenue]) + SUM('smartsheet - Region'[Beverage Revenue]) + SUM('smartsheet - Region'[All Other F&B Revenue])) / SUM('smartsheet - Region'[Full Member Equivalents (FME)])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6fdd8300-5949-47af-ba82-165f1e6bd2d9"
          },
          {
            "name": "Payroll and Related per FME",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Payroll and PTEB Expense]), SUM('smartsheet - Region'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "142e1b8e-db6b-408c-9718-5061e49f4efe"
          },
          {
            "name": "Cost of sales - F&B per FME",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Cost of sales F&B]), SUM('smartsheet - Region'[Full Member Equivalents (FME)]), 0)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e17c26af-8a6d-40d4-899e-4c9d4f2b19b6"
          },
          {
            "name": "Operating per FME",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Operating Expenses]) + SUM('smartsheet - Region'[Cost of Sales - Pro shop]), SUM('smartsheet - Region'[Full Member Equivalents (FME)]), 0)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6eba4988-ff8b-471a-b945-3fe4baffd4f5"
          },
          {
            "name": "Tax and insurance per FME",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Tax and insurance]), SUM('smartsheet - Region'[Full Member Equivalents (FME)]), 0)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "db0ff6ed-a820-4a01-8e7a-99f963045306"
          },
          {
            "name": "Total Expenses per FME",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Total Exp]), SUM('smartsheet - Region'[Full Member Equivalents (FME)]), 0)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "987a73df-479a-40b4-8820-d7b592a0f744"
          },
          {
            "name": "Dues Revenue FY23",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE('smartsheet - Region'[Dues Revenue per FME]),",
              "    YEAR('smartsheet - Region'[Year end]) = 2023,",
              "    VALUES('smartsheet - Region'[Classification])",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "96c7c196-ac8b-4b3c-b6f7-c7cbb2a06228"
          },
          {
            "name": "Memberships (FME) to employees",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Full Member Equivalents (FME)]), SUM('smartsheet - Region'[Total employees in season]),0)",
            "formatString": "0.0",
            "lineageTag": "1e3f4471-6106-4418-92e0-e6951abc9c51"
          },
          {
            "name": "Food Gross Profit %",
            "expression": "DIVIDE((SUM('smartsheet - Region'[Food Revenue]) - SUM('smartsheet - Region'[Cost of food sold])), SUM('smartsheet - Region'[Food Revenue]),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "3be33e57-ccd8-459a-aa88-39aabb791d86"
          },
          {
            "name": "Cost of Food Sold %",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Cost of food sold]), SUM('smartsheet - Region'[Food Revenue]),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "1024af11-fe50-47b4-b748-30a45a69dbc4"
          },
          {
            "name": "Beverage Gross Profit %",
            "expression": "DIVIDE((SUM('smartsheet - Region'[Beverage Revenue]) - SUM('smartsheet - Region'[Cost of beverage sales])), SUM('smartsheet - Region'[Beverage Revenue]),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "1494ddeb-5fff-4338-a720-121b60bab442"
          },
          {
            "name": "Cost of Beverage Sold %",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Cost of beverage sales]), SUM('smartsheet - Region'[Beverage Revenue]),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "396bf819-e925-4124-9602-8a25f0179967"
          },
          {
            "name": "F&B Gross Profit %",
            "expression": [
              "",
              "DIVIDE(",
              "    (",
              "        (SUM('smartsheet - Region'[Beverage Revenue]) + SUM('smartsheet - Region'[Food Revenue]))",
              "         - (SUM('smartsheet - Region'[Cost of beverage sales]) + SUM('smartsheet - Region'[Cost of food sold]))",
              "    ), ",
              "    (SUM('smartsheet - Region'[Beverage Revenue]) + SUM('smartsheet - Region'[Food Revenue])),",
              "    0",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "58a6e47b-06e2-44fc-8eac-3cdc8dfce9e8"
          },
          {
            "name": "Cost of F&B %",
            "expression": [
              "",
              "DIVIDE(",
              "    (",
              "        (SUM('smartsheet - Region'[Cost of beverage sales]) + SUM('smartsheet - Region'[Cost of food sold]))",
              "    ), ",
              "    (SUM('smartsheet - Region'[Beverage Revenue]) + SUM('smartsheet - Region'[Food Revenue])),",
              "    0",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "693986ac-b97e-48c2-8a4c-3bafe2df9f40"
          },
          {
            "name": "Food sales to beverage",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Food Revenue]), SUM('smartsheet - Region'[Beverage Revenue]),0)",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "97b2e2a2-8813-4bb8-98c8-93484053764c"
          },
          {
            "name": "GCM cost per hole - 18 holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b4fb2c02-21e1-4279-a32b-67dcf52453ae"
          },
          {
            "name": "GCM Total operating expense - 18 holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[Total Exp]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "f01be75a-653c-4a0e-8a11-681ffda79bb3"
          },
          {
            "name": "Rounds per year - 18 holes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        AVERAGE('smartsheet - Region'[Rounds per year]),",
              "        'smartsheet - Region'[# of holes] = 18)"
            ],
            "lineageTag": "fc127d4d-32e2-4aae-a598-871d2f49a1eb"
          },
          {
            "name": "Rounds per year - multiple course",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        AVERAGE('smartsheet - Region'[Rounds per year]),",
              "        'smartsheet - Region'[# of holes] > 18)",
              "        *",
              "    CALCULATE(",
              "        DIVIDE(18, AVERAGE('smartsheet - Region'[# of holes]),0),",
              "        'smartsheet - Region'[# of holes] > 18)"
            ],
            "lineageTag": "70214774-1a43-4c10-9b31-ea1f35d2380b"
          },
          {
            "name": "GCM Total - multiple holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "5aecd4bd-15df-40ce-8cd3-dd51d208dd5d"
          },
          {
            "name": "GCM Total operating expense - multiple course",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[Total Exp]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "29615e06-cde7-4762-a243-f9459028b60c"
          },
          {
            "name": "Rounds per year - 18 holes 2022",
            "expression": [
              "",
              "    CALCULATE(",
              "        AVERAGE('smartsheet - Region'[Rounds per year]),",
              "        'smartsheet - Region'[# of holes] = 18,",
              "        'smartsheet - Region'[Year] = 2022)"
            ],
            "formatString": "0",
            "lineageTag": "4c8ab093-e8c1-45cb-8f3b-44eedf9412ce"
          },
          {
            "name": "Rounds per year - 18 holes 2023",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        AVERAGE('smartsheet - Region'[Rounds per year]),",
              "        'smartsheet - Region'[# of holes] = 18,",
              "        'smartsheet - Region'[Year] = 2023)"
            ],
            "lineageTag": "f5277125-9c68-4588-bf9b-3731cc9cfcee"
          },
          {
            "name": "Round 18 Change",
            "expression": "DIVIDE(([Rounds per year - 18 holes 2023] - [Rounds per year - 18 holes 2022]), [Rounds per year - 18 holes 2022],0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4bdfa547-e88a-47a5-871d-6533ae684bd6"
          },
          {
            "name": "Rounds per year - multiple course 2023",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        AVERAGE('smartsheet - Region'[Rounds per year]),",
              "        'smartsheet - Region'[# of holes] > 18,",
              "\t    'smartsheet - Region'[Year] = 2023)",
              "        *",
              "    CALCULATE(",
              "        DIVIDE(18, AVERAGE('smartsheet - Region'[# of holes]),0),",
              "        'smartsheet - Region'[# of holes] > 18,",
              "\t    'smartsheet - Region'[Year] = 2023)"
            ],
            "lineageTag": "95e36c1f-fc76-4135-8872-2d7dfc62818c"
          },
          {
            "name": "Rounds per year - multiple course 2021",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        AVERAGE('smartsheet - Region'[Rounds per year]),",
              "        'smartsheet - Region'[# of holes] > 18,",
              "\t    YEAR('smartsheet - Region'[Year end]) = 2021)",
              "        *",
              "    CALCULATE(",
              "        DIVIDE(18, AVERAGE('smartsheet - Region'[# of holes]),0),",
              "        'smartsheet - Region'[# of holes] > 18,",
              "\t    YEAR('smartsheet - Region'[Year end]) = 2021)"
            ],
            "lineageTag": "57f1baf7-d6f9-4f2f-8f06-908a8d9f99c0"
          },
          {
            "name": "Multiple Course Change",
            "expression": "DIVIDE(([Rounds per year - multiple course 2023] - [Rounds per year - multiple course 2021]), [Rounds per year - multiple course 2021],0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "6c4af810-cca4-4db0-9b17-3763b76473ed"
          },
          {
            "name": "Maintained acres - 18 holes",
            "expression": [
              "",
              "    CALCULATE(",
              "        AVERAGE('smartsheet - Region'[Maintained golf acreage]),",
              "        'smartsheet - Region'[# of holes] = 18)"
            ],
            "formatString": "0",
            "lineageTag": "2b244393-f53a-4a70-bdb8-09d37517e414"
          },
          {
            "name": "GCM cost per acre - 18 holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[Maintained golf acreage]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "bd3af116-1984-4667-934f-37f88af2128f"
          },
          {
            "name": "GCM cost per round - 18 holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[Rounds per year]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "4d38f8ab-fa0e-4d53-9f3e-bb1cffcd7253"
          },
          {
            "name": "Maintained acres - multiple holes",
            "expression": [
              "",
              "    CALCULATE(",
              "        AVERAGE('smartsheet - Region'[Maintained golf acreage]),",
              "        'smartsheet - Region'[# of holes] > 18)"
            ],
            "formatString": "0",
            "lineageTag": "08dc9e14-66df-4549-a63c-edd82a9921c6"
          },
          {
            "name": "GCM cost per acre - multiple holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[Maintained golf acreage]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "93e48326-3de2-4cb6-9342-00bd0787a126"
          },
          {
            "name": "GCM cost per round - multiple holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[Rounds per year]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "926c90c8-5d8a-4258-8b8f-879603541734"
          },
          {
            "name": "GCM cost per acre - 18 holes 2023",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] = 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2023",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2023",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c897fee4-d062-45fa-840f-c1a0d5046cd6"
          },
          {
            "name": "GCM cost per acre - 18 holes 2022",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] = 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2022",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2022",
              "    ),",
              "    0",
              ")"
            ],
            "lineageTag": "a7bdcc15-4f46-4366-ac9d-0be73c1e7925"
          },
          {
            "name": "Cost per hole change 18",
            "expression": "DIVIDE(([GCM cost per hole - 18 holes 2023] - [GCM cost per hole - 18 holes 2022]), [GCM cost per hole - 18 holes 2022],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "4e0e791a-8770-4b19-b03a-04ba0cd0c32f"
          },
          {
            "name": "GCM cost per hole - multiple holes 2023",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] > 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2023",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] > 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2023",
              "    ),",
              "    0",
              ")"
            ],
            "lineageTag": "6f101a1e-fc26-4017-8a71-b970832b8c0b"
          },
          {
            "name": "Cost per hole change multiple",
            "expression": "DIVIDE(([GCM cost per hole - multiple holes 2023] - [GCM cost per hole - multiple holes 2022]), [GCM cost per hole - multiple holes 2022],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "da108dfa-fa2e-4fa0-8df6-0ee89f010e60"
          },
          {
            "name": "Full membership - refunadable equity percentages",
            "expression": "SUM('smartsheet - Region'[Refundable Equity]) / SUM('smartsheet - Region'[Full membership - joining fees])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "4ce49c98-0f2a-43d8-8fcc-3cb76fdeb8a5"
          },
          {
            "name": "F&B departmental subsidy to combined F&B sales",
            "expression": "DIVIDE(ABS(SUM('smartsheet - Region'[F&B departmental subsidy])), (SUM('smartsheet - Region'[Food Revenue]) + SUM('smartsheet - Region'[Beverage Revenue])), 0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "d8350309-6f19-4787-81fc-5ac2a0fcae0e"
          },
          {
            "name": "F&B departmental subsidy: Total dues revenue",
            "expression": "DIVIDE(ABS(SUM('smartsheet - Region'[F&B departmental subsidy])), SUM('smartsheet - Region'[Dues Revenue]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "90606d85-9339-416f-ac46-d2d53d7fd039"
          },
          {
            "name": "F&B departmental subsidy: FME",
            "expression": "DIVIDE(ABS(SUM('smartsheet - Region'[F&B departmental subsidy])), SUM('smartsheet - Region'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ef592826-a774-4dee-9ee6-a6d3f331793d"
          },
          {
            "name": "Mandatory Membership %",
            "expression": [
              "",
              "VAR TotalCount = COUNTROWS('smartsheet - Region')",
              "VAR YesCount = CALCULATE(COUNTROWS('smartsheet - Region'), 'smartsheet - Region'[Mandatory Membership] = \"yes\")",
              "RETURN",
              "DIVIDE(YesCount, TotalCount, 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "e21dc256-15df-4bfb-8cb9-1a55f95a490b"
          },
          {
            "name": "Full member equivalent (FME) Calc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR TotalCount = COUNTROWS('smartsheet - Region')",
              "VAR FME = CALCULATE(SUM('smartsheet - Region'[Full Member Equivalents (FME)]))",
              "RETURN",
              "DIVIDE(FME, TotalCount, 0)"
            ],
            "lineageTag": "9a515e2b-ce00-4b72-9fcd-9c73a01fea1e"
          },
          {
            "name": "Operating Assessment %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('smartsheet - Region'[Operating Assessment]),",
              "        'smartsheet - Region'[Operating Assessment] = \"Yes\"",
              "    ),",
              "    COUNT('smartsheet - Region'[Operating Assessment])",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "abb8cd68-fb5d-445d-b9e7-b08ef8ea1d7d"
          },
          {
            "name": "Increase in Menu %",
            "expression": [
              "",
              "VAR TotalCount = COUNTROWS('smartsheet - Region')",
              "VAR YesCount = CALCULATE(COUNTROWS('smartsheet - Region'), 'smartsheet - Region'[Increase in Menu Prices] = \"yes\")",
              "RETURN",
              "DIVIDE(YesCount, TotalCount, 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "e5603698-019e-4dba-8bb7-ab85aa519d55"
          },
          {
            "name": "Increase in Beverage %",
            "expression": [
              "",
              "VAR TotalCount = COUNTROWS('smartsheet - Region')",
              "VAR YesCount = CALCULATE(COUNTROWS('smartsheet - Region'), 'smartsheet - Region'[Increase in Beverage Prices] = \"yes\")",
              "RETURN",
              "DIVIDE(YesCount, TotalCount, 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "999e8db1-e694-4bf2-97e5-2ad1645a7805"
          },
          {
            "name": "Clubs with minimum %",
            "expression": [
              "",
              "VAR TotalCount = COUNTROWS('smartsheet - Region')",
              "VAR YesCount = CALCULATE(COUNTROWS('smartsheet - Region'), 'smartsheet - Region'[Food and Beverage Minimum] = \"yes\")",
              "RETURN",
              "DIVIDE(YesCount, TotalCount, 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "430e0e6b-cbf1-4ddd-aa80-64b15599f409"
          },
          {
            "name": "Clubs with mandatroy %",
            "expression": [
              "",
              "VAR TotalCount = COUNTROWS('smartsheet - Region')",
              "VAR YesCount = CALCULATE(COUNTROWS('smartsheet - Region'), 'smartsheet - Region'[Mandatory Service Charge] = \"yes\")",
              "RETURN",
              "DIVIDE(YesCount, TotalCount, 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "d9902698-c1be-4282-ad60-0d3c7d39ea31"
          },
          {
            "name": "Joining Fees FY23",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE('smartsheet - Region'[Tot Equity]),",
              "    YEAR('smartsheet - Region'[Year end]) = 2023,",
              "    VALUES('smartsheet - Region'[Classification])",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "22bb1bc1-32d1-4a45-839b-d6d40dff64a1"
          },
          {
            "name": "Joining Fees FY22",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE('smartsheet - Region'[Tot Equity]),",
              "    YEAR('smartsheet - Region'[Year end]) = 2022,",
              "    VALUES('smartsheet - Region'[Classification])",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7d57d2e5-f40c-496c-bcd7-2d975bde3ba3"
          },
          {
            "name": "Joining Fees Change",
            "expression": "[Joining Fees FY23] - [Joining Fees FY22]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "33c64a9a-b39f-4c79-92e2-0cd620f4a7af"
          },
          {
            "name": "Joining Fees % Change",
            "expression": "DIVIDE(([Joining Fees FY23] - [Joining Fees FY22]), [Joining Fees FY22],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "71d4b483-f8f8-414c-beda-14bc5de1ba0c"
          },
          {
            "name": "Average surplus",
            "expression": "AVERAGE('smartsheet - Region'[Total Rev]) - AVERAGE('smartsheet - Region'[Total Exp])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e80ab93a-2872-4671-a596-801b73be29ca"
          },
          {
            "name": "Average surplus per FME",
            "expression": "[Total Revenue per FME] - [Total Expenses per FME]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ef6d0392-db34-4c99-a6af-764427cc7708"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "54d47691-f1ab-47d6-a434-e932a7d395fd"
          },
          {
            "name": "% of clubs utilizing foreign labor",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNT('smartsheet - Region'[Other Capital]),",
              "        'smartsheet - Region'[Use of Organized Foreign Labor] = \"Yes\"",
              "    ),",
              "    COUNT('smartsheet - Region'[Other Capital])",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "901b1fd9-9a65-44a9-8376-5f1291a7b34d"
          },
          {
            "name": "GCM cost per hole - multiple holes 2022",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] > 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2022",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] > 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2022",
              "    ),",
              "    0",
              ")"
            ],
            "lineageTag": "6d90129c-3250-4e9d-945b-15b9ad1ebb5c"
          },
          {
            "name": "GCM salaries and wages - 18 holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Salaries and wages]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "befb4a9b-426c-4645-b6d7-3b3dabb7a57f"
          },
          {
            "name": "GCM Repairs & Maintainence - 18 holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Repairs & mtce (includes tree trimming, lake]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "dc381ff8-393a-41e3-b3f6-c4618bca0745"
          },
          {
            "name": "GCM PTEB - 18 holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Payroll taxes and benefits]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "029374c6-652f-4c7b-a315-9a0e895ede0d"
          },
          {
            "name": "GCM Equipment - 18 holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Leased equipment expense]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d7a6f8be-c2d9-4cc6-a90c-4f9d72bbbb92"
          },
          {
            "name": "GCM Course Supplies - 18 holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Course supplies and contracts (includes gaso]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "87b1a546-1ca1-4b5d-a3e9-2b2a62750ede"
          },
          {
            "name": "GCM All Other Expenses - 18 holes",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  All other expenses (including utilities)]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "b702f6e9-dc62-428b-be1d-d873df5220b8"
          },
          {
            "name": "GCM salaries and wages - 18 holes %",
            "expression": "DIVIDE([GCM salaries and wages - 18 holes], [GCM cost per hole - 18 holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "bafe7c7c-74a8-4351-b533-136653af6c54"
          },
          {
            "name": "GCM PTEB - 18 holes %",
            "expression": "DIVIDE([GCM PTEB - 18 holes], [GCM cost per hole - 18 holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "0245c13d-ffd4-4bf4-ad39-17adc627ea45"
          },
          {
            "name": "GCM Course Supplies - 18 holes %",
            "expression": "DIVIDE([GCM Course Supplies - 18 holes], [GCM cost per hole - 18 holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "89397c42-9300-484d-8b84-00b935de88d6"
          },
          {
            "name": "GCM Repairs & Maintainence - 18 holes %",
            "expression": "DIVIDE([GCM Repairs & Maintainence - 18 holes], [GCM cost per hole - 18 holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "281a85e5-b08e-4c6e-9a6a-96427dd97059"
          },
          {
            "name": "GCM Equipment - 18 holes %",
            "expression": "DIVIDE([GCM Equipment - 18 holes], [GCM cost per hole - 18 holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "5caaa835-fa00-4fd2-a4b4-e07f96e2655a"
          },
          {
            "name": "GCM All Other Expenses - 18 holes %",
            "expression": "DIVIDE([GCM All Other Expenses - 18 holes], [GCM cost per hole - 18 holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "49fd1427-4b9b-4372-a8aa-be238f74f0cb"
          },
          {
            "name": "GCM salaries and wages - Multiple",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Salaries and wages]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "520aa1bb-d8a0-49a5-9e2e-bd9b1487118f"
          },
          {
            "name": "GCM PTEB - Multiple",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Payroll taxes and benefits]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "5a6ab0aa-10da-44cf-a2f3-349333e4d579"
          },
          {
            "name": "GCM Course Supplies - Multiple",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Course supplies and contracts (includes gaso]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a8c4bad4-20bd-41d7-8658-495637e056fe"
          },
          {
            "name": "GCM Repairs & Maintainence - Multiple",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Repairs & mtce (includes tree trimming, lake]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "dc3ad39f-0305-4352-84cf-89b6084fc532"
          },
          {
            "name": "GCM Equipment - Multiple",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Leased equipment expense]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2de68b27-2a32-4e2f-81e6-78724c8bb975"
          },
          {
            "name": "GCM All Other Expenses - Multiple",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  All other expenses (including utilities)]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1e90619d-3c60-41e0-8a8d-370f0290a959"
          },
          {
            "name": "GCM Course Supplies - Multiple %",
            "expression": "DIVIDE([GCM Course Supplies - Multiple], [GCM Total - multiple holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "fa7474d7-e45c-4e34-89b4-829d31f4a8a7"
          },
          {
            "name": "GCM salaries and wages - Multiple %",
            "expression": "DIVIDE([GCM salaries and wages - Multiple], [GCM Total - multiple holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "d8b5b937-c9b1-4233-acb4-6ddee4f38eb1"
          },
          {
            "name": "GCM PTEB - Multiple %",
            "expression": "DIVIDE([GCM PTEB - Multiple], [GCM Total - multiple holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "478ceae1-b6c5-48a6-8c1e-502c8f465dbe"
          },
          {
            "name": "GCM Repairs & Maintainence - Multiple %",
            "expression": "DIVIDE([GCM Repairs & Maintainence - Multiple], [GCM Total - multiple holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "4eb0cb24-f708-4f89-ac4d-31f3abb2cc38"
          },
          {
            "name": "GCM Equipment - Multiple %",
            "expression": "DIVIDE([GCM Equipment - Multiple], [GCM Total - multiple holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "5282748c-2518-467e-a118-1f72746a5ed3"
          },
          {
            "name": "GCM All Other Expenses - Multiple %",
            "expression": "DIVIDE([GCM All Other Expenses - Multiple], [GCM Total - multiple holes],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "b354234a-f389-4c42-a0f8-b74e966a738a"
          },
          {
            "name": "Cost of Pro Shop Sales %",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Cost of Sales - Pro shop]), SUM('smartsheet - Region'[Pro Shop Sales]),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "8c55f4fd-c150-4fef-87b6-af1722420eb6"
          },
          {
            "name": "Average menu price increase",
            "expression": [
              "",
              "    CALCULATE(",
              "        AVERAGE('smartsheet - Region'[Av % inc Menu Price]),",
              "        'smartsheet - Region'[Increase in Menu Prices] = \"Yes\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "6d58aea3-bfe5-41ef-b3bd-79199ea35d68"
          },
          {
            "name": "Percentage of covers that are banquet or function",
            "expression": "DIVIDE(AVERAGE('smartsheet - Region'[#  function / banquet covers]), AVERAGE('smartsheet - Region'[Total covers]),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "f69f9bc6-2f18-483b-ab1b-80c56ff12744"
          },
          {
            "name": "Salaries and wages, net of gratuities (%)",
            "expression": "DIVIDE(SUM('smartsheet - Region'[F&B - Salaries and wages expense (EXC credit for M]), SUM('smartsheet - Region'[Food and beverage (F&B) revenues]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4b9cd025-c3cc-4014-96dd-3a20956e76f7"
          },
          {
            "name": "PTEB (%)",
            "expression": "DIVIDE(SUM('smartsheet - Region'[F&B - Payroll taxes and benefits]), SUM('smartsheet - Region'[Food and beverage (F&B) revenues]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e9096d2e-229b-4d9c-94dd-9d965fdc5be3"
          },
          {
            "name": "F&B all other expenses (%)",
            "expression": "DIVIDE(SUM('smartsheet - Region'[F&B All other expenses]), SUM('smartsheet - Region'[Food and beverage (F&B) revenues]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "3a3787d2-91bf-4e16-b953-c7ed8ed1ec57"
          },
          {
            "name": "F&B total expenses (%)",
            "expression": "DIVIDE(SUM('smartsheet - Region'[F&B Total Expenses]), SUM('smartsheet - Region'[Food and beverage (F&B) revenues]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "44bfad1a-9d06-446b-bbfb-41794f1f70bf"
          },
          {
            "name": "Departmental (subsidy)",
            "expression": "ABS([F&B Gross Profit %] - [F&B total expenses (%)])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "381785bd-3538-4124-87da-11c2fc884d87"
          },
          {
            "name": "Average drink price increase",
            "expression": [
              "",
              "    CALCULATE(",
              "        AVERAGE('smartsheet - Region'[Av % inc Bev Price]),",
              "        'smartsheet - Florida'[Increase in Beverage Prices] = \"Yes\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "97305121-4740-4a89-b544-ffe1d9e20f18"
          },
          {
            "name": "GCM cost per hole - multiple",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "lineageTag": "f44f93d7-63c3-47f8-9208-b0201ce6a4ba"
          },
          {
            "name": "GCM Payroll - 18 holes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Salaries and wages]) + SUM('smartsheet - Region'[GCM  Payroll taxes and benefits]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18",
              "    ),",
              "    0",
              ")"
            ],
            "lineageTag": "89257d34-5413-4fc7-8438-ebe2ae2604ca"
          },
          {
            "name": "GCM Payroll - multiple",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM  Salaries and wages]) + SUM('smartsheet - Region'[GCM  Payroll taxes and benefits]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] > 18",
              "    ),",
              "    0",
              ")"
            ],
            "lineageTag": "6919ca16-0f49-4362-bc40-d218910b23ff"
          },
          {
            "name": "Refundable equity percentage",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Refundable Equity]), SUM('smartsheet - Region'[Total equity]),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "489d1093-e035-46a6-87cd-7a98ae5cae9f"
          },
          {
            "name": "Full membership - avg total annual cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE('smartsheet - Region'[Amount of F&B Minimum]) + AVERAGE('smartsheet - Region'[Amount of Monthly Service Charge]) + AVERAGE('smartsheet - Region'[Capital Assessment Amount]) + AVERAGE('smartsheet - Region'[Amount of general capital assessment]) + AVERAGE('smartsheet - Region'[Dues Rate - Audit Year]) + AVERAGE('smartsheet - Region'[Operating Assessment Amount])",
            "lineageTag": "55df7565-aa51-43a2-a683-5e9225205a69"
          },
          {
            "name": "AverageF&BMinimum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE('smartsheet - Region'[Amount of F&B Minimum]),",
              "    'smartsheet - Region'[Food and Beverage Minimum] = \"yes\"",
              ")"
            ],
            "lineageTag": "ce8b1cf9-fa38-4a53-b69e-051c989c99b2"
          },
          {
            "name": "GCM cost per hole - 18 holes 2022",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] = 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2022",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2022",
              "    ),",
              "    0",
              ")"
            ],
            "lineageTag": "3be23d78-3e03-45a8-af76-d78e2d5bdf1c"
          },
          {
            "name": "GCM cost per hole - 18 holes 2023",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[GCM Total]),",
              "        'smartsheet - Region'[# of holes] = 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2023",
              "    ),",
              "    CALCULATE(",
              "        SUM('smartsheet - Region'[# of holes]),",
              "        'smartsheet - Region'[# of holes] = 18,",
              "        YEAR('smartsheet - Region'[Year end]) = 2023",
              "    ),",
              "    0",
              ")"
            ],
            "lineageTag": "53e13f99-8e12-4495-a67d-7848ad48fd26"
          },
          {
            "name": "Cost of sales - pro shop %",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Cost of Sales - Pro shop]), SUM('smartsheet - Region'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d834997c-1634-45ac-9757-6482dc838abe"
          },
          {
            "name": "Cost of Sales - pro shop per FME",
            "expression": "DIVIDE(SUM('smartsheet - Region'[Cost of Sales - Pro shop]), SUM('smartsheet - Region'[Full Member Equivalents (FME)]), 0)",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "8375d67a-0206-4ca8-9dcb-63a43a034b1e"
          }
        ],
        "partitions": [
          {
            "name": "smartsheet - Region",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\E082336\\offboarding\\chris-eisen\\apps\\clubs\\Dta\\Smartsheet\\Smartsheet Upload PowerBI.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Promoted Headers\",{{\"Total Total Liabilities\", \"Total Liabilities\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Year end\", type date}, {\"Full Member Equivalents (FME)\", type number}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Clubs With Positive Working Capital\", each if [Current Assets] > [Current Liabilities] then 1 else 0),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"Club name\", type text}, {\"Classification\", type text}, {\"Type\", type text}, {\"Mandatory Membership\", type text}, {\"General Capital Assessment\", type text}, {\"Operating Assessment\", type text}, {\"Other Capital\", type text}, {\"Major renovation\", type text}, {\"Third Party Debt\", type text}, {\"Use of Organized Foreign Labor\", type text}, {\"Increase in Health Insurance\", type text}, {\"Food and Beverage Minimum\", type text}, {\"Automatic F&B Gratuity\", type text}, {\"Mandatory Service Charge\", type text}, {\"Compensation Method for F&B Staff\", type text}, {\"Increase in Menu Prices\", type text}, {\"Increase in Beverage Prices\", type text}, {\"Type of Renovation  1\", type text}, {\"Type of Renovation  2\", type text}, {\"Type of Renovation  3\", type text}, {\"Year End\", type text}, {\"Type of Renovation - 1\", type text}, {\"Type of Renovation - 2\", type text}, {\"Type of Renovation - 3\", type text}, {\"Clubs With Positive Working Capital\", type text}, {\"Refundable Equity\", type number}, {\"Non-refundable equity\", type number}, {\"Total equity\", type number}, {\"Dues Rate - Current Year\", type number}, {\"Dues Rate - Audit Year\", type number}, {\"Capital Assessment Amount\", type number}, {\"Operating Assessment Amount\", type number}, {\"Amount of general capital assessment\", type number}, {\"Amount of Budgeted Major Capital Project\", type number}, {\"Amount of Budgeted Other Capital Projects\", type number}, {\"Ending PPE, net\", type number}, {\"Capital Expenditures (PP&E)\", type number}, {\"Depreciation Expense\", type number}, {\"Total Third Party Debt\", type number}, {\"Current Assets\", type number}, {\"Current Liabilities\", type number}, {\"Total Liabilities\", type number}, {\"Ending Net Assets\", type number}, {\"Golf Revenue\", type number}, {\"Tennis Revenue\", type number}, {\"Pro Shop Sales\", type number}, {\"Other Sports Revenue\", type number}, {\"Dues Revenue\", type number}, {\"Operating Assessments\", type number}, {\"Non-Owner Initiation fees\", type number}, {\"Food Revenue\", type number}, {\"Beverage Revenue\", type number}, {\"All Other F&B Revenue\", type number}, {\"Payroll and PTEB Expense\", type number}, {\"Cost of sales - F&B\", type number}, {\"Cost of Sales - Pro shop\", type number}, {\"Operating Expenses\", type number}, {\"Property Taxes\", type number}, {\"Insurance Expense\", type number}, {\"Total employees in season\", type number}, {\"# Foreign Staff hired in yr\", type number}, {\"Total Foreign Labor Costs\", type number}, {\"% inc. in Health Insurance\", type number}, {\"Amount of F&B Minimum\", type number}, {\"% amt of F&B gratuity\", type number}, {\"Amount of Monthly Service Charge\", type number}, {\"# full service kitchens\", type number}, {\"# covers (include function / banquet)\", type number}, {\"#  function / banquet covers\", type number}, {\"Food sales (exc Mins)\", type number}, {\"Cost of food sold\", type number}, {\"Beverage sales\", type number}, {\"Cost of beverage sales\", type number}, {\"F&B - Salaries and wages expense (EXC credit for M\", type number}, {\"F&B - Less credit = 20% of F&B sales (only applies\", type number}, {\"F&B - Payroll taxes and benefits\", type number}, {\"F&B - Employees' meals\", type number}, {\"F&B - Laundry\", type number}, {\"F&B - Linen, china, glass, silver\", type number}, {\"F&B - Other expenses (excluding entertainment, val\", type number}, {\"Av % inc Menu Price\", type number}, {\"Av % inc Bev Price\", type number}, {\"# of holes\", type number}, {\"Maintained golf acreage\", type number}, {\"Rounds per year\", type number}, {\"GCM  Salaries and wages\", type number}, {\"GCM  Payroll taxes and benefits\", type number}, {\"GCM  Course supplies and contracts (includes gaso\", type number}, {\"GCM  Repairs & mtce (includes tree trimming, lake\", type number}, {\"GCM  Leased equipment expense\", type number}, {\"GCM  All other expenses (including utilities)\", type number}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Changed Type1\",{{\"Clubs With Positive Working Capital\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type2\",{{\"Year End\", \"Fiscal_Year\"}}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Total Membership\", Int64.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type3\",\"North and Central\",\"North And Central\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Appended Query\" = Table.Combine({#\"Replaced Value\", #\"smartsheet - Florida\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Appended Query\", {\"Classification\"}, Order, {\"Classification\"}, \"Order\", JoinKind.LeftOuter),",
                "    #\"Expanded Order\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Order\", {\"Order\"}, {\"Order.Order\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Expanded Order\",\"Florida\",\"a. Florida\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Southeast without Boca\",\"b. Southeast without Boca\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"Boca Raton Area\",\"c. Boca Raton Area\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"Southwest without CIRAs\",\"d. Southwest without CIRAs\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"Southwest CIRAs\",\"e. Southwest CIRAs\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"North And Central\",\"f. North And Central\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"Yacht and Beach Clubs\",\"g. Yacht and Beach Clubs\",Replacer.ReplaceText,{\"Classification\"})",
                "in",
                "    #\"Replaced Value7\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_610958bb-1789-43bf-a11c-8faba4da955e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "600cfb10-7fa7-44e7-92d2-006a3b985581",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "01924a52-92df-4340-8231-c8ba090c341a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3025b920-a50e-4b92-a617-9e302590a94d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e98b0dde-a6ee-4fd3-9b99-268339155200",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "10dfad8d-a188-46dc-80e1-42de534cad14",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "65aae2ad-7abf-48a6-8165-7b9618d68daf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b1cc3c62-bada-4b03-83e8-b3f0f19f5376",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a8ed0d22-7f1c-4b59-820f-639cf84cdc85",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0562d09f-01da-443f-8359-a4c8685dc7d8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1a5fd651-5944-482e-bbf7-c35730e95734",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5247a430-53d5-4e73-8b7d-38eba8eb4f0d",
                "ordinal": 3
              }
            ],
            "lineageTag": "8f248c01-9e04-4cbd-80a0-e676f41ad00a"
          }
        ],
        "isHidden": true,
        "lineageTag": "e85a9ab1-4e41-40cb-954d-5509c6d5cbd4",
        "partitions": [
          {
            "name": "LocalDateTable_610958bb-1789-43bf-a11c-8faba4da955e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('smartsheet - Region'[Year end])), 1, 1), Date(Year(MAX('smartsheet - Region'[Year end])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "smartsheet - Florida",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Club name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efa5eef0-b6a8-47d9-9c8d-b59c9e420787",
            "sourceColumn": "Club name",
            "summarizeBy": "none"
          },
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bf0fc1a-6f10-4ef3-9bed-f26b4c117990",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Zip Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36e20fba-7b80-4049-b3f4-c710627ecd02",
            "sourceColumn": "Zip Code",
            "summarizeBy": "none"
          },
          {
            "name": "Year end",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2867759e-1eee-4432-aebc-425d07e3b876",
            "sourceColumn": "Year end",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a8244fc7-8c0f-4d11-9005-3d05c57ca1d1"
                },
                "isDefault": true,
                "relationship": "4a00b6aa-83a1-49e9-a4fb-56551f552f03"
              }
            ]
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a85abefa-0160-4a6e-a147-a2ba38ae287f",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Mandatory Membership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c6530c5-0b15-43d5-af2d-4294686d3bb5",
            "sourceColumn": "Mandatory Membership",
            "summarizeBy": "none"
          },
          {
            "name": "Unnamed: 6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc955b25-5cd2-4ebc-b45a-57929a34fe03",
            "sourceColumn": "Unnamed: 6",
            "summarizeBy": "none"
          },
          {
            "name": "Total Membership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d2a28463-9645-4feb-a7ad-cd7589cb5c94",
            "sourceColumn": "Total Membership",
            "summarizeBy": "sum"
          },
          {
            "name": "Full Member Equivalents (FME)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4f002911-b0a3-4469-a7dc-4edf7de22cf6",
            "sourceColumn": "Full Member Equivalents (FME)",
            "summarizeBy": "sum"
          },
          {
            "name": "Refundable Equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bb7a9416-c769-4e6a-8de9-e14f16a2f990",
            "sourceColumn": "Refundable Equity",
            "summarizeBy": "sum"
          },
          {
            "name": "Non-refundable equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0db0e122-1f63-43e7-87ce-ba85dfb14015",
            "sourceColumn": "Non-refundable equity",
            "summarizeBy": "sum"
          },
          {
            "name": "Total equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c69338f2-9345-486f-b63b-4d31b39f4881",
            "sourceColumn": "Total equity",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Rate - Current Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "552333af-be51-45a3-98c0-e14c198edd2a",
            "sourceColumn": "Dues Rate - Current Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Rate - Audit Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fd3811ab-1736-4b8d-a455-15d5bf66f711",
            "sourceColumn": "Dues Rate - Audit Year",
            "summarizeBy": "sum"
          },
          {
            "name": "General Capital Assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a419b23-12f5-404b-b818-31db39514005",
            "sourceColumn": "General Capital Assessment",
            "summarizeBy": "none"
          },
          {
            "name": "Capital Assessment Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "94cb5882-e600-410d-a63c-c92f70682845",
            "sourceColumn": "Capital Assessment Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5265bb7f-b403-4047-9bfc-5e5232da7bc0",
            "sourceColumn": "Operating Assessment",
            "summarizeBy": "none"
          },
          {
            "name": "Operating Assessment Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "681892b2-82c7-4a60-8f8a-9359aae8c7cd",
            "sourceColumn": "Operating Assessment Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Other Capital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2a2c154-3f3a-4997-8994-904da3bd5942",
            "sourceColumn": "Other Capital",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of general capital assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cc6e8dc6-ba73-4171-8b05-38b036969181",
            "sourceColumn": "Amount of general capital assessment",
            "summarizeBy": "sum"
          },
          {
            "name": "Major renovation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2fdeba9-6ee2-447e-9db9-0f46be3139d7",
            "sourceColumn": "Major renovation",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation - 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9103d5a8-6cab-4063-9bd5-0c6d5257aee9",
            "sourceColumn": "Type of Renovation - 1",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation - 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6aef3b20-0732-41b1-bae3-9cdf0d4197b7",
            "sourceColumn": "Type of Renovation - 2",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation - 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cf1db33-07ad-4a82-a0c8-52554f85ee65",
            "sourceColumn": "Type of Renovation - 3",
            "summarizeBy": "none"
          },
          {
            "name": "Budgeted Major Capital Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70d9ea0c-9a59-4bab-a4cd-54526ff3675f",
            "sourceColumn": "Budgeted Major Capital Project",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of Budgeted Major Capital Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "098d78ad-9b5d-4999-bb55-d29c437f31cb",
            "sourceColumn": "Amount of Budgeted Major Capital Project",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount of Budgeted Other Capital Projects",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "03440067-e2f5-4e19-9d48-397d1382d9ff",
            "sourceColumn": "Amount of Budgeted Other Capital Projects",
            "summarizeBy": "sum"
          },
          {
            "name": "Ending PPE, net",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "51572b52-50a6-4f67-acb9-b24b71d456de",
            "sourceColumn": "Ending PPE, net",
            "summarizeBy": "sum"
          },
          {
            "name": "Capital Expenditures (PP&E)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "287d6644-4d80-40b6-a32e-8a7d5dd16e43",
            "sourceColumn": "Capital Expenditures (PP&E)",
            "summarizeBy": "sum"
          },
          {
            "name": "Depreciation Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e75be8e1-a640-4718-8828-5ebf3e416210",
            "sourceColumn": "Depreciation Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Third Party Debt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7caf11f-d07c-4b5b-adb4-59f7dc3b1ad4",
            "sourceColumn": "Third Party Debt",
            "summarizeBy": "none"
          },
          {
            "name": "Total Third Party Debt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fadfae92-bdbe-48fe-8b81-1e08ec2ecf78",
            "sourceColumn": "Total Third Party Debt",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Assets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7bf293cc-6bf2-41ef-beeb-e50acf42535d",
            "sourceColumn": "Current Assets",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Liabilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ff9e38a9-8e7b-4240-8869-6ba320a389b0",
            "sourceColumn": "Current Liabilities",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Liabilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "289f8814-ace4-4dca-9f64-068f5960dcc6",
            "sourceColumn": "Total Liabilities",
            "summarizeBy": "sum"
          },
          {
            "name": "Ending Net Assets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7c8c8097-5d8a-4d25-8c8c-04ff87e0b45c",
            "sourceColumn": "Ending Net Assets",
            "summarizeBy": "sum"
          },
          {
            "name": "Golf Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f85a7170-685d-4399-9736-7798b1a5b077",
            "sourceColumn": "Golf Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Tennis Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8ed548c9-2c86-4ad2-aaa1-ffb9aac5efac",
            "sourceColumn": "Tennis Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Pro Shop Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9937bbf5-1a4a-4100-8f4f-3429108e86bb",
            "sourceColumn": "Pro Shop Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Other Sports Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "89410d9c-fe81-4c25-bd7f-873595efa997",
            "sourceColumn": "Other Sports Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7815478b-5d09-4e6d-9d98-59c53dc14182",
            "sourceColumn": "Dues Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Assessments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4fcefb4b-93e7-4fab-8348-f9afcf7e2a03",
            "sourceColumn": "Operating Assessments",
            "summarizeBy": "sum"
          },
          {
            "name": "Non-Owner Initiation fees",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e6773fdf-35e9-4f8d-9977-5c2b0388a13a",
            "sourceColumn": "Non-Owner Initiation fees",
            "summarizeBy": "sum"
          },
          {
            "name": "Food Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f79c25b0-0f3c-43cc-9723-d51a0ad94365",
            "sourceColumn": "Food Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Beverage Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bcd3d38b-222d-4f88-a2c1-3ac65dde5683",
            "sourceColumn": "Beverage Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "All Other F&B Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c8c1be55-c547-46db-99a5-e0564475d9af",
            "sourceColumn": "All Other F&B Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Payroll and PTEB Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a89cb922-569f-4df5-b266-ffa952bcae4a",
            "sourceColumn": "Payroll and PTEB Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of sales - F&B",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "802245ff-81a8-4b87-9b44-6d5a6442c4f2",
            "sourceColumn": "Cost of sales - F&B",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of Sales - Pro shop",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "06723751-abe7-40f3-aa2b-7092fba676db",
            "sourceColumn": "Cost of Sales - Pro shop",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Expenses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "969c1367-3f99-48a5-99c9-545e0c2518e2",
            "sourceColumn": "Operating Expenses",
            "summarizeBy": "sum"
          },
          {
            "name": "Property Taxes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f859afe8-b638-459a-b321-8915a9d10d8a",
            "sourceColumn": "Property Taxes",
            "summarizeBy": "sum"
          },
          {
            "name": "Insurance Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "33190ef7-73a1-4b34-b084-05349c95a6bf",
            "sourceColumn": "Insurance Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Total employees in season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e5e842c4-d0c5-43b6-bf1a-400699542b9a",
            "sourceColumn": "Total employees in season",
            "summarizeBy": "sum"
          },
          {
            "name": "Use of Organized Foreign Labor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d60c9c1d-75df-4f63-8c79-c286870b555b",
            "sourceColumn": "Use of Organized Foreign Labor",
            "summarizeBy": "none"
          },
          {
            "name": "# Foreign Staff hired in yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9c5a1b15-a5e8-40b1-9762-610a08b1ba42",
            "sourceColumn": "# Foreign Staff hired in yr",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Foreign Labor Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5e4d5ff3-f529-4974-a46f-f58619cee7ce",
            "sourceColumn": "Total Foreign Labor Costs",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Health Insurance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f189018-3f74-4abc-8427-94586e1873e9",
            "sourceColumn": "Increase in Health Insurance",
            "summarizeBy": "none"
          },
          {
            "name": "% inc. in Health Insurance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "64f3f9cd-01e9-4322-accf-af2831d28a14",
            "sourceColumn": "% inc. in Health Insurance",
            "summarizeBy": "sum"
          },
          {
            "name": "Food and Beverage Minimum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35d44a69-fcf6-4db7-a142-1feeddc97cbd",
            "sourceColumn": "Food and Beverage Minimum",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of F&B Minimum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5d7ca809-0120-4a3f-b4fd-bd142496d04a",
            "sourceColumn": "Amount of F&B Minimum",
            "summarizeBy": "sum"
          },
          {
            "name": "Automatic F&B Gratuity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae57fde2-4349-424f-abb1-8fc4beb2cd49",
            "sourceColumn": "Automatic F&B Gratuity",
            "summarizeBy": "none"
          },
          {
            "name": "% amt of F&B gratuity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8c83b619-d7b7-4ff0-9705-0bdd5bcd9b57",
            "sourceColumn": "% amt of F&B gratuity",
            "summarizeBy": "sum"
          },
          {
            "name": "Mandatory Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc816516-0b30-4efa-b77b-cd81e81101d6",
            "sourceColumn": "Mandatory Service Charge",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of Monthly Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cd5fdd4c-bceb-4bb5-9f70-413a21d06be1",
            "sourceColumn": "Amount of Monthly Service Charge",
            "summarizeBy": "sum"
          },
          {
            "name": "# full service kitchens",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "645aad7c-a40f-4d78-90a4-718ed437494d",
            "sourceColumn": "# full service kitchens",
            "summarizeBy": "sum"
          },
          {
            "name": "# covers (include function / banquet)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "28cedf72-1fdd-4849-9e08-9bdd8428f63a",
            "sourceColumn": "# covers (include function / banquet)",
            "summarizeBy": "sum"
          },
          {
            "name": "#  function / banquet covers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "21bdeebf-e49d-4a62-b849-021b556ea01b",
            "sourceColumn": "#  function / banquet covers",
            "summarizeBy": "sum"
          },
          {
            "name": "Compensation Method for F&B Staff",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e06bf6a-da72-4f73-9aaa-e69b72c1e38e",
            "sourceColumn": "Compensation Method for F&B Staff",
            "summarizeBy": "none"
          },
          {
            "name": "Food sales (exc Mins)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4b11669a-f567-4d73-9817-624fa819af86",
            "sourceColumn": "Food sales (exc Mins)",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of food sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b5aa8aa7-4163-408f-b2ae-357488808c14",
            "sourceColumn": "Cost of food sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Beverage sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5e676123-23c5-4330-95af-b7c57dd4ec68",
            "sourceColumn": "Beverage sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of beverage sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "647185dd-2ac3-4aa7-83f0-2729bfc97012",
            "sourceColumn": "Cost of beverage sales",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Salaries and wages expense (EXC credit for M",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "57493490-c647-40c7-9640-3ec355b7cce2",
            "sourceColumn": "F&B - Salaries and wages expense (EXC credit for M",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Less credit = 20% of F&B sales (only applies",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7630ebe3-f745-4c2c-bbfa-2d21e275c6b3",
            "sourceColumn": "F&B - Less credit = 20% of F&B sales (only applies",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Payroll taxes and benefits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3fa4bf5e-f8d2-4623-8f15-0183570a2d4b",
            "sourceColumn": "F&B - Payroll taxes and benefits",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Employees' meals",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67d1c5ef-fafb-4ad3-bff3-a880d05f9e95",
            "sourceColumn": "F&B - Employees' meals",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Laundry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "555ae0ce-e48e-4796-b05c-22cbf875df26",
            "sourceColumn": "F&B - Laundry",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Linen, china, glass, silver",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6cf487ed-6da0-4774-bf93-bed705047d89",
            "sourceColumn": "F&B - Linen, china, glass, silver",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Other expenses (excluding entertainment, val",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9069725e-d12b-4c4f-9d73-9660962d982f",
            "sourceColumn": "F&B - Other expenses (excluding entertainment, val",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Menu Prices",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ff013c6-6a0c-4058-a018-f410e0546d57",
            "sourceColumn": "Increase in Menu Prices",
            "summarizeBy": "none"
          },
          {
            "name": "Av % inc Menu Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fd640ad6-0e36-4c7f-a13c-44d71260da42",
            "sourceColumn": "Av % inc Menu Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Beverage Prices",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88134b3f-0b4c-4f49-91c3-192885db0c65",
            "sourceColumn": "Increase in Beverage Prices",
            "summarizeBy": "none"
          },
          {
            "name": "Av % inc Bev Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "884556e1-2f66-4837-8a9a-b3f341ea3d94",
            "sourceColumn": "Av % inc Bev Price",
            "summarizeBy": "sum"
          },
          {
            "name": "# of holes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "744d6f3d-514c-4cef-af2b-c29d6db68005",
            "sourceColumn": "# of holes",
            "summarizeBy": "sum"
          },
          {
            "name": "Maintained golf acreage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9345c442-962f-4831-b62f-d24960031a2b",
            "sourceColumn": "Maintained golf acreage",
            "summarizeBy": "sum"
          },
          {
            "name": "Rounds per year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "344d7727-3dac-4889-9743-e9a43150c113",
            "sourceColumn": "Rounds per year",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  Salaries and wages",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8a8317c5-7de7-4f74-bb8d-4df2595c3c02",
            "sourceColumn": "GCM  Salaries and wages",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  Payroll taxes and benefits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bc470a5f-d326-4c87-be34-6cc1f3a51c3f",
            "sourceColumn": "GCM  Payroll taxes and benefits",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  Course supplies and contracts (includes gaso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ec384180-0dd9-429c-b37a-2d232751dc4b",
            "sourceColumn": "GCM  Course supplies and contracts (includes gaso",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  Repairs & mtce (includes tree trimming, lake",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8196f134-dfb8-441c-b510-122cf5732ff3",
            "sourceColumn": "GCM  Repairs & mtce (includes tree trimming, lake",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  Leased equipment expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ff735306-9775-444f-98db-b8bbf987a493",
            "sourceColumn": "GCM  Leased equipment expense",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM  All other expenses (including utilities)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d400d39f-b5f0-4606-94ab-4bf919901202",
            "sourceColumn": "GCM  All other expenses (including utilities)",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal_Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7bcd01c-ff57-41bb-a215-8104815e1e16",
            "sourceColumn": "Fiscal_Year",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation  1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7ad45cb-bb53-4b2b-8c7d-ec3447ea301e",
            "sourceColumn": "Type of Renovation  1",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation  2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "155170c0-f1f9-44ac-bea7-ca6e1e29dcc4",
            "sourceColumn": "Type of Renovation  2",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation  3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61da421a-dcc1-4efa-92f5-bcbab4caeaf7",
            "sourceColumn": "Type of Renovation  3",
            "summarizeBy": "none"
          },
          {
            "name": "Clubs With Positive Working Capital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3d71f37f-b320-4697-a29f-0d0bc56052e3",
            "sourceColumn": "Clubs With Positive Working Capital",
            "summarizeBy": "sum"
          },
          {
            "name": "Type of Renovation  4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "042756f7-64af-45de-9294-5be684d03859",
            "sourceColumn": "Type of Renovation  4",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ecfe32af-27e6-47db-a8c4-8b029f90e78c",
        "partitions": [
          {
            "name": "smartsheet - Florida",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\E082336\\offboarding\\chris-eisen\\apps\\clubs\\Dta\\Smartsheet\\Smartsheet Upload PowerBI.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Promoted Headers\",{{\"Total Total Liabilities\", \"Total Liabilities\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Year end\", type date}, {\"Full Member Equivalents (FME)\", type number}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Clubs With Positive Working Capital\", each if [Current Assets] > [Current Liabilities] then 1 else 0),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"Club name\", type text}, {\"Classification\", type text}, {\"Type\", type text}, {\"Mandatory Membership\", type text}, {\"General Capital Assessment\", type text}, {\"Operating Assessment\", type text}, {\"Other Capital\", type text}, {\"Major renovation\", type text}, {\"Third Party Debt\", type text}, {\"Use of Organized Foreign Labor\", type text}, {\"Increase in Health Insurance\", type text}, {\"Food and Beverage Minimum\", type text}, {\"Automatic F&B Gratuity\", type text}, {\"Mandatory Service Charge\", type text}, {\"Compensation Method for F&B Staff\", type text}, {\"Increase in Menu Prices\", type text}, {\"Increase in Beverage Prices\", type text}, {\"Type of Renovation  1\", type text}, {\"Type of Renovation  2\", type text}, {\"Type of Renovation  3\", type text}, {\"Year End\", type text}, {\"Type of Renovation - 1\", type text}, {\"Type of Renovation - 2\", type text}, {\"Type of Renovation - 3\", type text}, {\"Clubs With Positive Working Capital\", type text}, {\"Refundable Equity\", type number}, {\"Non-refundable equity\", type number}, {\"Total equity\", type number}, {\"Dues Rate - Current Year\", type number}, {\"Dues Rate - Audit Year\", type number}, {\"Capital Assessment Amount\", type number}, {\"Operating Assessment Amount\", type number}, {\"Amount of general capital assessment\", type number}, {\"Amount of Budgeted Major Capital Project\", type number}, {\"Amount of Budgeted Other Capital Projects\", type number}, {\"Ending PPE, net\", type number}, {\"Capital Expenditures (PP&E)\", type number}, {\"Depreciation Expense\", type number}, {\"Total Third Party Debt\", type number}, {\"Current Assets\", type number}, {\"Current Liabilities\", type number}, {\"Total Liabilities\", type number}, {\"Ending Net Assets\", type number}, {\"Golf Revenue\", type number}, {\"Tennis Revenue\", type number}, {\"Pro Shop Sales\", type number}, {\"Other Sports Revenue\", type number}, {\"Dues Revenue\", type number}, {\"Operating Assessments\", type number}, {\"Non-Owner Initiation fees\", type number}, {\"Food Revenue\", type number}, {\"Beverage Revenue\", type number}, {\"All Other F&B Revenue\", type number}, {\"Payroll and PTEB Expense\", type number}, {\"Cost of sales - F&B\", type number}, {\"Cost of Sales - Pro shop\", type number}, {\"Operating Expenses\", type number}, {\"Property Taxes\", type number}, {\"Insurance Expense\", type number}, {\"Total employees in season\", type number}, {\"# Foreign Staff hired in yr\", type number}, {\"Total Foreign Labor Costs\", type number}, {\"% inc. in Health Insurance\", type number}, {\"Amount of F&B Minimum\", type number}, {\"% amt of F&B gratuity\", type number}, {\"Amount of Monthly Service Charge\", type number}, {\"# full service kitchens\", type number}, {\"# covers (include function / banquet)\", type number}, {\"#  function / banquet covers\", type number}, {\"Food sales (exc Mins)\", type number}, {\"Cost of food sold\", type number}, {\"Beverage sales\", type number}, {\"Cost of beverage sales\", type number}, {\"F&B - Salaries and wages expense (EXC credit for M\", type number}, {\"F&B - Less credit = 20% of F&B sales (only applies\", type number}, {\"F&B - Payroll taxes and benefits\", type number}, {\"F&B - Employees' meals\", type number}, {\"F&B - Laundry\", type number}, {\"F&B - Linen, china, glass, silver\", type number}, {\"F&B - Other expenses (excluding entertainment, val\", type number}, {\"Av % inc Menu Price\", type number}, {\"Av % inc Bev Price\", type number}, {\"# of holes\", type number}, {\"Maintained golf acreage\", type number}, {\"Rounds per year\", type number}, {\"GCM  Salaries and wages\", type number}, {\"GCM  Payroll taxes and benefits\", type number}, {\"GCM  Course supplies and contracts (includes gaso\", type number}, {\"GCM  Repairs & mtce (includes tree trimming, lake\", type number}, {\"GCM  Leased equipment expense\", type number}, {\"GCM  All other expenses (including utilities)\", type number}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Changed Type1\",{{\"Clubs With Positive Working Capital\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type2\",{{\"Year End\", \"Fiscal_Year\"}}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Total Membership\", Int64.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type3\",\"Southwest without CIRAs\",\"Florida\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Boca Raton Area\",\"Florida\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Southeast without Boca\",\"Florida\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"Southwest CIRAs\",\"Florida\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"Yacht and Beach Clubs\",\"Florida\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"North and Central\",\"Florida\",Replacer.ReplaceText,{\"Classification\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"North And Central\",\"Florida\",Replacer.ReplaceText,{\"Classification\"})",
                "in",
                "    #\"Replaced Value6\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a8244fc7-8c0f-4d11-9005-3d05c57ca1d1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ac8cec65-0350-4eb8-be47-72ce1d898410",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "eaf09b23-471e-47ff-bd8d-5bea0891a0d1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3a86b06f-8f71-4465-846b-b0df73cd3174",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b0da6849-3ab9-4233-92de-a3e640623b63",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "879e89f0-c3c4-46e6-b8e6-2be0d48f2296",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "dd7f3a3c-411b-4a1b-86e3-21e4e3b3c424",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8db0f370-a5bd-4049-bb6d-a31b2da8e1ba",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3f2f92ca-6640-4140-95b5-b385742f16fe",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3d047af7-ca58-46fb-825a-89b0d996b407",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1e04863d-b2a3-4235-94a3-437cc3cc1d0c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1328209c-8e90-42ae-9354-6c8514f95fba",
                "ordinal": 3
              }
            ],
            "lineageTag": "10b3d4da-6186-4008-a0a5-fe54b1e4c7c1"
          }
        ],
        "isHidden": true,
        "lineageTag": "e225987a-ed28-41a9-a815-5eb62c184fa0",
        "partitions": [
          {
            "name": "LocalDateTable_a8244fc7-8c0f-4d11-9005-3d05c57ca1d1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('smartsheet - Florida'[Year end])), 1, 1), Date(Year(MAX('smartsheet - Florida'[Year end])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Perc",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d15554eb-469e-4ec0-9d43-a374c05afd4c",
            "sourceColumn": "Field",
            "summarizeBy": "none"
          },
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8026c58a-a292-4062-83cd-2c70dd9e1037",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d76142c2-23ce-4086-85c6-6a184a5f0162",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9c5c9c8c-93da-47a1-86d8-6620eb77c7e0",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Column5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5521763-487b-4a3a-b4a4-28d435cbe975",
            "sourceColumn": "Column5",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "240ed776-9909-45ee-9a5f-ae2e6afea75a",
        "partitions": [
          {
            "name": "Perc",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\E082336\\offboarding\\chris-eisen\\apps\\clubs\\Dta\\Smartsheet\\Clubs - Trend Sheet.xlsx\"), null, true),",
                "    Perc_Sheet = Source{[Item=\"Perc\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Perc_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Value\", type number}, {\"Year\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dol",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6841bbfb-bef8-420e-aae7-dc8f6faaea06",
            "sourceColumn": "Field",
            "summarizeBy": "none"
          },
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "247634e3-e72a-46fb-853a-d1b92cf37249",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0014193a-f84e-4c69-859f-10bec744e8a9",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a8d5303f-1fd1-4483-86aa-6717e9102782",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "fd23effc-2d37-46eb-a818-e373eb439821",
        "measures": [
          {
            "name": "Dues 2023",
            "expression": [
              "AVERAGEX(",
              "    FILTER(",
              "        'Dol',",
              "        'Dol'[Year] = \"2023\"",
              "            && 'Dol'[Field] = \"Dues (full membership)\"",
              "    ),",
              "    'Dol'[Value]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "349a654d-85e6-4b36-bf5b-6f3161bd567a"
          },
          {
            "name": "Dues 2024",
            "expression": [
              "AVERAGEX(",
              "    FILTER(",
              "        'Dol',",
              "        'Dol'[Year] = \"2024\"",
              "            && 'Dol'[Field] = \"Dues (full membership)\"",
              "    ),",
              "    'Dol'[Value]",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a219fa06-a6b7-48ba-832d-a31b44281178"
          },
          {
            "name": "Dues Change",
            "expression": "[Dues 2024] - [Dues 2023]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a3c70753-ede2-47f3-83c2-93f51f0829f3"
          },
          {
            "name": "Dues Change %",
            "expression": "DIVIDE(([Dues 2024] - [Dues 2023]), [Dues 2023], 0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "dc390b9b-dc1f-4a0f-b2bc-47b31ade44e2"
          },
          {
            "name": "Joining fees 2024",
            "expression": [
              "AVERAGEX(",
              "    FILTER(",
              "        'Dol',",
              "        'Dol'[Year] = \"2024\"",
              "            && 'Dol'[Field] = \"Total annual membership cost\"",
              "    ),",
              "    'Dol'[Value]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f9a255ee-8e50-427c-aa2a-723bc6d3a732"
          },
          {
            "name": "Joining fees 2023",
            "expression": [
              "AVERAGEX(",
              "    FILTER(",
              "        'Dol',",
              "        'Dol'[Year] = \"2023\"",
              "            && 'Dol'[Field] = \"Total annual membership cost\"",
              "    ),",
              "    'Dol'[Value]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "41f6f63b-d399-47c2-841e-c09d8faf59d3"
          },
          {
            "name": "Join Fees Change",
            "expression": "[Joining fees 2024] - [Joining fees 2023]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6d3edc8b-f58f-4122-931d-5cbcc4c09193"
          },
          {
            "name": "Join Fees Change %",
            "expression": "DIVIDE(([Joining fees 2024] - [Joining fees 2023]), [Joining fees 2023],0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "ec0c2662-66ff-4f16-b9c3-f888146e8b31"
          }
        ],
        "partitions": [
          {
            "name": "Dol",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\E082336\\offboarding\\chris-eisen\\apps\\clubs\\Dta\\Smartsheet\\Clubs - Trend Sheet.xlsx\"), null, true),",
                "    Tot_Sheet = Source{[Item=\"Dol\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Tot_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Field\", type text}, {\"Classification\", type text}, {\"Year\", type text}, {\"Value\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tot",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Field",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "687d3c8e-c2ad-472e-8fbe-de15fb6acb8c",
            "sourceColumn": "Field",
            "summarizeBy": "none"
          },
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30f6cb1a-8d03-4352-8218-f2c662632c96",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebe3c81c-00de-4263-9aef-6fbaa73aaa9c",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0",
            "lineageTag": "dc8c0325-0390-42c5-8349-5fe1b6f48f14",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b5e3bbaf-56c0-4b8d-a8cd-469711f83804",
        "partitions": [
          {
            "name": "Tot",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\E082336\\offboarding\\chris-eisen\\apps\\clubs\\Dta\\Smartsheet\\Clubs - Trend Sheet.xlsx\"), null, true),",
                "    Tot_Sheet = Source{[Item=\"Tot\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Tot_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Field\", type text}, {\"Classification\", type text}, {\"Year\", type text}, {\"Value\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Exec Sum",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8ba85fa-f21c-43b7-8366-78601e5f1c40",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Total membership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6c141c49-3276-46d9-8f19-1ea974b57b83",
            "sourceColumn": "Total membership",
            "summarizeBy": "sum"
          },
          {
            "name": "Full member equivalents (FME)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f7e0e184-1407-4d0b-9577-d419b4ecf98f",
            "sourceColumn": "Full member equivalents (FME)",
            "summarizeBy": "sum"
          },
          {
            "name": "Mandatory membership %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "628692b2-18cf-4a79-826b-c24ff8cd3174",
            "sourceColumn": "Mandatory membership %",
            "summarizeBy": "sum"
          },
          {
            "name": "Employees - in season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "840224b4-72b4-446d-9618-6c47dea0350c",
            "sourceColumn": "Employees - in season",
            "summarizeBy": "sum"
          },
          {
            "name": "Memberships (FME) to employees",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "370381f1-3c35-43b5-b92d-e9c5353a15aa",
            "sourceColumn": "Memberships (FME) to employees",
            "summarizeBy": "sum"
          },
          {
            "name": "Full membership - dues (2024)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "104f3936-5ea3-49dd-8901-a5b8c24ce466",
            "sourceColumn": "Full membership - dues (2024)",
            "summarizeBy": "sum"
          },
          {
            "name": "Full membership - joining fees",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "7fb470de-d1de-4c07-9c5d-2fa7ea2e0f01",
            "sourceColumn": "Full membership - joining fees",
            "summarizeBy": "sum"
          },
          {
            "name": "Full membership - refunadable equity percentages",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "b6381519-1a5c-4072-a9bd-094ab04dcb86",
            "sourceColumn": "Full membership - refunadable equity percentages",
            "summarizeBy": "sum"
          },
          {
            "name": "Average of Full membership - total annual cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "472cb731-b55e-4134-904d-09a529097d2c",
            "sourceColumn": "Average of Full membership - total annual cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Full membership - % that had a dues rate increase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0%;-0%;0%",
            "lineageTag": "16ee9584-7c41-4ad0-b239-83152c9b3bfd",
            "sourceColumn": "Full membership - % that had a dues rate increase",
            "summarizeBy": "sum"
          },
          {
            "name": "Clubs with an annual capital assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "57e57cfe-451b-4d1a-9220-eab7cf1b9e9a",
            "sourceColumn": "Clubs with an annual capital assessment",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating assessment %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "df25a209-72cb-4eca-a3a2-42be621129ec",
            "sourceColumn": "Operating assessment %",
            "summarizeBy": "sum"
          },
          {
            "name": "Third-party debt per FME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "2214e6e4-7396-45c4-97c6-494e06af3afd",
            "sourceColumn": "Third-party debt per FME",
            "summarizeBy": "sum"
          },
          {
            "name": "Combined revenues",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "4453f7d7-b59c-4ce4-84b6-4932790b93ce",
            "sourceColumn": "Combined revenues",
            "summarizeBy": "sum"
          },
          {
            "name": "Food and beverage (F&B) revenues",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f8fa189a-812f-44b1-8c8b-514fe49e1361",
            "sourceColumn": "Food and beverage (F&B) revenues",
            "summarizeBy": "sum"
          },
          {
            "name": "Food Sales to $1 of beverage sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fef61e35-47fd-482e-8a60-84012d2aab38",
            "sourceColumn": "Food Sales to $1 of beverage sales",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B departmental subsidy to combined F&B sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "6589315d-f133-48f6-b44a-33fad52201c2",
            "sourceColumn": "F&B departmental subsidy to combined F&B sales",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B departmental subsidy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "edfd8416-88ee-452f-af34-345b857de496",
            "sourceColumn": "F&B departmental subsidy",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B departmental subsidy: Total dues revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "8b1c0aac-7791-4671-9054-1605c4cb88f7",
            "sourceColumn": "F&B departmental subsidy: Total dues revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B departmental subsidy: FME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e8da5a7e-4572-4961-b5a9-d1261ef7cf8f",
            "sourceColumn": "F&B departmental subsidy: FME",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B gross profit %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "df769172-f0bf-4f37-b534-0056ca5225e4",
            "sourceColumn": "F&B gross profit %",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM 18 holes - rounds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "75cffca3-c257-48a4-972b-05c5f83f6f1d",
            "sourceColumn": "GCM 18 holes - rounds",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM 18 holes - cost per hole",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f3ff9c74-0e19-47fc-ab4d-880bb480dc7c",
            "sourceColumn": "GCM 18 holes - cost per hole",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM 18 holes - total operating expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "da33fcf9-250b-447a-a43d-534777bd0b46",
            "sourceColumn": "GCM 18 holes - total operating expense",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM multiple course - rounds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "cf0c218f-b58c-4deb-8738-8da058c6a43e",
            "sourceColumn": "GCM multiple course - rounds",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM multiple course - cost per hole",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "db0cfad5-6b88-4b6f-b478-146267ba8441",
            "sourceColumn": "GCM multiple course - cost per hole",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM multiple course - total operating expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "a72f89b8-c563-4ea3-83bf-8a291392df56",
            "sourceColumn": "GCM multiple course - total operating expense",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "739b17be-5db6-459f-8328-c87589b242fc",
        "partitions": [
          {
            "name": "Exec Sum",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\E082336\\offboarding\\chris-eisen\\apps\\clubs\\Dta\\Smartsheet\\Clubs - Trend Sheet.xlsx\"), null, true),",
                "    #\"Exec Sum_Sheet\" = Source{[Item=\"Exec Sum\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Exec Sum_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Classification\", type text}, {\"Total membership\", type number}, {\"Full member equivalents (FME)\", Int64.Type}, {\"Mandatory membership %\", type number}, {\"Employees - in season\", Int64.Type}, {\"Memberships (FME) to employees\", type number}, {\"Full membership - dues (2024)\", Int64.Type}, {\"Full membership - joining fees\", Int64.Type}, {\"Full membership - refunadable equity percentages\", type number}, {\"Average of Full membership - total annual cost\", Int64.Type}, {\"Full membership - % that had a dues rate increase\", Int64.Type}, {\"Clubs with an annual capital assessment\", type number}, {\"Operating assessment %\", type number}, {\"Third-party debt per FME\", Int64.Type}, {\"Combined revenues\", Int64.Type}, {\"Food and beverage (F&B) revenues\", Int64.Type}, {\"Food Sales to $1 of beverage sales\", type number}, {\"F&B departmental subsidy to combined F&B sales\", type number}, {\"F&B departmental subsidy\", Int64.Type}, {\"F&B departmental subsidy: Total dues revenue\", type number}, {\"F&B departmental subsidy: FME\", Int64.Type}, {\"F&B gross profit %\", type number}, {\"GCM 18 holes - rounds\", type number}, {\"GCM 18 holes - cost per hole\", Int64.Type}, {\"GCM 18 holes - total operating expense\", type number}, {\"GCM multiple course - rounds\", type number}, {\"GCM multiple course - cost per hole\", Int64.Type}, {\"GCM multiple course - total operating expense\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Golf",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3f73e29-f32d-417c-a72a-3457a20077cd",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Rounds (18 holes)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "5839920f-b54a-4fe5-a860-00b13c008a05",
            "sourceColumn": "Rounds (18 holes)",
            "summarizeBy": "sum"
          },
          {
            "name": "Round 18 Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2835a3eb-5bfd-4fce-86bd-70a532f833bc",
            "sourceColumn": "Round 18 Change",
            "summarizeBy": "sum"
          },
          {
            "name": "Rounds (multi, based on 18)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "6cfb064c-e34d-42b5-8626-b4d0b58ab8fd",
            "sourceColumn": "Rounds (multi, based on 18)",
            "summarizeBy": "sum"
          },
          {
            "name": "Annual change (multiple holes)*",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ea7b1120-7f21-40b1-a30b-5c6be56d0371",
            "sourceColumn": "Annual change (multiple holes)*",
            "summarizeBy": "sum"
          },
          {
            "name": "Average of in-house pro shop",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "5fcc5f1f-1c2c-4f49-ba41-2490c5735851",
            "sourceColumn": "Average of in-house pro shop",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of pro shop sales %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0%;-0%;0%",
            "lineageTag": "88c92af0-ce8f-4f96-af6f-e593eba24650",
            "sourceColumn": "Cost of pro shop sales %",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost per hole",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ba249097-9acf-4a3f-bc3b-aee8a0251b28",
            "sourceColumn": "Cost per hole",
            "summarizeBy": "sum"
          },
          {
            "name": "% change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "95faf9c7-e7f4-4512-af48-58e82b2bd298",
            "sourceColumn": "% change",
            "summarizeBy": "sum"
          },
          {
            "name": "Maintained acres",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "83db8cbd-b9c1-437a-b4ea-3a63e3ae4547",
            "sourceColumn": "Maintained acres",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM cost per acre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fbc8ecf7-aa41-430e-ba5f-27c3e5b5e729",
            "sourceColumn": "GCM cost per acre",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM cost per round",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d42f2ac2-699a-47a3-aff7-78cf40fe67df",
            "sourceColumn": "GCM cost per round",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost per hole_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "68558b29-5a78-4716-89d1-40b748a131b5",
            "sourceColumn": "Cost per hole_1",
            "summarizeBy": "sum"
          },
          {
            "name": "% change*",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c915e00d-df2f-440e-a1d0-4dabe8502195",
            "sourceColumn": "% change*",
            "summarizeBy": "sum"
          },
          {
            "name": "Maintained acres_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80ad7e4e-039a-48ac-9e71-54ccd2d7406a",
            "sourceColumn": "Maintained acres_2",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM cost per acre_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "b8f681a6-3eae-4ec0-b321-79fe6f97f695",
            "sourceColumn": "GCM cost per acre_3",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM cost per round_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "774e7827-b0e7-4fb7-97a4-2cba6ba226e2",
            "sourceColumn": "GCM cost per round_4",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "7f450ba1-2e21-4fcc-8574-615de125b316",
        "partitions": [
          {
            "name": "Golf",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\E082336\\offboarding\\chris-eisen\\apps\\clubs\\Dta\\Smartsheet\\Clubs - Trend Sheet.xlsx\"), null, true),",
                "    Golf_Sheet = Source{[Item=\"Golf\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Golf_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Classification\", type text}, {\"Rounds (18 holes)\", type number}, {\"Round 18 Change\", type number}, {\"Rounds (multi, based on 18)\", type number}, {\"Annual change (multiple holes)*\", type number}, {\"Average of in-house pro shop\", type number}, {\"Cost of pro shop sales %\", type number}, {\"Cost per hole\", Int64.Type}, {\"% change\", type number}, {\"Maintained acres\", Int64.Type}, {\"GCM cost per acre\", Int64.Type}, {\"GCM cost per round\", Int64.Type}, {\"Cost per hole_1\", Int64.Type}, {\"% change*\", type number}, {\"Maintained acres_2\", Int64.Type}, {\"GCM cost per acre_3\", Int64.Type}, {\"GCM cost per round_4\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}