{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Ryan's Sheet - Single Selection\",\"Ryan's Sheet - Comparision\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.1066.0 (23.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "93436129-e0de-4338-a74f-01d51c8efdea",
        "fromColumn": "Year end",
        "fromTable": "Ryan's Sheet - Single Selection",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ea87b48e-cf73-4ee2-9724-0be41bbea877"
      },
      {
        "name": "e9dabd16-0154-4ba0-80c6-0349250d4160",
        "fromColumn": "Year end - Copy",
        "fromTable": "Ryan's Sheet - Single Selection",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9dfae6c2-a5f2-45ab-9eed-a8044e1032ba"
      },
      {
        "name": "166e3c1e-c455-493d-87dd-560dc9da4a2a",
        "fromColumn": "Year end",
        "fromTable": "Ryan's Sheet - Comparision",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c676eb26-1023-4985-ab89-14db214ea3de"
      },
      {
        "name": "26569726-066a-40eb-a93e-61b6c8f5de88",
        "fromColumn": "Year end - Copy",
        "fromTable": "Ryan's Sheet - Comparision",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8e9b3a54-d9ce-428d-b308-c3026abaf5d4"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Ryan's Sheet - Single Selection",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2308aa65-4845-473f-87a8-eb9c81f823d8",
            "sourceColumn": "RowNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "Club name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "465377ec-401a-4cb7-80bf-3957011658fb",
            "sourceColumn": "Club name",
            "summarizeBy": "none"
          },
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cf45f7d-301b-4a89-8808-a5d825db1517",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Zip Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0cd835c0-a966-4a75-9d68-aa5d35cf6f6b",
            "sourceColumn": "Zip Code",
            "summarizeBy": "count"
          },
          {
            "name": "Year end",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2ececa0a-fef8-4a80-a9db-f8a0f019f657",
            "sourceColumn": "Year end",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ea87b48e-cf73-4ee2-9724-0be41bbea877"
                },
                "isDefault": true,
                "relationship": "93436129-e0de-4338-a74f-01d51c8efdea"
              }
            ]
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ff59f97-81b7-4b26-9d65-4898e349188b",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Mandatory Membership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d671cc58-4358-436e-9aab-4486523ae672",
            "sourceColumn": "Mandatory Membership",
            "summarizeBy": "none"
          },
          {
            "name": "Full Member Equivalents (FME)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "94944809-e9ec-4647-b01d-20108be7a576",
            "sourceColumn": "Full Member Equivalents (FME)",
            "summarizeBy": "sum"
          },
          {
            "name": "Refundable Equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "473cd814-961e-4d9f-b2e8-a6fbe63b0de9",
            "sourceColumn": "Refundable Equity",
            "summarizeBy": "sum"
          },
          {
            "name": "Non-refundable equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "38829e4c-b5f4-48a8-88b6-aad4a095d280",
            "sourceColumn": "Non-refundable equity",
            "summarizeBy": "sum"
          },
          {
            "name": "Total equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c00f2b1f-56f9-4547-acac-2a5bc11a91ab",
            "sourceColumn": "Total equity",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Rate - Current Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c3f066a8-d0c9-4689-9071-a43cdad86c3f",
            "sourceColumn": "Dues Rate - Current Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Rate - Audit Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d2665498-5e3f-4bf8-be3f-c660f7c91761",
            "sourceColumn": "Dues Rate - Audit Year",
            "summarizeBy": "sum"
          },
          {
            "name": "General Capital Assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94181a4b-92d5-4dfa-bb0c-0883da2b2bb8",
            "sourceColumn": "General Capital Assessment",
            "summarizeBy": "none"
          },
          {
            "name": "Capital Assessment Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46992384-1f68-46da-bf19-34c39630c521",
            "sourceColumn": "Capital Assessment Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71fe7e1c-755f-4ddc-b71b-d1706bc3522b",
            "sourceColumn": "Operating Assessment",
            "summarizeBy": "none"
          },
          {
            "name": "Operating Assessment Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c72928fb-f0a8-4b5a-85a2-ee80e5e6ec95",
            "sourceColumn": "Operating Assessment Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Other Capital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5735b383-cd19-483f-ae39-03865723caed",
            "sourceColumn": "Other Capital",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of general capital assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a26d92c4-944e-4906-b51a-a61a9a304535",
            "sourceColumn": "Amount of general capital assessment",
            "summarizeBy": "none"
          },
          {
            "name": "Major renovation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "952c0ed7-e11a-4cc8-b31a-62cd6c60539d",
            "sourceColumn": "Major renovation",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation - 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "923bd607-bcc4-4b2f-a209-d8cfed02844a",
            "sourceColumn": "Type of Renovation - 1",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation - 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd5dc7f2-f2b8-4553-abd8-80a59ebf8577",
            "sourceColumn": "Type of Renovation - 2",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation - 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34309756-e1ac-44bd-8090-331ee8996b02",
            "sourceColumn": "Type of Renovation - 3",
            "summarizeBy": "none"
          },
          {
            "name": "Budgeted Major Capital Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00bc2d56-f884-4723-8a4d-f99a2ce414fe",
            "sourceColumn": "Budgeted Major Capital Project",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of Budgeted Major Capital Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "b72047d1-a66d-4182-949e-ad3f15d89a20",
            "sourceColumn": "Amount of Budgeted Major Capital Project",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount of Budgeted Other Capital Projects",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4cfc7f90-b16f-4721-8e74-1f3eb82d9e4f",
            "sourceColumn": "Amount of Budgeted Other Capital Projects",
            "summarizeBy": "sum"
          },
          {
            "name": "Ending PPE, net",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "26b06c7e-7ec2-46b6-8e87-fe9e1cc29860",
            "sourceColumn": "Ending PPE, net",
            "summarizeBy": "sum"
          },
          {
            "name": "Capital Expenditures (PP&E)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "11a2f0d1-40d4-4754-b171-353f983ad7df",
            "sourceColumn": "Capital Expenditures (PP&E)",
            "summarizeBy": "sum"
          },
          {
            "name": "Depreciation Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce8ce58d-eac9-42af-a9eb-427efb059438",
            "sourceColumn": "Depreciation Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Third Party Debt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1389fba9-e4b1-4016-86a7-2f7ff1acc7d7",
            "sourceColumn": "Third Party Debt",
            "summarizeBy": "none"
          },
          {
            "name": "Total Third Party Debt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "84dd6e56-ccd0-4a6f-a8b5-9a8768d13abd",
            "sourceColumn": "Total Third Party Debt",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Assets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "2f62bf4e-1e36-426f-8f3f-972f3960e1b4",
            "sourceColumn": "Current Assets",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Liabilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9441274e-e944-432a-bb44-32ec3cb63a8c",
            "sourceColumn": "Current Liabilities",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Total Liabilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fe5472f3-fdfc-4c43-b9d6-78f178b5f3e0",
            "sourceColumn": "Total Total Liabilities",
            "summarizeBy": "sum"
          },
          {
            "name": "Ending Net Assets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f80c8cce-993c-451a-be28-29c162dcd2c9",
            "sourceColumn": "Ending Net Assets",
            "summarizeBy": "sum"
          },
          {
            "name": "Golf Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ff76e343-f4bf-4bef-a6bb-0a7801a1f3ef",
            "sourceColumn": "Golf Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Tennis Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f18ba74-9bcd-4261-a426-63d7322de5cb",
            "sourceColumn": "Tennis Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Pro Shop Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f2c7ba14-9069-4690-89de-5f2d24a0e52f",
            "sourceColumn": "Pro Shop Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Other Sports Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe17a2f7-b248-41cb-a7c4-2ada66456bdd",
            "sourceColumn": "Other Sports Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d1d47698-3d85-4888-b909-605e2284efc9",
            "sourceColumn": "Dues Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Assessments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "de91abf2-98bd-415e-8535-7b3d94932420",
            "sourceColumn": "Operating Assessments",
            "summarizeBy": "sum"
          },
          {
            "name": "Non-Owner Initiation fees",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "262b405e-5877-4a44-9f57-264e57702c02",
            "sourceColumn": "Non-Owner Initiation fees",
            "summarizeBy": "sum"
          },
          {
            "name": "Food Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "642f1f7d-4cb0-45bf-839e-c8b902ae9683",
            "sourceColumn": "Food Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Beverage Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "2209a7da-1358-41d8-8530-f37dcd2d7426",
            "sourceColumn": "Beverage Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "All Other F&B Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "936971b8-1e00-4a06-87a2-a82d2ee665c8",
            "sourceColumn": "All Other F&B Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Payroll and PTEB Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a94393cc-23e6-4495-b4ae-e48ea0fd5c95",
            "sourceColumn": "Payroll and PTEB Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of sales - F&B",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "36d8dd0d-f602-436e-886e-8504534c5b39",
            "sourceColumn": "Cost of sales - F&B",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of Sales - Pro shop",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3bba849e-0fce-470d-9029-02082ced0a4a",
            "sourceColumn": "Cost of Sales - Pro shop",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Expenses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5177a28e-e6ff-4ffc-857c-60f7ff9f16dc",
            "sourceColumn": "Operating Expenses",
            "summarizeBy": "sum"
          },
          {
            "name": "Property Taxes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6191f3c-4511-427e-a188-cb61c408c27a",
            "sourceColumn": "Property Taxes",
            "summarizeBy": "sum"
          },
          {
            "name": "Insurance Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1d501100-d902-46a1-8c43-727ae0b1c220",
            "sourceColumn": "Insurance Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Total employees in season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8f625b09-2387-4308-8b77-b354dd5ea612",
            "sourceColumn": "Total employees in season",
            "summarizeBy": "sum"
          },
          {
            "name": "Use of Organized Foreign Labor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92e4597a-c473-4ec5-9f8c-e3fe590b60db",
            "sourceColumn": "Use of Organized Foreign Labor",
            "summarizeBy": "none"
          },
          {
            "name": "# Foreign Staff hired in yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f23faead-5799-4585-ba8d-5f40f4d0c7de",
            "sourceColumn": "# Foreign Staff hired in yr",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Foreign Labor Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "00719be5-05a1-4ef7-a472-77079ce01aa7",
            "sourceColumn": "Total Foreign Labor Costs",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Health Insurance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c75d96fb-6910-478c-af3b-84c2a81a5e12",
            "sourceColumn": "Increase in Health Insurance",
            "summarizeBy": "none"
          },
          {
            "name": "% inc. in Health Insurance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "552381d0-487c-4c3f-8a90-c5ee165c59a8",
            "sourceColumn": "% inc. in Health Insurance",
            "summarizeBy": "sum"
          },
          {
            "name": "Food and Beverage Minimum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa75f045-9ac8-47db-8a2a-bd6a53b89a0c",
            "sourceColumn": "Food and Beverage Minimum",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of F&B Minimum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "3d4b828f-3efa-4283-9a00-7ce5db4ed7a2",
            "sourceColumn": "Amount of F&B Minimum",
            "summarizeBy": "sum"
          },
          {
            "name": "Automatic F&B Gratuity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d45e864-4a54-42ee-9944-1b821fd659db",
            "sourceColumn": "Automatic F&B Gratuity",
            "summarizeBy": "none"
          },
          {
            "name": "% amt of F&B gratuity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "381ee14a-89ba-4a45-9a79-4dc5901dea26",
            "sourceColumn": "% amt of F&B gratuity",
            "summarizeBy": "sum"
          },
          {
            "name": "Mandatory Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "472ad185-105f-4f7c-b484-2c7d3e0bd897",
            "sourceColumn": "Mandatory Service Charge",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of Monthly Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fcf237bd-fb50-48cd-8edd-4d9300049b9a",
            "sourceColumn": "Amount of Monthly Service Charge",
            "summarizeBy": "sum"
          },
          {
            "name": "# full service kitchens",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "15e67d84-20d8-4153-9da9-369091be4184",
            "sourceColumn": "# full service kitchens",
            "summarizeBy": "sum"
          },
          {
            "name": "# covers (include function / banquet)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "feba1633-c299-40ee-8b18-11cb4192968c",
            "sourceColumn": "# covers (include function / banquet)",
            "summarizeBy": "sum"
          },
          {
            "name": "#  function / banquet covers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c401230-9b42-4f2a-8027-28685e1eb192",
            "sourceColumn": "#  function / banquet covers",
            "summarizeBy": "sum"
          },
          {
            "name": "Compensation Method for F&B Staff",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f819b95f-65de-486c-93ce-9ef594621659",
            "sourceColumn": "Compensation Method for F&B Staff",
            "summarizeBy": "none"
          },
          {
            "name": "Food sales (exc Mins)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f123abba-0012-402d-a3e4-66ffae478291",
            "sourceColumn": "Food sales (exc Mins)",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of food sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4386c0a0-ef4f-4643-a959-7a697112fe28",
            "sourceColumn": "Cost of food sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Beverage sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5a4a2088-f27d-4734-bf9a-9d763817670d",
            "sourceColumn": "Beverage sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of beverage sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4b402acc-f3c1-4132-9797-03ded41eae8d",
            "sourceColumn": "Cost of beverage sales",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Salaries and wages expense (EXC credit for M",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c27bf644-5412-4b88-a93f-3f1f7d1f449c",
            "sourceColumn": "F&B - Salaries and wages expense (EXC credit for M",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Less credit = 20% of F&B sales (only applies",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b0bb3f6b-ff2b-4537-8bf7-2734ec27371a",
            "sourceColumn": "F&B - Less credit = 20% of F&B sales (only applies",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Payroll taxes and benefits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1162d0ab-4006-4cd9-a388-8c092b9d1226",
            "sourceColumn": "F&B - Payroll taxes and benefits",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Employees' meals",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4e450c27-42ce-448b-9b00-2be597ded4fa",
            "sourceColumn": "F&B - Employees' meals",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Laundry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dcf8d523-5652-4339-934b-3ceeff706555",
            "sourceColumn": "F&B - Laundry",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Linen, china, glass, silver",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a64809c6-35ec-4aeb-9c2e-b91cd917f07b",
            "sourceColumn": "F&B - Linen, china, glass, silver",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Other expenses (excluding entertainment, val",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7da79e1f-9bf2-4e40-9dd2-f1655242f9a5",
            "sourceColumn": "F&B - Other expenses (excluding entertainment, val",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Menu Prices",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e40f25e-43a0-425e-8106-693ff287bc3f",
            "sourceColumn": "Increase in Menu Prices",
            "summarizeBy": "none"
          },
          {
            "name": "Av % inc Menu Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c23ffad1-5f9b-4057-b5b3-c557eb15b02b",
            "sourceColumn": "Av % inc Menu Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Beverage Prices",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fea8d455-2f9a-4708-90f5-fba2bbbafa5d",
            "sourceColumn": "Increase in Beverage Prices",
            "summarizeBy": "none"
          },
          {
            "name": "Av % inc Bev Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0b023354-64ae-4d61-97c3-12d577fad9bc",
            "sourceColumn": "Av % inc Bev Price",
            "summarizeBy": "sum"
          },
          {
            "name": "# of holes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2cbcbc1c-d05c-4a3c-9525-3942f566b07c",
            "sourceColumn": "# of holes",
            "summarizeBy": "sum"
          },
          {
            "name": "Maintained golf acreage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "78d29a85-66ac-4dfb-9413-446f213ad3fb",
            "sourceColumn": "Maintained golf acreage",
            "summarizeBy": "sum"
          },
          {
            "name": "Rounds per year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "a50f2f95-f1c7-440c-998a-96a4f2c7fe3c",
            "sourceColumn": "Rounds per year",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - Salaries and wages",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "347a79cd-3b75-49e3-8590-9b017ed6b9d8",
            "sourceColumn": "GCM - Salaries and wages",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - Payroll taxes and benefits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "016555ad-b295-427e-8ed2-e5af6d337159",
            "sourceColumn": "GCM - Payroll taxes and benefits",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - Course supplies and contracts (includes gaso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "23901c32-4df6-473b-8bcc-8eb35961544d",
            "sourceColumn": "GCM - Course supplies and contracts (includes gaso",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - Repairs & mtce (includes tree trimming, lake",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d6ba0ee-f4eb-4cba-b746-06b86ed577c8",
            "sourceColumn": "GCM - Repairs & mtce (includes tree trimming, lake",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - Leased equipment expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a02c8fcb-4095-4b94-ac39-c245c45c4d8d",
            "sourceColumn": "GCM - Leased equipment expense",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - All other expenses (including utilities)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aba90048-ccbf-46f3-9b39-58d2a334d5f1",
            "sourceColumn": "GCM - All other expenses (including utilities)",
            "summarizeBy": "sum"
          },
          {
            "name": "Year end - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "41999a83-77cf-4684-9a7e-c973cb8f20b9",
            "sourceColumn": "Year end - Copy",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_9dfae6c2-a5f2-45ab-9eed-a8044e1032ba"
                },
                "isDefault": true,
                "relationship": "e9dabd16-0154-4ba0-80c6-0349250d4160"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d217fa7d-e2cb-4b78-a9ba-4cbcc52954d5",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Total Membership Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'Ryan''s Sheet - Single Selection'[Dues Rate - Audit Year] + 'Ryan''s Sheet - Single Selection'[Capital Assessment Amount] + 'Ryan''s Sheet - Single Selection'[Operating Assessment Amount] + 'Ryan''s Sheet - Single Selection'[Amount of F&B Minimum] + 'Ryan''s Sheet - Single Selection'[Amount of Monthly Service Charge]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "95d4ef8b-3a77-45be-9c75-504b1bac74b8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Sports Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Single Selection'[Golf Revenue] + 'Ryan''s Sheet - Single Selection'[Tennis Revenue] + 'Ryan''s Sheet - Single Selection'[Other Sports Revenue] + 'Ryan''s Sheet - Single Selection'[Pro Shop Sales]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "895b923e-3232-4e4e-94f0-d0192b91a536",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Rev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Single Selection'[Sports Revenue] + 'Ryan''s Sheet - Single Selection'[Dues Revenue] + 'Ryan''s Sheet - Single Selection'[Food Revenue] + 'Ryan''s Sheet - Single Selection'[Beverage Revenue] + 'Ryan''s Sheet - Single Selection'[All Other F&B Revenue]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "a9495c57-6ad0-4f63-a044-f3a702617749",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Exp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Single Selection'[Payroll and PTEB Expense] + 'Ryan''s Sheet - Single Selection'[Cost of beverage sales] + 'Ryan''s Sheet - Single Selection'[Operating Expenses] + 'Ryan''s Sheet - Single Selection'[Cost of food sold] + 'Ryan''s Sheet - Single Selection'[Cost of Sales - Pro shop] + 'Ryan''s Sheet - Single Selection'[Insurance Expense] + 'Ryan''s Sheet - Single Selection'[Property Taxes]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "2fdce1a9-3a12-41ea-b0da-ac874e8b537e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Cost of Sales F&B",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Single Selection'[Cost of food sold] + 'Ryan''s Sheet - Single Selection'[Cost of beverage sales]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "d7cbaac8-269a-4f0c-8e89-ad065e5ac879",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Tax & Insurance Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Single Selection'[Property Taxes] + 'Ryan''s Sheet - Single Selection'[Insurance Expense]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "62150e88-ba83-4e24-8b75-54aef48de659",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Single Selection'[Dues Revenue] + 'Ryan''s Sheet - Single Selection'[Food Revenue] + 'Ryan''s Sheet - Single Selection'[Beverage Revenue] + 'Ryan''s Sheet - Single Selection'[All Other F&B Revenue] + 'Ryan''s Sheet - Single Selection'[Sports Revenue]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "76280761-2b83-428c-b551-2f00f94321ac",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Food & Beverage Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Single Selection'[Food Revenue] + 'Ryan''s Sheet - Single Selection'[Beverage Revenue]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "41519cc4-37de-4e1f-80ce-060817fd3bc0",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "GCM Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Single Selection'[GCM - All other expenses (including utilities)] + 'Ryan''s Sheet - Single Selection'[GCM - Course supplies and contracts (includes gaso] + 'Ryan''s Sheet - Single Selection'[GCM - Leased equipment expense] + 'Ryan''s Sheet - Single Selection'[GCM - Payroll taxes and benefits] + 'Ryan''s Sheet - Single Selection'[GCM - Repairs & mtce (includes tree trimming, lake] + 'Ryan''s Sheet - Single Selection'[GCM - Salaries and wages]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2c7f74cd-ce54-4cfb-9be3-e7e6179b42f6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Minimums and Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Ryan''s Sheet - Single Selection'[Food and Beverage Minimum] = \"Yes\" && ",
              "    'Ryan''s Sheet - Single Selection'[Mandatory Service Charge]= \"Yes\", ",
              "    \"Yes\", ",
              "    \"No\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3791385c-2d85-4671-b34d-68a02ae3b00d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "lineageTag": "740a214f-e1b4-4d9d-9856-f6458e64eb7c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Minimums and Gratuity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Ryan''s Sheet - Single Selection'[Food and Beverage Minimum] = \"Yes\" && ",
              "    'Ryan''s Sheet - Single Selection'[Automatic F&B Gratuity] = \"Yes\", ",
              "    \"Yes\", ",
              "    \"No\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "5fda625a-45fd-4604-a85d-51fb01214a43",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Minimums and Gratuity and Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Ryan''s Sheet - Single Selection'[Food and Beverage Minimum] = \"Yes\" &&",
              "    'Ryan''s Sheet - Single Selection'[Automatic F&B Gratuity] = \"Yes\" &&",
              "    'Ryan''s Sheet - Single Selection'[Mandatory Service Charge]= \"Yes\", ",
              "    \"Yes\", ",
              "    \"No\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "b08422a7-36f4-4925-ae26-e2cc80905f6d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Neither Gratuity or Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    OR('Ryan''s Sheet - Single Selection'[Automatic F&B Gratuity] = \"No\",",
              "    'Ryan''s Sheet - Single Selection'[Mandatory Service Charge]= \"No\"), ",
              "    \"Yes\", ",
              "    \"No\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "32a7977d-f31e-420c-8cfd-50475b6756ae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "F&B All other expenses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "'Ryan''s Sheet - Single Selection'[F&B - Employees' meals] + 'Ryan''s Sheet - Single Selection'[F&B - Laundry] + 'Ryan''s Sheet - Single Selection'[F&B - Less credit = 20% of F&B sales (only applies] + 'Ryan''s Sheet - Single Selection'[F&B - Linen, china, glass, silver] + 'Ryan''s Sheet - Single Selection'[F&B - Other expenses (excluding entertainment, val]",
            "isDataTypeInferred": true,
            "lineageTag": "b731b574-f036-453a-965f-1cc0e253a38d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "F&B departmental subsidy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "('Ryan''s Sheet - Single Selection'[Food Revenue] + 'Ryan''s Sheet - Single Selection'[Beverage Revenue]) - ('Ryan''s Sheet - Single Selection'[Cost of food sold] + 'Ryan''s Sheet - Single Selection'[Cost of beverage sales] + 'Ryan''s Sheet - Single Selection'[F&B - Salaries and wages expense (EXC credit for M] + 'Ryan''s Sheet - Single Selection'[F&B - Less credit = 20% of F&B sales (only applies] + 'Ryan''s Sheet - Single Selection'[F&B - Payroll taxes and benefits] + 'Ryan''s Sheet - Single Selection'[F&B - Employees' meals] + 'Ryan''s Sheet - Single Selection'[F&B - Laundry] + 'Ryan''s Sheet - Single Selection'[F&B - Linen, china, glass, silver] + 'Ryan''s Sheet - Single Selection'[F&B - Other expenses (excluding entertainment, val])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "faa30030-3bcd-476b-a25f-a4dbe6c76219",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "bddf6ea9-130d-4b1b-96f0-008c039523fb",
        "measures": [
          {
            "name": "Change in Dues",
            "expression": "SUM('Ryan''s Sheet - Single Selection'[Dues Rate - Current Year]) - SUM('Ryan''s Sheet - Single Selection'[Dues Rate - Audit Year])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9c934f64-1a2a-4de7-a553-7e52c914ca0a"
          },
          {
            "name": "% Change in Dues",
            "expression": "DIVIDE((SUM('Ryan''s Sheet - Single Selection'[Dues Rate - Current Year]) - SUM('Ryan''s Sheet - Single Selection'[Dues Rate - Audit Year])), SUM('Ryan''s Sheet - Single Selection'[Dues Rate - Audit Year]),0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "b18a4f54-9179-4467-a82b-f62c7a6d55c4"
          },
          {
            "name": "Increasing Dues",
            "expression": [
              "",
              "    IF(",
              "        AVERAGE('Ryan''s Sheet - Single Selection'[Dues Rate - Current Year]) > AVERAGE('Ryan''s Sheet - Single Selection'[Dues Rate - Audit Year]),",
              "        \"Yes\",",
              "        \"No\"",
              "    )"
            ],
            "lineageTag": "3b74e0ec-faa8-411a-9605-5dd14450f5eb"
          },
          {
            "name": "Refundable Equity %",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Refundable Equity]), (SUM('Ryan''s Sheet - Single Selection'[Refundable Equity]) + SUM('Ryan''s Sheet - Single Selection'[Non-refundable equity])),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "823de370-0cb3-4c8c-9f98-3ef8a41a69ef"
          },
          {
            "name": "Working Captial Ratio",
            "expression": "DIVIDE(AVERAGE('Ryan''s Sheet - Single Selection'[Current Assets]), AVERAGE('Ryan''s Sheet - Single Selection'[Current Liabilities]),0)",
            "formatString": "0.00",
            "lineageTag": "1e5519fc-203b-4905-ad5e-e28a2fbc196d"
          },
          {
            "name": "Positive Working Capital",
            "expression": [
              "",
              "    IF(",
              "        (SUM('Ryan''s Sheet - Single Selection'[Current Assets]) - SUM('Ryan''s Sheet - Single Selection'[Current Liabilities])) > 0,",
              "        \"Yes\",",
              "        \"No\"",
              "    )"
            ],
            "lineageTag": "acbb8653-5246-4cea-ae44-19e64360fa45"
          },
          {
            "name": "Debt / Equity Ratio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE(AVERAGE('Ryan''s Sheet - Single Selection'[Total Total Liabilities]), AVERAGE('Ryan''s Sheet - Single Selection'[Ending Net Assets]),0)",
            "lineageTag": "46002068-c3dd-4495-aa39-e7e97d837469"
          },
          {
            "name": "Ending Net Assets per FME",
            "expression": "DIVIDE(AVERAGE('Ryan''s Sheet - Single Selection'[Ending Net Assets]), AVERAGE('Ryan''s Sheet - Single Selection'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "0a73b11b-da7e-42d7-a2db-49f5959b8fdd"
          },
          {
            "name": "Third Party Debt per FME",
            "expression": "DIVIDE(AVERAGE('Ryan''s Sheet - Single Selection'[Total Third Party Debt]), AVERAGE('Ryan''s Sheet - Single Selection'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fb426686-7abd-40f5-95d9-41c0ef7fce8b"
          },
          {
            "name": "Dues Revenue%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]), ((SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) + SUM('Ryan''s Sheet - Single Selection'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "37dabbfa-6957-4bb7-8fce-ac6e2af47852"
          },
          {
            "name": "Sports Revenue%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Sports Revenue]), ((SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) + SUM('Ryan''s Sheet - Single Selection'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "3dad9420-01cb-44f2-acb4-c8e0bc441366"
          },
          {
            "name": "Food Revenue%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Food Revenue]), ((SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) + SUM('Ryan''s Sheet - Single Selection'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "91673899-89c5-49bf-956d-0909dc04a522"
          },
          {
            "name": "Beverage Revenue%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]), ((SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) + SUM('Ryan''s Sheet - Single Selection'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Sports Revenue]))), 0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "81c85b43-884e-43a7-8100-4e3044391287"
          },
          {
            "name": "Other Revenue%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[All Other F&B Revenue]), ((SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) + SUM('Ryan''s Sheet - Single Selection'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "6b56eddf-9a31-4b88-970a-447d817e8831"
          },
          {
            "name": "Payroll and Related%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Payroll and PTEB Expense]), SUM('Ryan''s Sheet - Single Selection'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "061af994-a393-4830-9be7-63d303eb240d"
          },
          {
            "name": "Cost of Sales%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Cost of Sales F&B]), SUM('Ryan''s Sheet - Single Selection'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "71f82c3f-c493-4643-bc65-7ade7c24c9a8"
          },
          {
            "name": "Operating Expense%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Operating Expenses]) + SUM('Ryan''s Sheet - Single Selection'[Cost of Sales - Pro shop]), SUM('Ryan''s Sheet - Single Selection'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dcf03af1-68e9-4967-852e-26568e6560c5"
          },
          {
            "name": "Tax & Insurance Expense%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Property Taxes]) + SUM('Ryan''s Sheet - Single Selection'[Insurance Expense]), SUM('Ryan''s Sheet - Single Selection'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ec2e9e64-a0d5-4f20-94c9-b0bfb74ee428"
          },
          {
            "name": "Payroll and Related Rev%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Payroll and PTEB Expense]), ((SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) + SUM('Ryan''s Sheet - Single Selection'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "02003865-8462-44cb-8bc6-cbb1a22a0e1b"
          },
          {
            "name": "Cost of Sales Rev%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Cost of Sales F&B]), ((SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) + SUM('Ryan''s Sheet - Single Selection'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5bdad52e-8a4a-43c2-bc37-76b55169d69b"
          },
          {
            "name": "Operating Expense Rev%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Operating Expenses]) + SUM('Ryan''s Sheet - Single Selection'[Cost of Sales - Pro shop]), ((SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) + SUM('Ryan''s Sheet - Single Selection'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "33a59d06-fa81-43cd-88ea-fe8f3d06154a"
          },
          {
            "name": "Tax & Insurance Expense Rev%",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Property Taxes]) + SUM('Ryan''s Sheet - Single Selection'[Insurance Expense]), ((SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) + SUM('Ryan''s Sheet - Single Selection'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "019a5035-a2cf-4a71-b720-131120daccd1"
          },
          {
            "name": "Total Expense as % of Total Revenue",
            "expression": "[Payroll and Related Rev%] + [Cost of Sales Rev%] + [Operating Expense Rev%] + [Tax & Insurance Expense Rev%]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1837d24e-0710-4890-95c6-5246438ed809"
          },
          {
            "name": "Surplus (Deficit)",
            "expression": "SUM('Ryan''s Sheet - Single Selection'[Total Rev]) - SUM('Ryan''s Sheet - Single Selection'[Total Exp])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2c90ace8-fc84-470c-83d7-c6d2941557d7"
          },
          {
            "name": "Payroll and Related per FME",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Payroll and PTEB Expense]), SUM('Ryan''s Sheet - Single Selection'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6f9b8d01-39d9-48fe-a617-c564d8f41061"
          },
          {
            "name": "FME to Employee",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Full Member Equivalents (FME)]), SUM('Ryan''s Sheet - Single Selection'[Total employees in season]),0)",
            "formatString": "0.0",
            "lineageTag": "6a611c22-0eff-45fe-909b-e518e7662153"
          },
          {
            "name": "Food Sales",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Food Revenue]), SUM('Ryan''s Sheet - Single Selection'[Food Revenue]),0) ",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0809d12f-0ce6-4974-a4a6-51df9168f31e"
          },
          {
            "name": "Food Gross Profit",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) - SUM('Ryan''s Sheet - Single Selection'[Cost of food sold]) - SUM('Ryan''s Sheet - Single Selection'[F&B - Employees' meals]), SUM('Ryan''s Sheet - Single Selection'[Food Revenue]),0) ",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "60c055dc-84e9-41d8-9a88-93d65380f5ab"
          },
          {
            "name": "Food Sold Cost",
            "expression": "1 - [Food Gross Profit]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "caf650bb-4ebe-47db-98cf-bd2d7542d966"
          },
          {
            "name": "Beverage Sales Calc",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]), SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "509659cc-6ca0-4f29-a860-6db8bb4069a2"
          },
          {
            "name": "Beverage Gross Profit",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) - SUM('Ryan''s Sheet - Single Selection'[Cost of beverage sales]), SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "46468ea6-1316-4882-ba35-4c093b4f8285"
          },
          {
            "name": "Cost of Beverage Sold",
            "expression": "1 - [Beverage Gross Profit]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "cd7c324a-0a44-48aa-807b-6cbf07d7805c"
          },
          {
            "name": "Food & Beverage Sales",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Food & Beverage Revenue]), SUM('Ryan''s Sheet - Single Selection'[Food & Beverage Revenue]),0) ",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4b5c681d-8253-4425-994b-f96414e9be7c"
          },
          {
            "name": "Food & Beverage Gross Profit",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Food & Beverage Revenue]) - SUM('Ryan''s Sheet - Single Selection'[Cost of Sales F&B]), SUM('Ryan''s Sheet - Single Selection'[Food & Beverage Revenue]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f8c95f50-01d3-4ac3-9dda-18b6f977f89b"
          },
          {
            "name": "Cost of Food & Beverage Sold",
            "expression": "1 - [Food & Beverage Gross Profit]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "9450f19c-8e0c-48e8-b888-a31db30bbaac"
          },
          {
            "name": "Cost per Hole",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM Total]), SUM('Ryan''s Sheet - Single Selection'[# of holes]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "dce08ea0-ade9-4c31-abde-34006959c96b"
          },
          {
            "name": "Cost per Round",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM Total]), SUM('Ryan''s Sheet - Single Selection'[Rounds per year]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "bc50d945-31e7-4c39-8f29-9c6f9120ec9b"
          },
          {
            "name": "Cost per Acre",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM Total]), SUM('Ryan''s Sheet - Single Selection'[Maintained golf acreage]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9954ee6f-ebfa-407a-8bf5-f1d66988b32c"
          },
          {
            "name": "Salaries and Wage per 18",
            "expression": [
              "",
              "    DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - Salaries and wages]), 18, 0) *",
              "    DIVIDE(18, SUM('Ryan''s Sheet - Single Selection'[# of holes]), 0)",
              ""
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a1eac698-a434-4b52-95a4-8b8438facd4a"
          },
          {
            "name": "Payroll Taxes and Benefits per 18",
            "expression": [
              "",
              "    DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - Payroll taxes and benefits]), 18,0) *",
              "    DIVIDE(18, SUM('Ryan''s Sheet - Single Selection'[# of holes]),0)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "bdc76b68-847e-4fe7-9689-b48e11e51600"
          },
          {
            "name": "Course Supplies per 18",
            "expression": [
              "",
              "    DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - Course supplies and contracts (includes gaso]), 18,0) *",
              "    DIVIDE(18, SUM('Ryan''s Sheet - Single Selection'[# of holes]),0)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "358789c3-ccc8-43e6-83a7-275bc236b6a8"
          },
          {
            "name": "Repairs per 18",
            "expression": [
              "",
              "    DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - Repairs & mtce (includes tree trimming, lake]), 18,0) *",
              "    DIVIDE(18, SUM('Ryan''s Sheet - Single Selection'[# of holes]),0)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6c0b0b49-e81e-46ef-bacf-795c206a8d1a"
          },
          {
            "name": "Leased Equipment per 18",
            "expression": [
              "",
              "    DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - Leased equipment expense]), 18,0) *",
              "    DIVIDE(18, SUM('Ryan''s Sheet - Single Selection'[# of holes]),0)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9e24d024-22fa-4072-bef2-52c6d02356cc"
          },
          {
            "name": "All Other Expenses per 18",
            "expression": [
              "",
              "    DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - All other expenses (including utilities)]), 18,0) *",
              "    DIVIDE(18, SUM('Ryan''s Sheet - Single Selection'[# of holes]),0)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "221775be-9324-4a84-a2f2-98e4c958e0d7"
          },
          {
            "name": "Total Expenses per 18",
            "expression": [
              "",
              "    DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM Total]), 18,0) *",
              "    DIVIDE(18, SUM('Ryan''s Sheet - Single Selection'[# of holes]),0)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d155a6ab-ed7e-4cca-8fe6-e565e4edfe51"
          },
          {
            "name": "Total Expenses per 18 Holes",
            "expression": "[Total Expenses per 18] * 18",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "71cbeb6b-d33b-4d84-b294-f831665753f1"
          },
          {
            "name": "Salaries and Wages %",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - Salaries and wages]), SUM('Ryan''s Sheet - Single Selection'[GCM Total]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f583e601-9a56-402a-9415-01058954f670"
          },
          {
            "name": "Payroll Taxes and Employee Benefits %",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - Payroll taxes and benefits]), SUM('Ryan''s Sheet - Single Selection'[GCM Total]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "79632ba5-d8b2-467b-a990-f84bd115b7eb"
          },
          {
            "name": "Course Supplies %",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - Course supplies and contracts (includes gaso]), SUM('Ryan''s Sheet - Single Selection'[GCM Total]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2aeb4f32-56e4-477d-8576-41078d9df7d0"
          },
          {
            "name": "Repairs to Equipment %",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - Repairs & mtce (includes tree trimming, lake]), SUM('Ryan''s Sheet - Single Selection'[GCM Total]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c2a32135-e5c1-4224-83c9-d44b1574420f"
          },
          {
            "name": "Leased Equipment %",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - Leased equipment expense]), SUM('Ryan''s Sheet - Single Selection'[GCM Total]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bee2e4fb-92e2-4277-8de2-954764992e5d"
          },
          {
            "name": "All Other Expenses %",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM - All other expenses (including utilities)]), SUM('Ryan''s Sheet - Single Selection'[GCM Total]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "6aad2190-a910-4cca-9645-5ac927dcac16"
          },
          {
            "name": "GCM Costs as % of Dues",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM Total]), SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ec3c28ef-a58d-4a0d-87f1-f408b61792e2"
          },
          {
            "name": "GCM Costs as % of Operating Costs",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[GCM Total]), SUM('Ryan''s Sheet - Single Selection'[Total Exp]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dceafbe2-1d97-403e-8d6f-5825f5feb1ca"
          },
          {
            "name": "Restaurant Sales per FME",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]), SUM('Ryan''s Sheet - Single Selection'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "cb87098d-51a5-462e-9f49-8fbe1d3da726"
          },
          {
            "name": "Restaurant Salaries Compared to Revenue%",
            "expression": [
              "DIVIDE(",
              "    SUM('Ryan''s Sheet - Single Selection'[F&B - Salaries and wages expense (EXC credit for M]) + SUM('Ryan''s Sheet - Single Selection'[F&B - Payroll taxes and benefits]), ",
              "    SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]),",
              "    0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "27720f7e-e8c4-4362-87e7-3b6d361f4968"
          },
          {
            "name": "Salaries and Wages % of Rev",
            "expression": [
              "DIVIDE(",
              "    SUM('Ryan''s Sheet - Single Selection'[F&B - Salaries and wages expense (EXC credit for M]), ",
              "    SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]),",
              "    0)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7f47fc5c-81e9-455c-922d-7de011e49247"
          },
          {
            "name": "Payroll Taxes % of Rev",
            "expression": [
              "DIVIDE(",
              "    SUM('Ryan''s Sheet - Single Selection'[F&B - Payroll taxes and benefits]), ",
              "    SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]),",
              "    0)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c5ee863f-c0e3-4700-bf1d-0cfebf57fe99"
          },
          {
            "name": "F&B All Other Expenses % of Rev",
            "expression": [
              "DIVIDE(",
              "    SUM('Ryan''s Sheet - Single Selection'[F&B All other expenses]), ",
              "    SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]),",
              "    0)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b7978b73-ffdb-470c-bf94-7592969c5d0f"
          },
          {
            "name": "Total Department Expenses % of Rev%",
            "expression": [
              "DIVIDE(",
              "    SUM('Ryan''s Sheet - Single Selection'[F&B - Salaries and wages expense (EXC credit for M]) + SUM('Ryan''s Sheet - Single Selection'[F&B - Payroll taxes and benefits]) + SUM('Ryan''s Sheet - Single Selection'[F&B All other expenses]), ",
              "    SUM('Ryan''s Sheet - Single Selection'[Food Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]),",
              "    0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cfc943ef-9595-4fa8-b52e-1934c42dcd94"
          },
          {
            "name": "F&B Gross Profit %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    (",
              "        (SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Food Revenue]))",
              "         - (SUM('Ryan''s Sheet - Single Selection'[Cost of beverage sales]) + SUM('Ryan''s Sheet - Single Selection'[Cost of food sold]))",
              "    ), ",
              "    (SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]) + SUM('Ryan''s Sheet - Single Selection'[Food Revenue])),",
              "    0",
              "    )"
            ],
            "lineageTag": "58a16d54-78c6-44c2-9446-c4f769a62583"
          },
          {
            "name": "Departmental (subsidy)",
            "expression": "([F&B Gross Profit %] - [Total Department Expenses % of Rev%])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fcb0a221-8585-4f4a-b645-87b08f74c231"
          },
          {
            "name": "Food Sales to Beverage Sales",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Food Revenue]), SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]),0)",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1a59c7ce-e3f6-4631-8759-a4ffc507dfb3"
          },
          {
            "name": "Subsidy per FME",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[F&B departmental subsidy]), SUM('Ryan''s Sheet - Single Selection'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "76b93ddb-1347-4fc8-9805-0bf8e2b2598c"
          },
          {
            "name": "F&B departmental subsidy: Total dues revenue",
            "expression": "DIVIDE(ABS(SUM('Ryan''s Sheet - Single Selection'[F&B departmental subsidy])), SUM('Ryan''s Sheet - Single Selection'[Dues Revenue]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cf0dfba7-2892-4b71-9fc0-78f50127d933"
          },
          {
            "name": "Food Revenue %",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Food Revenue]), SUM('Ryan''s Sheet - Single Selection'[Food & Beverage Revenue]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "79685cb3-3ea7-4dc5-94d5-f605967d44ef"
          },
          {
            "name": "Beverage Revenue %",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Single Selection'[Beverage Revenue]), SUM('Ryan''s Sheet - Single Selection'[Food & Beverage Revenue]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1ac3e05e-7155-427d-b165-85d9cf5eb57f"
          }
        ],
        "partitions": [
          {
            "name": "Ryan's Sheet - Single Selection",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"2391507492726660\" = Source{[Key=\"2391507492726660\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"2391507492726660\",{{\"RowNumber\", Int64.Type}, {\"Club name\", type text}, {\"Classification\", type text}, {\"Zip Code\", Int64.Type}, {\"Year end\", type date}, {\"Type\", type text}, {\"Mandatory Membership\", type text}, {\"Full Member Equivalents (FME)\", type number}, {\"Refundable Equity\", Int64.Type}, {\"Non-refundable equity\", Int64.Type}, {\"Total equity\", Int64.Type}, {\"Dues Rate - Current Year\", Int64.Type}, {\"Dues Rate - Audit Year\", type number}, {\"General Capital Assessment\", type text}, {\"Capital Assessment Amount\", Int64.Type}, {\"Operating Assessment\", type text}, {\"Operating Assessment Amount\", type any}, {\"Other Capital\", type text}, {\"Amount of general capital assessment\", type any}, {\"Major renovation\", type text}, {\"Type of Renovation - 1\", type text}, {\"Type of Renovation - 2\", type text}, {\"Type of Renovation - 3\", type text}, {\"Budgeted Major Capital Project\", type text}, {\"Amount of Budgeted Major Capital Project\", Int64.Type}, {\"Amount of Budgeted Other Capital Projects\", Int64.Type}, {\"Ending PPE, net\", Int64.Type}, {\"Capital Expenditures (PP&E)\", Int64.Type}, {\"Depreciation Expense\", Int64.Type}, {\"Third Party Debt\", type text}, {\"Total Third Party Debt\", Int64.Type}, {\"Current Assets\", Int64.Type}, {\"Current Liabilities\", Int64.Type}, {\"Total Total Liabilities\", Int64.Type}, {\"Ending Net Assets\", Int64.Type}, {\"Golf Revenue\", Int64.Type}, {\"Tennis Revenue\", Int64.Type}, {\"Pro Shop Sales\", Int64.Type}, {\"Other Sports Revenue\", Int64.Type}, {\"Dues Revenue\", Int64.Type}, {\"Operating Assessments\", Int64.Type}, {\"Non-Owner Initiation fees\", Int64.Type}, {\"Food Revenue\", Int64.Type}, {\"Beverage Revenue\", Int64.Type}, {\"All Other F&B Revenue\", Int64.Type}, {\"Payroll and PTEB Expense\", Int64.Type}, {\"Cost of sales - F&B\", Int64.Type}, {\"Cost of Sales - Pro shop\", Int64.Type}, {\"Operating Expenses\", Int64.Type}, {\"Property Taxes\", Int64.Type}, {\"Insurance Expense\", Int64.Type}, {\"Total employees in season\", type number}, {\"Use of Organized Foreign Labor\", type text}, {\"# Foreign Staff hired in yr\", Int64.Type}, {\"Total Foreign Labor Costs\", type number}, {\"Increase in Health Insurance\", type text}, {\"% inc. in Health Insurance\", type number}, {\"Food and Beverage Minimum\", type text}, {\"Amount of F&B Minimum\", Int64.Type}, {\"Automatic F&B Gratuity\", type text}, {\"% amt of F&B gratuity\", type number}, {\"Mandatory Service Charge\", type text}, {\"Amount of Monthly Service Charge\", type number}, {\"# full service kitchens\", Int64.Type}, {\"# covers (include function / banquet)\", Int64.Type}, {\"#  function / banquet covers\", Int64.Type}, {\"Compensation Method for F&B Staff\", type text}, {\"Food sales (exc Mins)\", Int64.Type}, {\"Cost of food sold\", Int64.Type}, {\"Beverage sales\", Int64.Type}, {\"Cost of beverage sales\", Int64.Type}, {\"F&B - Salaries and wages expense (EXC credit for M\", Int64.Type}, {\"F&B - Less credit = 20% of F&B sales (only applies\", type number}, {\"F&B - Payroll taxes and benefits\", Int64.Type}, {\"F&B - Employees' meals\", Int64.Type}, {\"F&B - Laundry\", Int64.Type}, {\"F&B - Linen, china, glass, silver\", Int64.Type}, {\"F&B - Other expenses (excluding entertainment, val\", Int64.Type}, {\"Increase in Menu Prices\", type text}, {\"Av % inc Menu Price\", type number}, {\"Increase in Beverage Prices\", type text}, {\"Av % inc Bev Price\", type number}, {\"# of holes\", Int64.Type}, {\"Maintained golf acreage\", type number}, {\"Rounds per year\", Int64.Type}, {\"GCM - Salaries and wages\", Int64.Type}, {\"GCM - Payroll taxes and benefits\", Int64.Type}, {\"GCM - Course supplies and contracts (includes gaso\", Int64.Type}, {\"GCM - Repairs & mtce (includes tree trimming, lake\", Int64.Type}, {\"GCM - Leased equipment expense\", Int64.Type}, {\"GCM - All other expenses (including utilities)\", Int64.Type}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"Year end\", \"Year end - Copy\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Duplicated Column\",{{\"Year end - Copy\", type date}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type1\", \"Year\", each Date.Year([#\"Year end - Copy\"]), Int64.Type),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Inserted Year\",{{\"Year\", type text}}),",
                "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type2\", {{\"Total equity\", 0}}),",
                "    #\"Replaced Errors1\" = Table.ReplaceErrorValues(#\"Replaced Errors\", {{\"Golf Revenue\", 0}}),",
                "    #\"Replaced Errors2\" = Table.ReplaceErrorValues(#\"Replaced Errors1\", {{\"Tennis Revenue\", 0}}),",
                "    #\"Replaced Errors3\" = Table.ReplaceErrorValues(#\"Replaced Errors2\", {{\"Pro Shop Sales\", 0}}),",
                "    #\"Replaced Errors4\" = Table.ReplaceErrorValues(#\"Replaced Errors3\", {{\"Other Sports Revenue\", 0}}),",
                "    #\"Replaced Errors5\" = Table.ReplaceErrorValues(#\"Replaced Errors4\", {{\"Dues Revenue\", 0}}),",
                "    #\"Replaced Errors6\" = Table.ReplaceErrorValues(#\"Replaced Errors5\", {{\"Operating Assessments\", 0}}),",
                "    #\"Replaced Errors7\" = Table.ReplaceErrorValues(#\"Replaced Errors6\", {{\"Non-Owner Initiation fees\", 0}}),",
                "    #\"Replaced Errors8\" = Table.ReplaceErrorValues(#\"Replaced Errors7\", {{\"Food Revenue\", 0}}),",
                "    #\"Replaced Errors9\" = Table.ReplaceErrorValues(#\"Replaced Errors8\", {{\"Beverage Revenue\", 0}}),",
                "    #\"Replaced Errors10\" = Table.ReplaceErrorValues(#\"Replaced Errors9\", {{\"All Other F&B Revenue\", 0}}),",
                "    #\"Replaced Errors11\" = Table.ReplaceErrorValues(#\"Replaced Errors10\", {{\"Payroll and PTEB Expense\", 0}}),",
                "    #\"Replaced Errors12\" = Table.ReplaceErrorValues(#\"Replaced Errors11\", {{\"Cost of sales - F&B\", 0}}),",
                "    #\"Replaced Errors13\" = Table.ReplaceErrorValues(#\"Replaced Errors12\", {{\"Cost of Sales - Pro shop\", 0}}),",
                "    #\"Replaced Errors14\" = Table.ReplaceErrorValues(#\"Replaced Errors13\", {{\"Operating Expenses\", 0}}),",
                "    #\"Replaced Errors15\" = Table.ReplaceErrorValues(#\"Replaced Errors14\", {{\"Property Taxes\", 0}}),",
                "    #\"Replaced Errors16\" = Table.ReplaceErrorValues(#\"Replaced Errors15\", {{\"Insurance Expense\", 0}}),",
                "    #\"Replaced Errors17\" = Table.ReplaceErrorValues(#\"Replaced Errors16\", {{\"GCM - Leased equipment expense\", 0}}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Replaced Errors17\",{{\"Operating Assessment Amount\", Int64.Type}}),",
                "    #\"Replaced Errors18\" = Table.ReplaceErrorValues(#\"Changed Type3\", {{\"Operating Assessment Amount\", null}})",
                "in",
                "    #\"Replaced Errors18\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_2b72d69d-3aac-4def-83df-5374ee625918",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c0d9a43a-c91d-467e-b484-18422c681ddc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f34bbde5-99e1-4ff1-acdf-f246589d342a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "95444b6e-b29e-492e-8d8f-39a590873a29",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e121a988-8d06-4630-b118-2e28e8733325",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "93d846ce-80f5-410a-9d83-38664f9f397b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "300b231c-cd8f-4eba-8ef0-2856bcc16f6d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2710593a-ff75-48d0-8a29-a5be5f931f9a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "adda2166-1a52-4a56-a26c-a3ebd87831b4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7c7c4468-93e6-4665-9654-55ea48205832",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "55365416-db85-4119-985e-2b89f6afae72",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9098f555-3b24-4f76-b331-596251748815",
                "ordinal": 3
              }
            ],
            "lineageTag": "d9c26fe5-db77-49b5-b642-51d130206866"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "1a78b73e-361b-499e-b8d8-4990b3c84d61",
        "partitions": [
          {
            "name": "DateTableTemplate_2b72d69d-3aac-4def-83df-5374ee625918",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ea87b48e-cf73-4ee2-9724-0be41bbea877",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "44ef2f80-36e3-47d3-a1d3-5dee7d3fea9e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4dfff359-8d14-48c8-9ef8-171ac0c97498",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b4b5c38e-0b69-4d94-a997-cb32a51c3193",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "27b755ec-dd75-48bb-ae31-148f3b464461",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "087a98a5-fe50-4fd0-87c3-3179331b4721",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0abb4388-ad5d-46be-a6f1-17e096ae26b7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6ec77dd6-b08f-40ab-ad47-c1140439f7a8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d3d2405b-2753-49a4-935e-fba2a6ee728e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5d75c58e-6cc7-41c7-8639-8ba214a3a267",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6f047375-895e-4e4e-8c55-f6b30cc5212a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e6cf32e1-172e-470f-80af-b41a18b1a13e",
                "ordinal": 3
              }
            ],
            "lineageTag": "b5480ccb-9557-4191-8b76-fa3f24f7c1d3"
          }
        ],
        "isHidden": true,
        "lineageTag": "f201ca4f-e2e0-465a-8fa0-94e9fdb12559",
        "partitions": [
          {
            "name": "LocalDateTable_ea87b48e-cf73-4ee2-9724-0be41bbea877",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Ryan''s Sheet - Single Selection'[Year end])), 1, 1), Date(Year(MAX('Ryan''s Sheet - Single Selection'[Year end])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_9dfae6c2-a5f2-45ab-9eed-a8044e1032ba",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2e03ca97-78f6-455b-a185-c7be6b7ca7aa",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "abaac739-058f-4a09-8fe6-f63fee839998",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7e4caf8f-ef6a-4bef-a26b-04d157377ffd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "37884f87-abee-4b9c-9ad9-4be305b9b8ce",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5514e4e9-4c0d-42f2-b96a-fbd556def656",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "16b1aabf-ac1d-42ab-8e7f-82595bb319e8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cec0b353-744e-4020-a685-ff2c491c5674",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "de9b6e07-4eb2-4914-86dc-1f4f69eb276c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "74b9a56b-951b-46f7-b436-bec0ae083a2f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6714ac6f-1626-4295-b26f-933adddf08cf",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e47001ea-4b1c-4842-8a6f-4539acdc1931",
                "ordinal": 3
              }
            ],
            "lineageTag": "9c2ae61e-978e-4bd2-80f3-d31b405a4630"
          }
        ],
        "isHidden": true,
        "lineageTag": "ddb3a216-a0b0-4c84-8eee-aa07e43262ed",
        "partitions": [
          {
            "name": "LocalDateTable_9dfae6c2-a5f2-45ab-9eed-a8044e1032ba",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Ryan''s Sheet - Single Selection'[Year end - Copy])), 1, 1), Date(Year(MAX('Ryan''s Sheet - Single Selection'[Year end - Copy])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Ryan's Sheet - Comparision",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "RowNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "168242c6-6685-4bfe-873b-fcb58e000e76",
            "sourceColumn": "RowNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "Club name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bd50b7a-ffb7-4f75-bbcd-b2a00ab739e3",
            "sourceColumn": "Club name",
            "summarizeBy": "none"
          },
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36374f9a-c91e-466e-8a63-8be325451ac4",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Zip Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2932cabe-77fd-417d-b014-7839e4b3a6e0",
            "sourceColumn": "Zip Code",
            "summarizeBy": "count"
          },
          {
            "name": "Year end",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "734e8913-186e-4968-8aac-d4821ab31767",
            "sourceColumn": "Year end",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c676eb26-1023-4985-ab89-14db214ea3de"
                },
                "isDefault": true,
                "relationship": "166e3c1e-c455-493d-87dd-560dc9da4a2a"
              }
            ]
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a980564-c2bd-43a5-afb3-d5d52dca12eb",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Mandatory Membership",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a7f4169-b6d4-46b2-87e3-11168589afcb",
            "sourceColumn": "Mandatory Membership",
            "summarizeBy": "none"
          },
          {
            "name": "Full Member Equivalents (FME)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ee544f1a-5cb9-496e-a839-d40e5826fa0c",
            "sourceColumn": "Full Member Equivalents (FME)",
            "summarizeBy": "sum"
          },
          {
            "name": "Refundable Equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d05b2313-b8b6-4b04-baaa-4ed2ab428758",
            "sourceColumn": "Refundable Equity",
            "summarizeBy": "sum"
          },
          {
            "name": "Non-refundable equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "bac0b692-f531-4d31-b171-88328d185a76",
            "sourceColumn": "Non-refundable equity",
            "summarizeBy": "sum"
          },
          {
            "name": "Total equity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50e7d7b8-38ec-44a5-b4af-d2022191d66b",
            "sourceColumn": "Total equity",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Rate - Current Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "b95e4eef-1c99-4549-acf7-5c0b9ac7c6bf",
            "sourceColumn": "Dues Rate - Current Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Rate - Audit Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f316dc5c-a84b-4587-a7f4-c1e9e6424d5a",
            "sourceColumn": "Dues Rate - Audit Year",
            "summarizeBy": "sum"
          },
          {
            "name": "General Capital Assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b6385e6-a75e-44c8-bd4a-bc58d30ecf1b",
            "sourceColumn": "General Capital Assessment",
            "summarizeBy": "none"
          },
          {
            "name": "Capital Assessment Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e7b636a8-0815-4076-b302-cae0265b2cc8",
            "sourceColumn": "Capital Assessment Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1bf37ebb-d890-4132-afb9-c1d9fdcc7cf4",
            "sourceColumn": "Operating Assessment",
            "summarizeBy": "none"
          },
          {
            "name": "Operating Assessment Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "32568180-31ee-43e0-a392-713c09a835ab",
            "sourceColumn": "Operating Assessment Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Other Capital",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07c3d8d2-657f-4e2f-ad4e-cb8dfecc185f",
            "sourceColumn": "Other Capital",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of general capital assessment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b9067c5-c2b6-4937-a431-540a3d97160e",
            "sourceColumn": "Amount of general capital assessment",
            "summarizeBy": "none"
          },
          {
            "name": "Major renovation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed05cdb8-9119-4a27-b485-6f68defcce3b",
            "sourceColumn": "Major renovation",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation - 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aaeec6e8-4c21-4ffd-bd49-6434fefc8a53",
            "sourceColumn": "Type of Renovation - 1",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation - 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36e5fd2e-2493-45d7-8ad3-79d6c55def46",
            "sourceColumn": "Type of Renovation - 2",
            "summarizeBy": "none"
          },
          {
            "name": "Type of Renovation - 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f609ac86-6db6-4992-bc1b-777524993c95",
            "sourceColumn": "Type of Renovation - 3",
            "summarizeBy": "none"
          },
          {
            "name": "Budgeted Major Capital Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcaad2ff-076f-4e68-95b2-635b19144f95",
            "sourceColumn": "Budgeted Major Capital Project",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of Budgeted Major Capital Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "2c42c791-910a-423e-958a-a28d29592f71",
            "sourceColumn": "Amount of Budgeted Major Capital Project",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount of Budgeted Other Capital Projects",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "91a93bdf-1912-46fe-bbd7-bfbe30071baa",
            "sourceColumn": "Amount of Budgeted Other Capital Projects",
            "summarizeBy": "sum"
          },
          {
            "name": "Ending PPE, net",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8da95506-5550-4686-8afd-4ea1f08516cb",
            "sourceColumn": "Ending PPE, net",
            "summarizeBy": "sum"
          },
          {
            "name": "Capital Expenditures (PP&E)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c30b48c8-68a1-4882-a27d-8b591e031e19",
            "sourceColumn": "Capital Expenditures (PP&E)",
            "summarizeBy": "sum"
          },
          {
            "name": "Depreciation Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec4cb0d4-e6d3-40a8-ada8-deb19760bd3e",
            "sourceColumn": "Depreciation Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Third Party Debt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b072f8a-8806-4e15-b44a-7b5ba698b6be",
            "sourceColumn": "Third Party Debt",
            "summarizeBy": "none"
          },
          {
            "name": "Total Third Party Debt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b54c1a68-df66-44db-af81-35b97e9cfa5a",
            "sourceColumn": "Total Third Party Debt",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Assets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "78c64fd7-a051-43a3-8484-e18987b4874b",
            "sourceColumn": "Current Assets",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Liabilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "68216a59-a832-412c-9196-01437006c1f1",
            "sourceColumn": "Current Liabilities",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Total Liabilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "80befce9-fca3-454f-9993-efe16f207dc6",
            "sourceColumn": "Total Total Liabilities",
            "summarizeBy": "sum"
          },
          {
            "name": "Ending Net Assets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "1f4e3b0c-2242-4ec8-be39-0ecb970d5707",
            "sourceColumn": "Ending Net Assets",
            "summarizeBy": "sum"
          },
          {
            "name": "Golf Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac5757df-7642-4cba-9cd5-30c4e75ce1f6",
            "sourceColumn": "Golf Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Tennis Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "584c6057-fbd2-414e-8eac-3151a6a1e313",
            "sourceColumn": "Tennis Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Pro Shop Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "11239067-6bce-402e-8fe1-daf843686245",
            "sourceColumn": "Pro Shop Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Other Sports Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7ef67260-6958-45d0-9818-ce30196614e9",
            "sourceColumn": "Other Sports Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Dues Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "064cfba7-52a8-41b5-96d2-0f6365e3060a",
            "sourceColumn": "Dues Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Assessments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "72dcdea1-a84e-4f4c-942e-0746069993d3",
            "sourceColumn": "Operating Assessments",
            "summarizeBy": "sum"
          },
          {
            "name": "Non-Owner Initiation fees",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "16ede91c-ffad-453f-9717-8e9285f9381f",
            "sourceColumn": "Non-Owner Initiation fees",
            "summarizeBy": "sum"
          },
          {
            "name": "Food Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "950b31d0-1b29-4e9d-9ae7-bfba793d24f1",
            "sourceColumn": "Food Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Beverage Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f8eb8b08-6dc4-4fbc-985e-05ef62e2f94e",
            "sourceColumn": "Beverage Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "All Other F&B Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "20805b92-fe4e-4744-8cab-200f6d6ddb81",
            "sourceColumn": "All Other F&B Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Payroll and PTEB Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0ce3d41-ddb4-4457-b2fa-a0d67a7e596a",
            "sourceColumn": "Payroll and PTEB Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of sales - F&B",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0bc3430f-a654-4aaf-8b7b-13211a60546c",
            "sourceColumn": "Cost of sales - F&B",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of Sales - Pro shop",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3368dd5-465d-487c-879e-970e121c4115",
            "sourceColumn": "Cost of Sales - Pro shop",
            "summarizeBy": "sum"
          },
          {
            "name": "Operating Expenses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cab5a2ac-cad2-4dce-9e4b-a4412f02820c",
            "sourceColumn": "Operating Expenses",
            "summarizeBy": "sum"
          },
          {
            "name": "Property Taxes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bf9094b9-952f-445e-86e2-4b372826ccbd",
            "sourceColumn": "Property Taxes",
            "summarizeBy": "sum"
          },
          {
            "name": "Insurance Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b251c161-d0b9-4bd4-aa60-dcbae4705adc",
            "sourceColumn": "Insurance Expense",
            "summarizeBy": "sum"
          },
          {
            "name": "Total employees in season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e89203d9-c742-4e49-960c-b7b85503d6d7",
            "sourceColumn": "Total employees in season",
            "summarizeBy": "sum"
          },
          {
            "name": "Use of Organized Foreign Labor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb10a85e-3969-49c0-8342-ea61989aeca3",
            "sourceColumn": "Use of Organized Foreign Labor",
            "summarizeBy": "none"
          },
          {
            "name": "# Foreign Staff hired in yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aab293b7-cce3-4d6a-9cc3-b804a476c219",
            "sourceColumn": "# Foreign Staff hired in yr",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Foreign Labor Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0e51a2eb-400f-48f2-9d13-ee54991b0d5e",
            "sourceColumn": "Total Foreign Labor Costs",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Health Insurance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62d2309d-a713-468b-b716-69001e9084e4",
            "sourceColumn": "Increase in Health Insurance",
            "summarizeBy": "none"
          },
          {
            "name": "% inc. in Health Insurance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4fa57c78-43d1-4130-b66d-919fe1d35923",
            "sourceColumn": "% inc. in Health Insurance",
            "summarizeBy": "sum"
          },
          {
            "name": "Food and Beverage Minimum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bb8b376-ac46-44ca-bd3b-df03e34a2d09",
            "sourceColumn": "Food and Beverage Minimum",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of F&B Minimum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "00c77af5-71d9-4fc8-96bb-c2e4e483bdf4",
            "sourceColumn": "Amount of F&B Minimum",
            "summarizeBy": "sum"
          },
          {
            "name": "Automatic F&B Gratuity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6179290-12bf-4958-a147-93beb5fedf4e",
            "sourceColumn": "Automatic F&B Gratuity",
            "summarizeBy": "none"
          },
          {
            "name": "% amt of F&B gratuity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "85461491-369d-41bf-b1a0-9146d6614ccf",
            "sourceColumn": "% amt of F&B gratuity",
            "summarizeBy": "sum"
          },
          {
            "name": "Mandatory Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cce0289-3d01-48d2-9e66-df2fafd795b7",
            "sourceColumn": "Mandatory Service Charge",
            "summarizeBy": "none"
          },
          {
            "name": "Amount of Monthly Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f1f14e16-137f-4c02-b4d7-a3900e8889cb",
            "sourceColumn": "Amount of Monthly Service Charge",
            "summarizeBy": "sum"
          },
          {
            "name": "# full service kitchens",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "07311aec-77e6-4c9e-8149-1d221a865e24",
            "sourceColumn": "# full service kitchens",
            "summarizeBy": "sum"
          },
          {
            "name": "# covers (include function / banquet)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6c810db-fa82-41de-8764-6374b6a8b1ca",
            "sourceColumn": "# covers (include function / banquet)",
            "summarizeBy": "sum"
          },
          {
            "name": "#  function / banquet covers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a2144c3a-7d89-4bf0-8268-123e2c94095e",
            "sourceColumn": "#  function / banquet covers",
            "summarizeBy": "sum"
          },
          {
            "name": "Compensation Method for F&B Staff",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6647dbdd-6b94-440b-8d7f-952e19d31894",
            "sourceColumn": "Compensation Method for F&B Staff",
            "summarizeBy": "none"
          },
          {
            "name": "Food sales (exc Mins)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ae6b37e-f53a-499c-bbbb-e3811563dac0",
            "sourceColumn": "Food sales (exc Mins)",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of food sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "85d97324-2e71-4558-8271-c6270f648bc0",
            "sourceColumn": "Cost of food sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Beverage sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e5bd311e-bafa-4711-a517-812fd0d7b80d",
            "sourceColumn": "Beverage sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost of beverage sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7478b78-f70f-45f1-b0d3-72418b2533d0",
            "sourceColumn": "Cost of beverage sales",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Salaries and wages expense (EXC credit for M",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a786137c-b027-46f1-b4bb-9ad33a0197bd",
            "sourceColumn": "F&B - Salaries and wages expense (EXC credit for M",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Less credit = 20% of F&B sales (only applies",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d00ccc09-436a-4827-8dd3-0b40e16b5e64",
            "sourceColumn": "F&B - Less credit = 20% of F&B sales (only applies",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Payroll taxes and benefits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d07401a5-e149-49e6-9bd7-2ce93be3507e",
            "sourceColumn": "F&B - Payroll taxes and benefits",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Employees' meals",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "adf0dc1c-f74c-4046-9498-402c27ef6a61",
            "sourceColumn": "F&B - Employees' meals",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Laundry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49e43527-1c13-479b-bed4-4a4e7074a3fb",
            "sourceColumn": "F&B - Laundry",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Linen, china, glass, silver",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c5c9fc74-d11b-40f1-8ae2-01064daa475a",
            "sourceColumn": "F&B - Linen, china, glass, silver",
            "summarizeBy": "sum"
          },
          {
            "name": "F&B - Other expenses (excluding entertainment, val",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d051a561-bdc8-470b-b075-fc80a3c2845a",
            "sourceColumn": "F&B - Other expenses (excluding entertainment, val",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Menu Prices",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de0a1f79-e19e-4d24-b9c0-d9225c47ebb3",
            "sourceColumn": "Increase in Menu Prices",
            "summarizeBy": "none"
          },
          {
            "name": "Av % inc Menu Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4452b561-f440-406c-9d25-5d50803ad764",
            "sourceColumn": "Av % inc Menu Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Increase in Beverage Prices",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86ddac47-a2b6-416b-ad48-eed67857b4ee",
            "sourceColumn": "Increase in Beverage Prices",
            "summarizeBy": "none"
          },
          {
            "name": "Av % inc Bev Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c3aacd4b-6a7f-420b-bef2-d55c2659ac4c",
            "sourceColumn": "Av % inc Bev Price",
            "summarizeBy": "sum"
          },
          {
            "name": "# of holes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7cc85b8d-714d-4630-9b31-cfd99871803c",
            "sourceColumn": "# of holes",
            "summarizeBy": "sum"
          },
          {
            "name": "Maintained golf acreage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "868e61ad-baba-4739-9ae9-ef716b03e149",
            "sourceColumn": "Maintained golf acreage",
            "summarizeBy": "sum"
          },
          {
            "name": "Rounds per year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "a0aea185-2900-4a30-9cc1-e184f0fb4967",
            "sourceColumn": "Rounds per year",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - Salaries and wages",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "244b930c-61f8-483c-954d-d93ebd4fbce7",
            "sourceColumn": "GCM - Salaries and wages",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - Payroll taxes and benefits",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cefcc6d8-b99a-41ea-8fe8-bdd489ca8024",
            "sourceColumn": "GCM - Payroll taxes and benefits",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - Course supplies and contracts (includes gaso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6766b87d-4106-4976-9755-ae394560e510",
            "sourceColumn": "GCM - Course supplies and contracts (includes gaso",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - Repairs & mtce (includes tree trimming, lake",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "201c2f18-f949-4dff-86a0-e0c87b08cef2",
            "sourceColumn": "GCM - Repairs & mtce (includes tree trimming, lake",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - Leased equipment expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "08d7f08e-4169-4e9f-8975-411e4c8dd902",
            "sourceColumn": "GCM - Leased equipment expense",
            "summarizeBy": "sum"
          },
          {
            "name": "GCM - All other expenses (including utilities)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "40aacba5-f400-4aeb-92f1-c47d3d2954ed",
            "sourceColumn": "GCM - All other expenses (including utilities)",
            "summarizeBy": "sum"
          },
          {
            "name": "Year end - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d19074e0-8e98-4934-a6dd-4c1c19871c7b",
            "sourceColumn": "Year end - Copy",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8e9b3a54-d9ce-428d-b308-c3026abaf5d4"
                },
                "isDefault": true,
                "relationship": "26569726-066a-40eb-a93e-61b6c8f5de88"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb94d5ff-240d-46f2-925f-f72ac45dde9c",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Total Membership Cost2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "'Ryan''s Sheet - Comparision'[Dues Rate - Audit Year] + 'Ryan''s Sheet - Comparision'[Capital Assessment Amount] + 'Ryan''s Sheet - Comparision'[Operating Assessment Amount] + 'Ryan''s Sheet - Comparision'[Amount of F&B Minimum] + 'Ryan''s Sheet - Comparision'[Amount of Monthly Service Charge]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "925b34ce-7d2f-4311-bd51-458864806108",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Positive Working Capital2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "    IF(",
              "        ('Ryan''s Sheet - Comparision'[Current Assets] - 'Ryan''s Sheet - Comparision'[Current Liabilities]) > 0,",
              "        1,",
              "        0",
              "    )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isDataTypeInferred": true,
            "lineageTag": "3b7ba329-f8b9-48d3-bd2d-eda696f2104c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Increasing Dues2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "    IF(",
              "        'Ryan''s Sheet - Comparision'[Dues Rate - Current Year] > 'Ryan''s Sheet - Comparision'[Dues Rate - Audit Year],",
              "        1,",
              "        0",
              "    )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "isDataTypeInferred": true,
            "lineageTag": "c9db4295-5b18-48cd-b883-45b4a43c90f8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Sports Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Comparision'[Golf Revenue] + 'Ryan''s Sheet - Comparision'[Tennis Revenue] + 'Ryan''s Sheet - Comparision'[Other Sports Revenue] + 'Ryan''s Sheet - Comparision'[Pro Shop Sales]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "a391a627-5b48-4b5e-acd8-1acfdfa0665e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Rev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Comparision'[Sports Revenue] + 'Ryan''s Sheet - Comparision'[Dues Revenue] + 'Ryan''s Sheet - Comparision'[Food Revenue] + 'Ryan''s Sheet - Comparision'[Beverage Revenue] + 'Ryan''s Sheet - Comparision'[All Other F&B Revenue]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "4366d660-e475-4feb-81f0-ba7bb991e495",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Operating Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Comparision'[Operating Expenses] + 'Ryan''s Sheet - Comparision'[Cost of Sales - Pro shop]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a101f767-5a1b-46dc-bd3d-0aff3fa7ce10",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Cost of Sales F&B",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Comparision'[Cost of food sold] + 'Ryan''s Sheet - Comparision'[Cost of beverage sales]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "46eabdbb-129b-47b3-98cd-90f11a2c4f47",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Operating Expense2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Comparision'[Operating Expenses] + 'Ryan''s Sheet - Comparision'[Cost of Sales - Pro shop]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "5ca13645-15ab-4741-915f-ed9dd66ed58c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Tax & Insurance Expense",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Comparision'[Property Taxes] + 'Ryan''s Sheet - Comparision'[Insurance Expense]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0be2de9e-d4ff-4724-a986-6935d472d41b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Total Exp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Comparision'[Payroll and PTEB Expense] + 'Ryan''s Sheet - Comparision'[Cost of beverage sales] + 'Ryan''s Sheet - Comparision'[Operating Expenses] + 'Ryan''s Sheet - Comparision'[Cost of food sold] + 'Ryan''s Sheet - Comparision'[Cost of Sales - Pro shop] + 'Ryan''s Sheet - Comparision'[Insurance Expense] + 'Ryan''s Sheet - Comparision'[Property Taxes]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "fa6a8219-a442-44f2-bc74-f512e664bda3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Food & Beverage Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Comparision'[Food Revenue] + 'Ryan''s Sheet - Comparision'[Beverage Revenue]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "0bfaff18-af1b-4811-a188-f9c29ce3aaed",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "GCM Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Ryan''s Sheet - Comparision'[GCM - All other expenses (including utilities)] + 'Ryan''s Sheet - Comparision'[GCM - Course supplies and contracts (includes gaso] + 'Ryan''s Sheet - Comparision'[GCM - Leased equipment expense] + 'Ryan''s Sheet - Comparision'[GCM - Payroll taxes and benefits] + 'Ryan''s Sheet - Comparision'[GCM - Repairs & mtce (includes tree trimming, lake] + 'Ryan''s Sheet - Comparision'[GCM - Salaries and wages]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "4cfdf6a5-e3e3-4fd0-9850-4d017a405ca4",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Minimums and Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Ryan''s Sheet - Comparision'[Food and Beverage Minimum] = \"Yes\" && ",
              "    'Ryan''s Sheet - Comparision'[Mandatory Service Charge]= \"Yes\", ",
              "    \"Yes\", ",
              "    \"No\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "74af3b63-5940-4854-812d-b52d2c694f0a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Minimums and Gratuity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Ryan''s Sheet - Comparision'[Food and Beverage Minimum] = \"Yes\" && ",
              "    'Ryan''s Sheet - Comparision'[Automatic F&B Gratuity] = \"Yes\", ",
              "    \"Yes\", ",
              "    \"No\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2347aae7-736e-4fb2-971c-3c03fb6aa3db",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Minimums and Gratuity and Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Ryan''s Sheet - Comparision'[Food and Beverage Minimum] = \"Yes\" &&",
              "    'Ryan''s Sheet - Comparision'[Automatic F&B Gratuity] = \"Yes\" &&",
              "    'Ryan''s Sheet - Comparision'[Mandatory Service Charge]= \"Yes\", ",
              "    \"Yes\", ",
              "    \"No\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a17b15f8-976b-4848-8648-9570472701fa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Neither Gratuity or Service Charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    OR('Ryan''s Sheet - Comparision'[Automatic F&B Gratuity] = \"No\",",
              "    'Ryan''s Sheet - Comparision'[Mandatory Service Charge]= \"No\"), ",
              "    \"Yes\", ",
              "    \"No\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "0f39593e-b6c7-4bf0-b671-bee3b608fc01",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "F&B All other expenses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "'Ryan''s Sheet - Comparision'[F&B - Employees' meals] + 'Ryan''s Sheet - Comparision'[F&B - Laundry] + 'Ryan''s Sheet - Comparision'[F&B - Less credit = 20% of F&B sales (only applies] + 'Ryan''s Sheet - Comparision'[F&B - Linen, china, glass, silver] + 'Ryan''s Sheet - Comparision'[F&B - Other expenses (excluding entertainment, val]",
            "isDataTypeInferred": true,
            "lineageTag": "f7117ace-21e4-4a5e-bdfc-813c330a6826",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "F&B departmental subsidy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "('Ryan''s Sheet - Comparision'[Food Revenue] + 'Ryan''s Sheet - Comparision'[Beverage Revenue]) - ('Ryan''s Sheet - Comparision'[Cost of food sold] + 'Ryan''s Sheet - Comparision'[Cost of beverage sales] + 'Ryan''s Sheet - Comparision'[F&B - Salaries and wages expense (EXC credit for M] + 'Ryan''s Sheet - Comparision'[F&B - Less credit = 20% of F&B sales (only applies] + 'Ryan''s Sheet - Comparision'[F&B - Payroll taxes and benefits] + 'Ryan''s Sheet - Comparision'[F&B - Employees' meals] + 'Ryan''s Sheet - Comparision'[F&B - Laundry] + 'Ryan''s Sheet - Comparision'[F&B - Linen, china, glass, silver] + 'Ryan''s Sheet - Comparision'[F&B - Other expenses (excluding entertainment, val])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "2eab8c65-f115-49c5-83b6-db78fd5b00e8",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "3259444e-4296-4752-8a7f-ddc61c442542",
        "measures": [
          {
            "name": "Percentage of Mandatory Membership",
            "expression": [
              "",
              "VAR TotalClubs = DISTINCTCOUNT('Ryan''s Sheet - Comparision'[Club name])",
              "VAR MandatoryClubs = CALCULATE(",
              "    DISTINCTCOUNT('Ryan''s Sheet - Comparision'[Club name]), ",
              "    'Ryan''s Sheet - Comparision'[Mandatory Membership] = \"Yes\"",
              ")",
              "RETURN",
              "DIVIDE(MandatoryClubs, TotalClubs, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "83b14c2c-44b9-4b8a-896e-a41805073b88"
          },
          {
            "name": "Change in Dues2",
            "expression": "AVERAGE('Ryan''s Sheet - Comparision'[Dues Rate - Current Year]) - AVERAGE('Ryan''s Sheet - Comparision'[Dues Rate - Audit Year])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a1f121a0-062e-4d61-8132-880c3d8c4083"
          },
          {
            "name": "% Change in Dues2",
            "expression": "DIVIDE((AVERAGE('Ryan''s Sheet - Comparision'[Dues Rate - Current Year]) - AVERAGE('Ryan''s Sheet - Comparision'[Dues Rate - Audit Year])), AVERAGE('Ryan''s Sheet - Comparision'[Dues Rate - Audit Year]), 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d80e4053-878d-4e64-a923-af2e76de1d2a"
          },
          {
            "name": "Refundable Equity %2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Refundable Equity]), (SUM('Ryan''s Sheet - Comparision'[Refundable Equity]) + SUM('Ryan''s Sheet - Comparision'[Non-refundable equity])),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "64cf901d-d6e7-4110-9037-621c069c379e"
          },
          {
            "name": "Working Captial Ratio2",
            "expression": "DIVIDE(AVERAGE('Ryan''s Sheet - Comparision'[Current Assets]), AVERAGE('Ryan''s Sheet - Comparision'[Current Liabilities]),0)",
            "formatString": "0.00",
            "lineageTag": "861fdc58-7462-4b4d-89e8-626ff087443b"
          },
          {
            "name": "Debt / Equity Ratio2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE(AVERAGE('Ryan''s Sheet - Comparision'[Total Total Liabilities]), AVERAGE('Ryan''s Sheet - Comparision'[Ending Net Assets]),0)",
            "lineageTag": "39278d61-45f6-4783-a2fc-e55d9b489aed"
          },
          {
            "name": "Ending Net Assets per FME2",
            "expression": "DIVIDE(AVERAGE('Ryan''s Sheet - Comparision'[Ending Net Assets]), AVERAGE('Ryan''s Sheet - Comparision'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "b69ad940-fa1d-455f-8911-4a914ef771ac"
          },
          {
            "name": "Percentage of Clubs with Budgeted Major Capital Projects",
            "expression": [
              "",
              "VAR TotalClubs = DISTINCTCOUNT('Ryan''s Sheet - Comparision'[Club name])",
              "VAR BudgetedCapital = CALCULATE(",
              "    DISTINCTCOUNT('Ryan''s Sheet - Comparision'[Club name]), ",
              "    'Ryan''s Sheet - Comparision'[Budgeted Major Capital Project]= \"Yes\"",
              ")",
              "RETURN",
              "DIVIDE(BudgetedCapital, TotalClubs, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "51dbc205-5baf-4a0c-b1fe-da1e5b7ef0ad"
          },
          {
            "name": "Third Party Debt per FME2",
            "expression": "DIVIDE(AVERAGE('Ryan''s Sheet - Comparision'[Total Third Party Debt]), AVERAGE('Ryan''s Sheet - Comparision'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "3046e654-b596-494e-be03-9d37fe89da37"
          },
          {
            "name": "Dues Revenue%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Dues Revenue]), ((SUM('Ryan''s Sheet - Comparision'[Dues Revenue]) + SUM('Ryan''s Sheet - Comparision'[Food Revenue]) + SUM('Ryan''s Sheet - Comparision'[Beverage Revenue]) + SUM('Ryan''s Sheet - Comparision'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Comparision'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0d5f76f7-b4d3-49ba-9509-95e9c73b3d98"
          },
          {
            "name": "Sports Revenue%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Sports Revenue]), ((SUM('Ryan''s Sheet - Comparision'[Dues Revenue]) + SUM('Ryan''s Sheet - Comparision'[Food Revenue]) + SUM('Ryan''s Sheet - Comparision'[Beverage Revenue]) + SUM('Ryan''s Sheet - Comparision'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Comparision'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "27f759ad-8964-424d-bb03-332397c5243d"
          },
          {
            "name": "Food Revenue%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Food Revenue]), ((SUM('Ryan''s Sheet - Comparision'[Dues Revenue]) + SUM('Ryan''s Sheet - Comparision'[Food Revenue]) + SUM('Ryan''s Sheet - Comparision'[Beverage Revenue]) + SUM('Ryan''s Sheet - Comparision'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Comparision'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "1243563f-89b5-4fa5-b5c1-c3ac560c751b"
          },
          {
            "name": "Beverage Revenue%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Beverage Revenue]), ((SUM('Ryan''s Sheet - Comparision'[Dues Revenue]) + SUM('Ryan''s Sheet - Comparision'[Food Revenue]) + SUM('Ryan''s Sheet - Comparision'[Beverage Revenue]) + SUM('Ryan''s Sheet - Comparision'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Comparision'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "6cbd4297-8d0a-459a-ba4d-09b3b457670f"
          },
          {
            "name": "Other Revenue%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[All Other F&B Revenue]), ((SUM('Ryan''s Sheet - Comparision'[Dues Revenue]) + SUM('Ryan''s Sheet - Comparision'[Food Revenue]) + SUM('Ryan''s Sheet - Comparision'[Beverage Revenue]) + SUM('Ryan''s Sheet - Comparision'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Comparision'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "6fabe301-4d2c-4f79-bd02-9a860b59a899"
          },
          {
            "name": "Payroll and Related%2",
            "expression": "DIVIDE(AVERAGE('Ryan''s Sheet - Comparision'[Payroll and PTEB Expense]), AVERAGE('Ryan''s Sheet - Comparision'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5e4ed1cb-c8dc-4eaf-b8e8-adb95c3f8d3b"
          },
          {
            "name": "Cost of Sales%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Cost of Sales F&B]), SUM('Ryan''s Sheet - Comparision'[Total Exp]),0)",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "53f2b003-5070-4b19-96c5-814c657b38a7"
          },
          {
            "name": "Operating Expense%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Operating Expenses]) + SUM('Ryan''s Sheet - Comparision'[Cost of Sales - Pro shop]), SUM('Ryan''s Sheet - Comparision'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f8393246-eff1-4e4f-a696-4107e9794228"
          },
          {
            "name": "Tax & Insurance Expense%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Property Taxes]) + SUM('Ryan''s Sheet - Comparision'[Insurance Expense]), SUM('Ryan''s Sheet - Comparision'[Total Exp]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5acd3d73-2297-43ed-945d-4d85e8ba959a"
          },
          {
            "name": "Payroll and Related Rev%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Payroll and PTEB Expense]), ((SUM('Ryan''s Sheet - Comparision'[Dues Revenue]) + SUM('Ryan''s Sheet - Comparision'[Food Revenue]) + SUM('Ryan''s Sheet - Comparision'[Beverage Revenue]) + SUM('Ryan''s Sheet - Comparision'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Comparision'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e2b513fa-b235-4583-9aea-8d27f73ee67b"
          },
          {
            "name": "Cost of Sales Rev%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Cost of Sales F&B]), ((SUM('Ryan''s Sheet - Comparision'[Dues Revenue]) + SUM('Ryan''s Sheet - Comparision'[Food Revenue]) + SUM('Ryan''s Sheet - Comparision'[Beverage Revenue]) + SUM('Ryan''s Sheet - Comparision'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Comparision'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b97f20ac-5d1a-4270-8d71-ab8ac6a5d9d0"
          },
          {
            "name": "Operating Expense Rev%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Operating Expenses]) + SUM('Ryan''s Sheet - Comparision'[Cost of Sales - Pro shop]), ((SUM('Ryan''s Sheet - Comparision'[Dues Revenue]) + SUM('Ryan''s Sheet - Comparision'[Food Revenue]) + SUM('Ryan''s Sheet - Comparision'[Beverage Revenue]) + SUM('Ryan''s Sheet - Comparision'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Comparision'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a0d3e06c-769c-4cc9-b341-3b76021ad47f"
          },
          {
            "name": "Tax & Insurance Expense Rev%2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Property Taxes]) + SUM('Ryan''s Sheet - Comparision'[Insurance Expense]), ((SUM('Ryan''s Sheet - Comparision'[Dues Revenue]) + SUM('Ryan''s Sheet - Comparision'[Food Revenue]) + SUM('Ryan''s Sheet - Comparision'[Beverage Revenue]) + SUM('Ryan''s Sheet - Comparision'[All Other F&B Revenue]) + SUM('Ryan''s Sheet - Comparision'[Sports Revenue]))),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "156c89f3-4060-42f4-9931-10c68cf59407"
          },
          {
            "name": "Total Expense as % of Total Revenue2",
            "expression": "[Payroll and Related Rev%2] + [Cost of Sales Rev%2] + [Operating Expense Rev%2] + [Tax & Insurance Expense Rev%2]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ef342598-b397-4cbf-913d-cd419b4b1f63"
          },
          {
            "name": "Surplus (Deficit)2",
            "expression": "AVERAGE('Ryan''s Sheet - Comparision'[Total Rev]) - AVERAGE('Ryan''s Sheet - Comparision'[Total Exp])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f9dc8128-de8b-4881-b1b1-225142553a7e"
          },
          {
            "name": "Payroll and Related per FME2",
            "expression": "DIVIDE(AVERAGE('Ryan''s Sheet - Comparision'[Payroll and PTEB Expense]), AVERAGE('Ryan''s Sheet - Comparision'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "f253aeb0-a1c9-422e-9159-950561e0ac1f"
          },
          {
            "name": "FME to Employee2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Full Member Equivalents (FME)]), SUM('Ryan''s Sheet - Comparision'[Total employees in season]),0)",
            "lineageTag": "91d9e0e7-2196-4b0b-8bfc-dd2c8427ed66"
          },
          {
            "name": "Food Sales2",
            "expression": "DIVIDE(SUM('Ryan''s Sheet - Comparision'[Food Revenue]), SUM('Ryan''s Sheet - Comparision'[Food Revenue]),0) ",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ce14086f-384f-4944-90bf-dd34eea7a131"
          },
          {
            "name": "Food Gross Profit2",
            "expression": "DIVIDE(Average('Ryan''s Sheet - Comparision'[Food Revenue]) - Average('Ryan''s Sheet - Comparision'[Cost of food sold]) - Average('Ryan''s Sheet - Comparision'[F&B - Employees' meals]), Average('Ryan''s Sheet - Comparision'[Food Revenue]),0) ",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "90229042-eff3-4034-8b00-7e2199f01e4c"
          },
          {
            "name": "Food Sold Cost2",
            "expression": "1 - [Food Gross Profit2]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "bebf5c24-f464-4053-aeb0-3daaaddbfcde"
          },
          {
            "name": "Beverage Sales Calc2",
            "expression": "DIVIDE(Average('Ryan''s Sheet - Comparision'[Beverage Revenue]), average('Ryan''s Sheet - Comparision'[Beverage Revenue]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b44c0805-9a5b-4e23-a660-03b7d8cfc82a"
          },
          {
            "name": "Beverage Gross Profit2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[Beverage Revenue]) - average('Ryan''s Sheet - Comparision'[Cost of beverage sales]), average('Ryan''s Sheet - Comparision'[Beverage Revenue]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ab78bdc9-b759-4922-9a0d-63a6f797c721"
          },
          {
            "name": "Cost of Beverage Sold2",
            "expression": "1 - [Beverage Gross Profit2]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "86ded430-9857-4525-a2ca-60772d9964e3"
          },
          {
            "name": "Food & Beverage Sales2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[Food & Beverage Revenue]), average('Ryan''s Sheet - Comparision'[Food & Beverage Revenue]),0) ",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f2c76333-18f6-48da-acae-4c6dcf7e140f"
          },
          {
            "name": "Food & Beverage Gross Profit2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[Food & Beverage Revenue]) - average('Ryan''s Sheet - Comparision'[Cost of Sales F&B]), average('Ryan''s Sheet - Comparision'[Food & Beverage Revenue]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c855ba28-1874-4f2e-8d45-3a3d8fa4d8e5"
          },
          {
            "name": "Cost of Food & Beverage Sold2",
            "expression": "1 - [Food & Beverage Gross Profit2]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c725bfb5-07da-476b-b88f-e9274a258c98"
          },
          {
            "name": "Cost per Hole2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[GCM Total]), average('Ryan''s Sheet - Comparision'[# of holes]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "eb02b0b2-5887-4d61-81de-ec2517e1fe7b"
          },
          {
            "name": "Cost per Round2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[GCM Total]), average('Ryan''s Sheet - Comparision'[Rounds per year]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "5eac45a9-dbe0-4b80-bc64-77135d4d5524"
          },
          {
            "name": "Cost per Acre2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[GCM Total]), average('Ryan''s Sheet - Comparision'[Maintained golf acreage]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d8c0ab81-efd9-4495-9f82-6404f6c4d04a"
          },
          {
            "name": "Salaries and Wage per 18 v2",
            "expression": [
              "",
              "    DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - Salaries and wages]), average('Ryan''s Sheet - Comparision'[# of holes]),0) *",
              "    DIVIDE(18, average('Ryan''s Sheet - Comparision'[# of holes]),0)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7383e31a-520f-41ef-99d3-d408d18fa7c5"
          },
          {
            "name": "Payroll Taxes and Benefits per 18 v2",
            "expression": [
              "",
              "    DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - Payroll taxes and benefits]), average('Ryan''s Sheet - Comparision'[# of holes]),0) *",
              "    DIVIDE(18, average('Ryan''s Sheet - Comparision'[# of holes]),0)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "67019f1c-b17b-476f-840c-6442ab316fdc"
          },
          {
            "name": "Course Supplies per 18 v2",
            "expression": [
              "",
              "    DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - Course supplies and contracts (includes gaso]), average('Ryan''s Sheet - Comparision'[# of holes]),0) *",
              "    DIVIDE(18, average('Ryan''s Sheet - Comparision'[# of holes]),0)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ee9ffc34-6a21-4ac0-a131-23eaddd7d504"
          },
          {
            "name": "Repairs per 18 v2",
            "expression": [
              "",
              "    DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - Repairs & mtce (includes tree trimming, lake]), average('Ryan''s Sheet - Comparision'[# of holes]),0) *",
              "    DIVIDE(18, average('Ryan''s Sheet - Comparision'[# of holes]),0)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7178f19f-06f1-47f5-af88-cb075a90a8ab"
          },
          {
            "name": "Leased Equipment per 18 v2",
            "expression": [
              "",
              "    DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - Leased equipment expense]), average('Ryan''s Sheet - Comparision'[# of holes]),0) *",
              "    DIVIDE(18, average('Ryan''s Sheet - Comparision'[# of holes]),0)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "de202ec6-8075-4dd0-ab7a-ca7fb4606db3"
          },
          {
            "name": "All Other Expenses per 18 v2",
            "expression": [
              "",
              "    DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - All other expenses (including utilities)]), average('Ryan''s Sheet - Comparision'[# of holes]),0) *",
              "    DIVIDE(18, average('Ryan''s Sheet - Comparision'[# of holes]),0)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "235979ea-c8f2-4001-8322-30ffb9bf8bed"
          },
          {
            "name": "Total Expenses per 18 v2",
            "expression": [
              "",
              "    DIVIDE(average('Ryan''s Sheet - Comparision'[GCM Total]), average('Ryan''s Sheet - Comparision'[# of holes]),0) *",
              "    DIVIDE(18, average('Ryan''s Sheet - Comparision'[# of holes]),0)"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "d5dd6b4b-6ee5-4256-bdcb-1a098ea03114"
          },
          {
            "name": "Total Expenses per 18 Holes v2",
            "expression": "[Total Expenses per 18 v2] * 18",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e14a65b1-f07e-4730-b239-390c687199d5"
          },
          {
            "name": "Salaries and Wages %2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - Salaries and wages]), average('Ryan''s Sheet - Comparision'[GCM Total]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dd0b9874-d5a6-4a5e-a833-e25210122598"
          },
          {
            "name": "Payroll Taxes and Employee Benefits %2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - Payroll taxes and benefits]), average('Ryan''s Sheet - Comparision'[GCM Total]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4919210d-670f-4f3b-b582-3c840476ae3d"
          },
          {
            "name": "Course Supplies %2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - Course supplies and contracts (includes gaso]), average('Ryan''s Sheet - Comparision'[GCM Total]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f530fe24-901a-4861-8f25-fe1210dfb68f"
          },
          {
            "name": "Repairs to Equipment %2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - Repairs & mtce (includes tree trimming, lake]), average('Ryan''s Sheet - Comparision'[GCM Total]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c2ea7454-aaf5-4afb-8418-7d210a8749bf"
          },
          {
            "name": "Leased Equipment %2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - Leased equipment expense]), average('Ryan''s Sheet - Comparision'[GCM Total]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "84afa270-d6c6-4646-808e-80df686e12fd"
          },
          {
            "name": "All Other Expenses %2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[GCM - All other expenses (including utilities)]), average('Ryan''s Sheet - Comparision'[GCM Total]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "fd4d7f8a-1721-4a6d-82ca-d5849ccaba39"
          },
          {
            "name": "GCM Costs as % of Dues v2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[GCM Total]), average('Ryan''s Sheet - Comparision'[Dues Revenue]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f398cf59-f52d-4ff7-a010-342d3ad9557b"
          },
          {
            "name": "GCM Costs as % of Operating Costs v2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[GCM Total]), average('Ryan''s Sheet - Comparision'[Total Exp]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b0e8036c-d109-4269-aa61-2d0f092f7fb1"
          },
          {
            "name": "Operating Assessment %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Operating Assessment] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "deaa1f70-20b9-45e9-a518-3ff0c833e6f0"
          },
          {
            "name": "Annual Capital Assessment %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[General Capital Assessment] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "8f7088dc-4dc9-4683-bf9d-f9e037c670db"
          },
          {
            "name": "Other Capital/Renovation/Debt Assessment %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Other Capital] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "045c0c69-25f4-482c-aa74-82d843574401"
          },
          {
            "name": "Third Party Debt %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Third Party Debt] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9436396c-1773-4d63-adf6-6581013f2fee"
          },
          {
            "name": "Menu Price Increase %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Increase in Menu Prices] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "69f87f91-4633-4a52-b680-805bc86bd5ad"
          },
          {
            "name": "Beverage Price Increase %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Increase in Beverage Prices] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "29749374-a410-42f2-af0c-3c90ce4a65ff"
          },
          {
            "name": "Minimums %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Food and Beverage Minimum] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d1058449-faa6-48eb-82c4-9d0dfd6c776d"
          },
          {
            "name": "F&B Gratuity %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Automatic F&B Gratuity] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "211afa99-0512-4d8d-9acc-9a4dc74c478a"
          },
          {
            "name": "Mandatory Service Charge %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Mandatory Service Charge] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dd28945a-bf14-441d-8112-0071a82b8eb1"
          },
          {
            "name": "Minimums and Service Charge %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Minimums and Service Charge] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b9d2b2f9-feb5-4244-93b0-a23ea5d0d340"
          },
          {
            "name": "Minimums and Gratuity %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Minimums and Gratuity] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "lineageTag": "333f8661-b19c-49de-b96a-b0a707e2b3b9"
          },
          {
            "name": "Minimums and Gratuity and Service Charge %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Minimums and Gratuity and Service Charge] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "lineageTag": "be1373cb-2c49-4d67-8699-1f282aa35006"
          },
          {
            "name": "Neither Gratuity or Mandatory %",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(COUNTROWS('Ryan''s Sheet - Comparision'), 'Ryan''s Sheet - Comparision'[Neither Gratuity or Service Charge] = \"Yes\"),",
              "    COUNTROWS('Ryan''s Sheet - Comparision'),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "823bb5ec-bdd2-46fd-ae5b-df9ab7929160"
          },
          {
            "name": "Restaurant Sales per FME2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[Food Revenue]) + average('Ryan''s Sheet - Comparision'[Beverage Revenue]), average('Ryan''s Sheet - Comparision'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7f3bc21e-1cb2-47a9-93a2-17092c2484ad"
          },
          {
            "name": "Restaurant Salaries Compared to Revenue%2",
            "expression": [
              "DIVIDE(",
              "    average('Ryan''s Sheet - Comparision'[F&B - Salaries and wages expense (EXC credit for M]) + average('Ryan''s Sheet - Comparision'[F&B - Payroll taxes and benefits]), ",
              "    average('Ryan''s Sheet - Comparision'[Food Revenue]) + average('Ryan''s Sheet - Comparision'[Beverage Revenue]),",
              "    0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6d7d0001-2836-4e4a-a46b-0fae996110c8"
          },
          {
            "name": "Salaries and Wages % of Rev2",
            "expression": [
              "DIVIDE(",
              "    average('Ryan''s Sheet - Comparision'[F&B - Salaries and wages expense (EXC credit for M]), ",
              "    average('Ryan''s Sheet - Comparision'[Food Revenue]) + average('Ryan''s Sheet - Comparision'[Beverage Revenue]),",
              "    0)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e673acc5-2ac9-4f25-bec8-c80c8dbde184"
          },
          {
            "name": "Payroll Taxes % of Rev2",
            "expression": [
              "DIVIDE(",
              "    average('Ryan''s Sheet - Comparision'[F&B - Payroll taxes and benefits]), ",
              "    average('Ryan''s Sheet - Comparision'[Food Revenue]) + average('Ryan''s Sheet - Comparision'[Beverage Revenue]),",
              "    0)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d508d200-817d-40a0-b5e5-216bd23bbc7c"
          },
          {
            "name": "F&B All Other Expenses % of Rev2",
            "expression": [
              "DIVIDE(",
              "    average('Ryan''s Sheet - Comparision'[F&B All other expenses]), ",
              "    average('Ryan''s Sheet - Comparision'[Food Revenue]) + average('Ryan''s Sheet - Comparision'[Beverage Revenue]),",
              "    0)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f0e98f33-29eb-4960-9a47-96b91451c802"
          },
          {
            "name": "Total Department Expenses % of Rev%2",
            "expression": [
              "DIVIDE(",
              "    average('Ryan''s Sheet - Comparision'[F&B - Salaries and wages expense (EXC credit for M]) + average('Ryan''s Sheet - Comparision'[F&B - Payroll taxes and benefits]) + average('Ryan''s Sheet - Comparision'[F&B All other expenses]), ",
              "    average('Ryan''s Sheet - Comparision'[Food Revenue]) + average('Ryan''s Sheet - Comparision'[Beverage Revenue]),",
              "    0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "69641fcc-a1b3-4498-b9fb-cd30b35c8d07"
          },
          {
            "name": "F&B Gross Profit %2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    (",
              "        (average('Ryan''s Sheet - Comparision'[Beverage Revenue]) + average('Ryan''s Sheet - Comparision'[Food Revenue]))",
              "         - (average('Ryan''s Sheet - Comparision'[Cost of beverage sales]) + average('Ryan''s Sheet - Comparision'[Cost of food sold]))",
              "    ), ",
              "    (average('Ryan''s Sheet - Comparision'[Beverage Revenue]) + average('Ryan''s Sheet - Comparision'[Food Revenue])),",
              "    0",
              "    )"
            ],
            "lineageTag": "83011e5c-94de-4e35-badf-c492e48beccb"
          },
          {
            "name": "Departmental (subsidy) v2",
            "expression": "([F&B Gross Profit %2] - [Total Department Expenses % of Rev%2])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4e48d33c-c0aa-4dd7-aed7-01be7e80f7b7"
          },
          {
            "name": "Food Sales to Beverage Sales2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[Food Revenue]), average('Ryan''s Sheet - Comparision'[Beverage Revenue]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c7723991-8a6f-4ac6-bf00-9d19cae4b9bc"
          },
          {
            "name": "Subsidy per FME2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[F&B departmental subsidy]), average('Ryan''s Sheet - Comparision'[Full Member Equivalents (FME)]),0)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "42c1b913-5376-4cb7-a342-f31ac81ac5c4"
          },
          {
            "name": "F&B departmental subsidy: Total dues revenue2",
            "expression": "DIVIDE(ABS(average('Ryan''s Sheet - Comparision'[F&B departmental subsidy])), average('Ryan''s Sheet - Comparision'[Dues Revenue]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "017990ef-b4c2-427f-8b9e-d6fa2545327b"
          },
          {
            "name": "Food Revenue %2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[Food Revenue]), average('Ryan''s Sheet - Comparision'[Food & Beverage Revenue]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "421a74af-8985-4456-b845-0fcf2b109a00"
          },
          {
            "name": "Beverage Revenue %2",
            "expression": "DIVIDE(average('Ryan''s Sheet - Comparision'[Beverage Revenue]), average('Ryan''s Sheet - Comparision'[Food & Beverage Revenue]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "441ca84f-c191-4ecd-b357-aa054e1f2520"
          }
        ],
        "partitions": [
          {
            "name": "Ryan's Sheet - Comparision",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Smartsheet.Tables(),",
                "    #\"2391507492726660\" = Source{[Key=\"2391507492726660\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"2391507492726660\",{{\"RowNumber\", Int64.Type}, {\"Club name\", type text}, {\"Classification\", type text}, {\"Zip Code\", Int64.Type}, {\"Year end\", type date}, {\"Type\", type text}, {\"Mandatory Membership\", type text}, {\"Full Member Equivalents (FME)\", type number}, {\"Refundable Equity\", Int64.Type}, {\"Non-refundable equity\", Int64.Type}, {\"Total equity\", Int64.Type}, {\"Dues Rate - Current Year\", Int64.Type}, {\"Dues Rate - Audit Year\", type number}, {\"General Capital Assessment\", type text}, {\"Capital Assessment Amount\", Int64.Type}, {\"Operating Assessment\", type text}, {\"Operating Assessment Amount\", type any}, {\"Other Capital\", type text}, {\"Amount of general capital assessment\", type any}, {\"Major renovation\", type text}, {\"Type of Renovation - 1\", type text}, {\"Type of Renovation - 2\", type text}, {\"Type of Renovation - 3\", type text}, {\"Budgeted Major Capital Project\", type text}, {\"Amount of Budgeted Major Capital Project\", Int64.Type}, {\"Amount of Budgeted Other Capital Projects\", Int64.Type}, {\"Ending PPE, net\", Int64.Type}, {\"Capital Expenditures (PP&E)\", Int64.Type}, {\"Depreciation Expense\", Int64.Type}, {\"Third Party Debt\", type text}, {\"Total Third Party Debt\", Int64.Type}, {\"Current Assets\", Int64.Type}, {\"Current Liabilities\", Int64.Type}, {\"Total Total Liabilities\", Int64.Type}, {\"Ending Net Assets\", Int64.Type}, {\"Golf Revenue\", Int64.Type}, {\"Tennis Revenue\", Int64.Type}, {\"Pro Shop Sales\", Int64.Type}, {\"Other Sports Revenue\", Int64.Type}, {\"Dues Revenue\", Int64.Type}, {\"Operating Assessments\", Int64.Type}, {\"Non-Owner Initiation fees\", Int64.Type}, {\"Food Revenue\", Int64.Type}, {\"Beverage Revenue\", Int64.Type}, {\"All Other F&B Revenue\", Int64.Type}, {\"Payroll and PTEB Expense\", Int64.Type}, {\"Cost of sales - F&B\", Int64.Type}, {\"Cost of Sales - Pro shop\", Int64.Type}, {\"Operating Expenses\", Int64.Type}, {\"Property Taxes\", Int64.Type}, {\"Insurance Expense\", Int64.Type}, {\"Total employees in season\", type number}, {\"Use of Organized Foreign Labor\", type text}, {\"# Foreign Staff hired in yr\", Int64.Type}, {\"Total Foreign Labor Costs\", type number}, {\"Increase in Health Insurance\", type text}, {\"% inc. in Health Insurance\", type number}, {\"Food and Beverage Minimum\", type text}, {\"Amount of F&B Minimum\", Int64.Type}, {\"Automatic F&B Gratuity\", type text}, {\"% amt of F&B gratuity\", type number}, {\"Mandatory Service Charge\", type text}, {\"Amount of Monthly Service Charge\", type number}, {\"# full service kitchens\", Int64.Type}, {\"# covers (include function / banquet)\", Int64.Type}, {\"#  function / banquet covers\", Int64.Type}, {\"Compensation Method for F&B Staff\", type text}, {\"Food sales (exc Mins)\", Int64.Type}, {\"Cost of food sold\", Int64.Type}, {\"Beverage sales\", Int64.Type}, {\"Cost of beverage sales\", Int64.Type}, {\"F&B - Salaries and wages expense (EXC credit for M\", Int64.Type}, {\"F&B - Less credit = 20% of F&B sales (only applies\", type number}, {\"F&B - Payroll taxes and benefits\", Int64.Type}, {\"F&B - Employees' meals\", Int64.Type}, {\"F&B - Laundry\", Int64.Type}, {\"F&B - Linen, china, glass, silver\", Int64.Type}, {\"F&B - Other expenses (excluding entertainment, val\", Int64.Type}, {\"Increase in Menu Prices\", type text}, {\"Av % inc Menu Price\", type number}, {\"Increase in Beverage Prices\", type text}, {\"Av % inc Bev Price\", type number}, {\"# of holes\", Int64.Type}, {\"Maintained golf acreage\", type number}, {\"Rounds per year\", Int64.Type}, {\"GCM - Salaries and wages\", Int64.Type}, {\"GCM - Payroll taxes and benefits\", Int64.Type}, {\"GCM - Course supplies and contracts (includes gaso\", Int64.Type}, {\"GCM - Repairs & mtce (includes tree trimming, lake\", Int64.Type}, {\"GCM - Leased equipment expense\", Int64.Type}, {\"GCM - All other expenses (including utilities)\", Int64.Type}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"Year end\", \"Year end - Copy\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Duplicated Column\",{{\"Year end - Copy\", type date}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type1\", \"Year\", each Date.Year([#\"Year end - Copy\"]), Int64.Type),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Inserted Year\",{{\"Year\", type text}}),",
                "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Changed Type2\", {{\"Total equity\", 0}}),",
                "    #\"Replaced Errors1\" = Table.ReplaceErrorValues(#\"Replaced Errors\", {{\"Golf Revenue\", 0}}),",
                "    #\"Replaced Errors2\" = Table.ReplaceErrorValues(#\"Replaced Errors1\", {{\"Tennis Revenue\", 0}}),",
                "    #\"Replaced Errors3\" = Table.ReplaceErrorValues(#\"Replaced Errors2\", {{\"Pro Shop Sales\", 0}}),",
                "    #\"Replaced Errors4\" = Table.ReplaceErrorValues(#\"Replaced Errors3\", {{\"Other Sports Revenue\", 0}}),",
                "    #\"Replaced Errors5\" = Table.ReplaceErrorValues(#\"Replaced Errors4\", {{\"Dues Revenue\", 0}}),",
                "    #\"Replaced Errors6\" = Table.ReplaceErrorValues(#\"Replaced Errors5\", {{\"Operating Assessments\", 0}}),",
                "    #\"Replaced Errors7\" = Table.ReplaceErrorValues(#\"Replaced Errors6\", {{\"Non-Owner Initiation fees\", 0}}),",
                "    #\"Replaced Errors8\" = Table.ReplaceErrorValues(#\"Replaced Errors7\", {{\"Food Revenue\", 0}}),",
                "    #\"Replaced Errors9\" = Table.ReplaceErrorValues(#\"Replaced Errors8\", {{\"Beverage Revenue\", 0}}),",
                "    #\"Replaced Errors10\" = Table.ReplaceErrorValues(#\"Replaced Errors9\", {{\"All Other F&B Revenue\", 0}}),",
                "    #\"Replaced Errors11\" = Table.ReplaceErrorValues(#\"Replaced Errors10\", {{\"Payroll and PTEB Expense\", 0}}),",
                "    #\"Replaced Errors12\" = Table.ReplaceErrorValues(#\"Replaced Errors11\", {{\"Cost of sales - F&B\", 0}}),",
                "    #\"Replaced Errors13\" = Table.ReplaceErrorValues(#\"Replaced Errors12\", {{\"Cost of Sales - Pro shop\", 0}}),",
                "    #\"Replaced Errors14\" = Table.ReplaceErrorValues(#\"Replaced Errors13\", {{\"Operating Expenses\", 0}}),",
                "    #\"Replaced Errors15\" = Table.ReplaceErrorValues(#\"Replaced Errors14\", {{\"Property Taxes\", 0}}),",
                "    #\"Replaced Errors16\" = Table.ReplaceErrorValues(#\"Replaced Errors15\", {{\"Insurance Expense\", 0}}),",
                "    #\"Replaced Errors17\" = Table.ReplaceErrorValues(#\"Replaced Errors16\", {{\"GCM - Leased equipment expense\", 0}}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Replaced Errors17\",{{\"Operating Assessment Amount\", type number}}),",
                "    #\"Replaced Errors18\" = Table.ReplaceErrorValues(#\"Changed Type3\", {{\"Operating Assessment Amount\", null}})",
                "in",
                "    #\"Replaced Errors18\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c676eb26-1023-4985-ab89-14db214ea3de",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "81591a8d-94ff-4073-8184-a6037005763a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "74eef361-1e90-4923-b6f2-b5487be37b4f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1fefdf50-9023-4e86-b41f-c7b888d1c018",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ec44cd82-2c98-413d-bddb-a4135b7e4bf8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cd6e1b9e-14e6-44fe-ab91-247a985e21e3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "fe16d8af-c836-4f31-8a5f-5aae63f3b033",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5fa5b2bc-4aba-41a1-aa54-80c3420cf824",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d2a97f49-7d31-435c-82d0-eb70eac6d4fa",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5d01fb22-617f-42a9-87c4-a9522160b7ff",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7cb63762-55ee-40a3-a48e-16089e20bc94",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e61b5f34-b3d8-44d6-9212-87aa5bebc8e6",
                "ordinal": 3
              }
            ],
            "lineageTag": "85904b65-75e8-42b6-bc0a-c7f1b36735ad"
          }
        ],
        "isHidden": true,
        "lineageTag": "41464cf9-644c-4b18-9c49-0729db7c4dfa",
        "partitions": [
          {
            "name": "LocalDateTable_c676eb26-1023-4985-ab89-14db214ea3de",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Ryan''s Sheet - Comparision'[Year end])), 1, 1), Date(Year(MAX('Ryan''s Sheet - Comparision'[Year end])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_8e9b3a54-d9ce-428d-b308-c3026abaf5d4",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c6ad1e82-ffb4-474a-9763-2a5f17a726a8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d5b0a87a-c14b-40e0-9f59-09d6f635a45c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c4259c33-2fd7-4af7-9cce-fa1defa5f905",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2f3f1f33-7d10-44d5-bab0-494384fb6de6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "53910da5-c810-4df6-a6f2-4b942c8f2b1d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "95307380-d35b-434e-9d5c-10df4a37825b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fcb37e85-9c14-461c-83d0-46ad4c0f2c99",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "da2355fe-86c4-44e7-bcf0-3e46558b0ef3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "cc126c60-c213-4549-b5ec-12f5327ad6e3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "10fe3d41-211d-48f4-b917-279147a425ad",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fc198243-5360-4adf-b4fd-53889327c5d4",
                "ordinal": 3
              }
            ],
            "lineageTag": "7e5afe20-36b1-49ff-aed4-968da11675d3"
          }
        ],
        "isHidden": true,
        "lineageTag": "59ca635e-8cb0-436d-8e57-d19ca8dddace",
        "partitions": [
          {
            "name": "LocalDateTable_8e9b3a54-d9ce-428d-b308-c3026abaf5d4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Ryan''s Sheet - Comparision'[Year end - Copy])), 1, 1), Date(Year(MAX('Ryan''s Sheet - Comparision'[Year end - Copy])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}